### ISSUE TITLE
Changing screen resolutions after a game has launched breaks mouse cursor tracking

### ISSUE THREAD

**Issue by mistydemeo** [renpy/renpy#1053]
I ran into this issue when playing Ladykiller in a Bind.

Steps to reproduce:
1. Launch the game at a lower resolution.
2. Switch to windowed in the game.
3. Switch to a higher resolution in the OS.
4. Switch to fullscreen in the game.

After doing this, the in-game mouse cursor tracking becomes offset from the actual position of the mouse cursor. This becomes obvious when trying to click buttons.

This was originally reported as #94 a few years ago, but closed because of difficulty reproing it. I can repro this consistently in LiaB using the steps above. I didn't take a video, but the video @renpytom posted in that issue is exactly the issue I'm having here.

**Comment by renpytom** [comment]
Is this still on the mac? Did you change the DPI of the system?

**Comment by mistydemeo** [comment]
Still on the Mac; sorry for not clarifying. This is a retina MacBook Pro, running OS X 10.12, native res 2560x1600. I did change the DPI; I launched the game at "larger text", and switched to default scaling.

**Comment by renpytom** [comment]
I'll look into this the best I can, but I'm not hopeful. I don't have a retina mac to reproduce this on, and there's a good chance this is due to SDL or one of the mac system libraries.

Do I understand correctly that this is an easy problem to avoid - it doesn't manifest if you change the resolution before starting the game?
