### ISSUE TITLE
Adding config.say_attribute_transition to LiveComposite transitions

### ISSUE THREAD

**Issue by Samukun** [renpy/renpy#1068]
Note to Tom:

It would be nice if there was a `config.say_attribute_transition` equivalent for LiveComposites with interpolated variables so that renpy just adds a transition by itself whenever an interpolated variable is changed instead of having to add a `with dissolve` every time.

**Comment by renpytom** [comment]
On one hand, this isn't possible, and on the other hand, you can already do it. 

The problem is that Ren'Py doesn't know which variables correspond to DynamicImages, and hence it can't know to cause a transition when they change. 

On the other hand, if you know what the variable are, you can just use a config.python_callback to execute the transition yourself. Or some other mechanism - for example, a custom statement.
