### ISSUE TITLE
werid error TypeError: expected string or buffer

### ISSUE THREAD

**Issue by jeremi360** [renpy/renpy#1074]
I have simple character:
```
pt = Character(player.name + " Thoughts",
                                color = pcolor,
                                what_prefix = "{i}", #it makes text italic
                                what_suffix =  "{/i}")
```

When I try make it to tell any thing I get this error:
`TypeError: expected string or buffer`

But when I reload(using Shift+R) every think is working.

**Comment by renpytom** [comment]
This strikes me as simply wrong, since you're probably not setting player.name until the game starts. (That would cause the problems you're seeing.) Consider using string interpolation instead:

define pt = Character("[player.name] Thoughts", ...)

If you don't think this is the right answer, please re-open this bug and attach the traceback.
