### ISSUE TITLE
Text outlines don't scale along with text when game window is resized

### ISSUE THREAD

**Issue by dansalvato** [renpy/renpy#1092]
If a text style has outlines, then the thickness of the outlines doesn't increase along with everything else being scaled up. For example, my game window is 1280x720, but when I enter fullscreen, my screen size is 1920x1080. This causes outlines to look much thinner when in fullscreen.

To help demonstrate this, I'll use a more extreme example of resolution differences.

Text outline at 640x360:
![image](https://cloud.githubusercontent.com/assets/7810794/21138070/acf1f678-c0e9-11e6-92b4-d7a52c8de56b.png)

The same text at 1920x1080:
![image](https://cloud.githubusercontent.com/assets/7810794/21138077/b5b4e6bc-c0e9-11e6-885b-3180d0af875f.png)

Since the text was scaled up, but the outline remains the same size, the outline appears much thinner.

**Comment by Gouvernathor** [comment]
This is still the case in the last version of renpy.

**Comment by nagilson** [comment]
I'm interested in implementing a fix for this. Do you think this is a good first issue?
  
One idea at first glance is to modify this function:
https://github.com/renpy/renpy/blob/75e87b00db3ba3d05f3d77d75dd7779627f5f902/renpy/text/text.py#L1298 
To scale the outline by some factor based on a ground-truth resolution. I could implement some sort of bool to the outlines style (https://github.com/renpy/renpy/blob/75e87b00db3ba3d05f3d77d75dd7779627f5f902/renpy/text/text.py#L1298) to enable or disable this feature, I would want to consider if it's a "breaking change" for expected behavior in old projects.

**Comment by JSearUK** [comment]
Ran across this while looking for something else:
https://www.renpy.org/doc/html/style_properties.html#style-property-outline_scaling

If that link is not for this, should it be? Or perhaps expanded to include it?

**Comment by Gouvernathor** [comment]
@JSearUK That was it, actually. Thank you for noticing it !
