### ISSUE TITLE
Unexpected behavior when setting character's what_args["slow_abortable"] to False

### ISSUE THREAD

**Issue by dansalvato** [renpy/renpy#1209]
You're probably going to hate me for this, because the "slow_abortable" property was probably put out of use a very long time ago. But I noticed when setting `what_args["slow_abortable"]` to `False`, clicking the mouse advances to the next line even when slow is still in progress. The culprit is in `text.py`:
```python
if self.slow and renpy.display.behavior.map_event(ev, "dismiss") and self.style.slow_abortable:
    self.call_slow_done(st)
    self.slow = False
    raise renpy.display.core.IgnoreEvent()
```
If we're in `slow`, then `renpy.display.core.IgnoreEvent()` should be raised whether or not `slow_abortable` is `True`.

```python
if self.slow and renpy.display.behavior.map_event(ev, "dismiss"):
    if self.style.slow_abortable:
        self.call_slow_done(st)
        self.slow = False
    raise renpy.display.core.IgnoreEvent()
```
If we do this, then the same behavior is elicited when `slow_abortable` is `True`, but if `False` then the event is ignored, and dismiss does nothing.

But if you're more in favor of just removing `slow_abortable` then I would appreciate you clarifying that anyway.

**Comment by renpytom** [comment]
Let's see.

The slow_abortable style property hasn't been documented for years. (Since 5.6.1.) It's working as it had been documented, and it's only being retained for compatibility with ancient games. 

I'm not going to change it's behavior. The fix is also not something I'd want to add. When the player clicks to advance the game, that should always happen, and there should not be a way to ignore it.
