### ISSUE TITLE
_history_list.voice.filename will be None if Voice Sustain is on

### ISSUE THREAD

**Issue by zedraxlo** [renpy/renpy#1228]
When Voice Sustain opened, then:
for h in _history_list:
h.voice.filename will return None in any case.

**Comment by zedraxlo** [comment]
This time, with 6.99.13.2758:
The sentences with no voice will all return _last_voice_play which should return None

**Comment by renpytom** [comment]
Please reopen an issue when you add a comment like this, so I can find it more easily.

**Comment by zedraxlo** [comment]
Sorry, I'm a newer to Github and didn't find the reopen button

**Comment by renpytom** [comment]
No problem, it's just to let you know for the future, since I lost this bug and thought I was going crazy since I remembered it.

**Comment by zedraxlo** [comment]
@renpytom 
They get back to return all None after 6.99.13.2770
for reopen the issue, I found this:
"you cannot re-open your own issues if a repo collaborator closed them"

**Comment by renpytom** [comment]
The problem here is that there are no

**Comment by renpytom** [comment]
Okay, so I've thought about how this should work, and this is what I settled on. 

h.voice.filename is set on initial play, or if the script explicitly says the voice should be sustained. It's not set if the voice sustain preference is set, since that means that voice would be sustained forever.

Hopefully, this should give a reasonable behavior for every game.
