### ISSUE TITLE
ATL animations with dissolve getting cut off in NPOT

### ISSUE THREAD

**Issue by arowana-vx** [renpy/renpy#1249]
Here's another potential bug (sorry for bombarding you so much lately! we've been doing a lot of game testing this month ^^). My example is kind of specific and rare, but I thought I'd report it just in case it's related to any larger NPOT issues. 

When NPOT is enabled, some of my ATL animations with internal dissolve transitions, such as the example below, get cut off at the bottom of the image. 
```
image animation_test:
    "images/sylvie_normal.png" with Dissolve(1, alpha = True)
    pause 1
    "images/sylvie_giggle.png" with Dissolve(1, alpha = True)
    pause 1
    repeat
```

Test project to demonstrate (when the image appears, wait 1 second to see the image get cut off at the bottom):
[NPOT_test.zip](https://github.com/renpy/renpy/files/1295321/NPOT_test.zip)

Some of my observations: 
- this only happens when NPOT is enabled; the animation acts normally after disabling NPOT
- "dissolve" may be the only transition that causes this issue (I had no problem with pixellate, blinds, or squares)
- the image size seems to matter; I wasn't able to reproduce this with smaller images (those shorter than screen height possibly?)

I tested in 6.99.13.2745. Also checked in an earlier version (6.99.13.2527), which did not have this issue. As always, let me know if you need more info and thanks for your help!

**Comment by renpytom** [comment]
Thanks for a solid bug report. I think I've figure out the issue and fixed it. The observation that it only occurred for images larger than the screen height was a key one, what caused it was a render to texture. 

Please send me more issues like this!  Well, I'd rather Ren'Py be bug free, but until then issues like these, with a lot of detail and a great replication, are the next best thing.

One suggestion would be to add:

```
label main_menu:
    return
```

to the start of the script. This will bypass the main menu when it's not relevant. (That's useful for me, since I usually run the game a half-dozen or more times when diagnosing and testing a fix.)
