### ISSUE TITLE
.webp doesn't work with auto-images

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#1298]
As the title says. You can do a simple test: same image, but called test.png shows up if I use:
show test
but if you convert it to .webp the same line doesn't show anything (the gray placeholder with text).
I put it in a sub-directory cg, so the actual call was show cg test, but anyway if it's a PNG it works, but if it's a WEBP not. Thanks

**Comment by renpytom** [comment]
How are you doing auto images? With the images/ directory? This was added in 6.99.13, so if you're not on that it won't work.

**Comment by jacknorton** [comment]
Not only images/ but also other directories. In particular I have a gfx folder with various subfolders named bg, cg, etc.
I can do for example scene bg graveyard and it works fine (having graveyard.jpg in the gfx/bg/ folder). But anything that it's .webp doesn't work.
With previous version it was working, now with the latest release (6.99.13.2919) not.

It also doesn't work the image callback anymore. I had this code:
```
init python hide:
    def missing_image_callback(s):
        if renpy.loadable(s[:-4] + ".webp"):
            return im.Image(s[:-4] + ".webp")
        if not renpy.loadable(s + ".base.jpg"):
            return im.Image("blank.png")
        if not renpy.loadable(s + ".mask.jpg"):
            return None
        return im.AlphaMask(im.Image(s + ".base.jpg", cache=False),
                            im.Image(s + ".mask.jpg", cache=False))
    config.missing_image_callback = missing_image_callback

```
so it would try to look for PNG but if couldn't find it, would automatically load the same image with .webp but now even this doesn't work anymore (in previous version it was).
For example I had:
image i_zephyr = "gfx/combat/p_zephyr.png"
and even if at end of development I converted all .PNGs to .webp (renaming the old .png .bak) the game would work normally, now it can't find the images anymore.

So something definitely changed from previous stable release to the latest :(

**Comment by epadder** [comment]
Still have this issue in current 6.99.14.3.3347.  Any webp files in subfolders of the image directory are not recognized automatically.  If they are in the image directory they can be called by name without extension I.E. scene backgrounds_17 will work but backgrounds 17 won't.  I have a stupid little function I wrote before I realized auto image definition was possible... but I'd rather not use it even if it works.

This is how I have the automatic images configured atm.
define config.automatic_images = [ '/', '_' ]
define config.automatic_images_strip = [ "images", "characters" ]

**Comment by renpytom** [comment]
I'm not going to fix this. 

automatic_images is a very old thing, that never worked particularly well. In the common use case, it's been superseded by the images/ directory. In the less common use case, you can just use a mix of renpy.list_files and renpy.image to do what you want to accomplish in a more flexible way. I'd suggest that your "stupid little function" is the right way to do this in a properly flexible manner.

**Comment by epadder** [comment]
Okay, my stupid function was really stupid btw... I had to feed in parts of the path, the # of files, and the extension basically to initialize the images per scene. Anyway though I guess if anyone else has this problem and they are a renpy newbie like me... I found out that the images in sub directories are auto defined (not by automatic_images) but just by the filename not the path.
**I.E.** character/Bob/scene1/1.webp 
would be 
**show 1**
not 
_show character Bob scene1 1_
Which is a slight issue for me because I want to have the directory structure be a part of the name to keep things organized. Another issue that arises is that if filenames aren't unique then they overwrite each other and whatever was picked last becomes the file that is used. I did read up on renpy.list_files (didn't know it was a thing) though and made a better function that will define the images the way I want to keep them organized.
