### ISSUE TITLE
renpy.say(interact=False) doesn't record voice to history....

### ISSUE THREAD

**Issue by vollschauer** [renpy/renpy#1348]
Not sure if it's a bug or not, but interact=False doesn't generate a voice entry in the history.
Also if you comment the first narrator line out then you'll have the first "voicefile1" entry also recorded to the second say line.
```
define e = Character("Eileen")

label start:

    voice "a_0001"
    $ renpy.say(e, "You've created a new Ren'Py game.", interact=True)

    "Now you see a voice entry in History (Comment this line out in the next run)"

    voice "a_0002"
    $ renpy.say(e, "You've created just another Ren'Py game.", interact=False)

    $ renpy.pause()

    "This will NOT add a voice entry to History"

    "End"

    return
```
In the histroy screen, just change this line to see if there is a voice or not
`text what + str(h.voice.filename)`

**Comment by vollschauer** [comment]
![image](https://user-images.githubusercontent.com/5165216/34829887-6d9697ec-f6e2-11e7-9ed9-b93f2490aa58.png)
![image](https://user-images.githubusercontent.com/5165216/34829941-a3a564a8-f6e2-11e7-8927-9f71f1e7af4d.png)

**Comment by renpytom** [comment]
I don't think this is a bug. 

I wouldn't expect renpy.say(..., interact=False) followed by a pause to be equivalent to a proper say statement. So I don't think it's a big deal that we're not processing voice in the same way we would when a voice is actually playing.

Is there some argument for doing this, rather than simply using a say statement as one would expect?

**Comment by vollschauer** [comment]
Well the pause was just an example, the "real" reason why I'm doing this, is because I have to do some character animation in the "middle" of the say and extend line without hiding the text.
