### ISSUE TITLE
Screens with ATL hide don't roll back correctly

### ISSUE THREAD

**Issue by eevee** [renpy/renpy#1404]
```
transform dummy_reveal:
    xcenter 0.5
    yanchor 0.5
    ypos 0.5
    on show:
        ypos -0.1
        linear 0.5 ypos 0.5
    on hide:
        linear 0.5 ypos -0.1

screen dummy():
    frame:
        xsize 50
        ysize 50
        background '#fff'
        at dummy_reveal

label start:
    "Hello."
    show screen dummy()
    "Okay, now, wait for it..."
    "Wait for it..."
    "..."
    hide screen dummy
    "Okay!  Now try backing up."
    "I said back up!"
```

Play through the script until just after the `hide screen`, then step backwards once.  The hide animation plays _again_.  The displayables inspector indicates the screen is still "shown", but it's off-screen and inaccessible.

Stepping back further leaves the screen inaccessible, until you hit the line "Okay, now wait for it...", at which point the show animation plays again.  Stepping back once more will immediately hide the screen as expected.

If I use an image instead of a screen:

```
    show expression Fixed(Solid('#fff'), xsize=50, ysize=50) as dummy at dummy_reveal
    # ...
    hide dummy
```

...then backing up through the `hide` instantly shows the image as expected, and it remains visible as I continue to step backwards.  (The show animation does still play when I step _backwards_ onto the "Okay, now wait for it..." line, though, which is a bit weird.)

**Comment by renpytom** [comment]
The thing to realize about this is that rollback tries to put Ren'Py into a state it was in at some point in the past. That state is right after the last statement that checkpointed, which is the "hide screen dummy" statement. The dummy screen is displayed, it's hidden, so we trigger the animation again. 

Similarly, when it goes back to just after "Hello", the show screen is triggered, and you get the animation. 

I like this, since while it's a little weird, it's in a sense correct. Your transform could have not bothered to set the ypos, which means that if on show was never triggered, ypos would not have been set. 

I don't see any difference between show expression and what I have here. I now have:

```renpy
transform dummy_reveal(xpos):
    xpos xpos
    yanchor 0.5
    ypos 0.5
    on show:
        ypos -0.1
        linear 0.5 ypos 0.5
    on hide:
        linear 0.5 ypos -0.1

screen dummy():
    frame:
        xsize 50
        ysize 50
        background '#fff'
        at dummy_reveal(200)

label start:
    "Hello."

    show expression Fixed(Solid('#ccf'), xsize=50, ysize=50) as dummy at dummy_reveal(100)

    show screen dummy()

    "Okay, now, wait for it..."
    "Wait for it..."
    "..."

    hide screen dummy
    hide dummy

    "Okay!  Now try backing up."
    "I said back up!"
```

And both boxes do the same thing. (Note that this bounced around on the nightly/git versions as I tweaked some things, so you might have been caught up in that.)

**Comment by eevee** [comment]
Your screen rolls back goofily as I described in 6.99.13, but it matches the `Solid` in current master (and my example is fixed as well), so whatever you were doing (f69c46?) seems to have fixed it  :)

**Comment by renpytom** [comment]
Ok, closing this. Probably had to do with transform reuse, which has been fixed.
