### ISSUE TITLE
Layeredimage 'at' clauses don't behave as expected

### ISSUE THREAD

**Issue by SpikyCaterpillar** [renpy/renpy#1438]
- Animated transforms don't animate; instead, they appear to complete instantly. (This might be necessary for layeredimages to make sense, but it's not mentioned in the docs)

- The docs say 'at' will accept a list of transforms, but feeding a layeredimage a list (e.g: 
`attribute from_u1 "ellen/uniform1.png" at [renpy.store.fadeoutonreplace]`
) crashes with a complaint that the list is not callable.

- Layered images are in their own namespace, so renpy.store needs to be prepended to all transform names.

My ultimate goal was to use LayeredImage to more-cleanly manufacture pose-change animations, because my current code is full of stuff like:

```python
image ellen fade_uniform1_cheerful_uniform2_neutral:
    EllenSprite('pose1','cheerful') # EllenSprite actually builds the im.Composites
    EllenSprite('pose2','neutral') with posechange
    # 'with' in the image itself because I only want the posechange fade to occur when I'm switching
    # poses, while afaik 'on replace' has no easy way of deciding what to do based on what was
    # showing last, and I want the next line of dialogue to display without waiting for the pose-change
    # to complete.  The window-during-transitions option ALMOST works for me but iirc keeps the
    # window blank until the anim is done.
```

**Comment by renpytom** [comment]
The second and third bullets were fixed by a very small change, a mistake on my part. 

The first one isn't a bug - I think you're misunderstanding what layered image is intended to do. A simple animated layer works - if you have:

```
transform blink:
    alpha 1.0
    linear 1.0 alpha 0.0
    linear 1.0 alpha 1.0
    repeat
```

Then "at blink" (and now "at [ blink ]" ) will work with a layeredimage. What won't work is something that tries to use `with` to move from one image to another. Layeredimages are images, and right now the different versions of an image aren't related to each other. So with, in particular, won't work. 

Although it's not elegant,

```
show ellen:
    "ellen pose2 neutral" with posechange
```

will work and do what you want. Something very similar would be:

```
show ellen pose2 neutral
$ renpy.transition(dissolve, layer='master')
```

At least right now, I don't want layeredimage to take arbitrary ATL. I'm open to maybe that happening in the future, when there's more experience with them,  but for now they're a replacement for (Live)Composite and ConditionSwitch. 

I'm going to reopen this, though, since I just had an idea I'm going to want you to try.

**Comment by renpytom** [comment]
I think this has been fixed, and you know my new idea (with dict), and so I'm going to close this now.
