### ISSUE TITLE
Make a sound every time a character appears

### ISSUE THREAD

**Issue by anoadragon453** [renpy/renpy#1464]
It would be nice if it were possible to have a short 'blip' sound every time a character of text appeared when cps were set to something other than 0. [An example](https://www.youtube.com/watch?v=Min0hkwO43g)

Should be optional.

**Comment by renpytom** [comment]
Nah, I don't think there's a good reason to add natives support to Ren'Py for being really annoying. 

That being said, Ren'Py does have support for playing back annoying text beeps, see an (old, but still relevant) example here:

https://www.renpy.org/wiki/renpy/doc/cookbook/Expanded_Text_Bleeps

**Comment by jessebrands** [comment]
I hope it's okay for me to comment on this issue again cause this does not at all solve my problems; or perhaps there's a way to solve this already. The VN I am developing is also using blips, specific ones for each character. This part works fine and I wrote python code to facilitate that.

What I am unable to do however, is have the rate of the blips be related to the CPS value. When text appears slowly, I would also like the blips to appear more slowly.

It would be great if there could be an event in renpy that was something along the lines of "show_text" that is called every time Ren'Py renders some new characters into the say screen. This could have other uses than blips too.

On that note, is there a way to get the _actual_ CPS value in Python? That way I could at least work out something myself. I can easily get the 'preference' value but that is not the same as what happens in a {cps=#} block.

Thanks in advance. I really appreciate all the hard work that has gone into Ren'Py, and would gladly contribute these changes myself if you think it is a good idea.

**Comment by GCMarvin** [comment]
I wanted to comment on this because I've been having the exact same problem. The [provided example](https://www.renpy.org/wiki/renpy/doc/cookbook/Expanded_Text_Bleeps) only loops a specific sound, but does not allow for further customization. I am currently working on a VN where (similar to Animal Crossing for example) each character/syllable should have a different sound associated with it, and for that it's required to know when each character is displayed. A callback would immediately solve that, but since that doesn't exist I'm currently creating a workaround.

<details><summary>This is my WIP attempt at solving this (click to expand):</summary>

```py
init python in bleeper:
    from time import sleep
    from renpy.text.textsupport import TAG, TEXT, PARAGRAPH, DISPLAYABLE

    def screen_callback(who: str, what: str):
        if who is None and what == "":
            return

        cps_base = renpy.store.preferences.text_cps
        cps_fixed = None
        cps_mult = 1.0

        what_displayable = renpy.get_displayable("say", "what")
        tokens = what_displayable.tokenize(what_displayable.text)

        global segments
        segments = [[]]

        for kind, token in tokens:
            if kind == TEXT:
                wait = 1 / (cps_fixed or cps_base * cps_mult)
                for char in token:
                    if char.isalnum():
                        segments[-1].append(("a.wav" if who == "A" else "~.wav", wait))
                    else:
                        segments[-1].append((None, wait))

            elif kind == TAG:
                if "=" in token:
                    key, value = token.split("=", 1)
                else:
                    key, value = token, None

                if key == "w":
                    segments.append([])

                elif key == "cps":
                    if value[0] == "*":
                        cps_mult = float(value[1:])
                    else:
                        cps_fixed = float(value)

                elif key == "/cps":
                    cps_fixed = None
                    cps_mult = 1.0

            else:
                raise ValueError(f"Token kind '{kind}' is not supported yet.")

    def character_callback(event: str, interact: bool, type: str):
        if not interact or type != "say":
            return

        elif event == "show_done":
            global cancel_token
            cancel_token = []
            renpy.invoke_in_thread(__play_segment, cancel_token)

        elif event == "slow_done":
            cancel_token.append(True)

    def __play_segment(cancel_token: list):
        for sound, wait in segments.pop(0):
            sleep(wait)

            if cancel_token:
                return

            if sound is not None:
                renpy.sound.play(sound, "voice", tight=True)

screen say(who, what):
    ...
    on "show" action Function(bleeper.screen_callback, who, what, _update_screens = False)

define config.all_character_callbacks += [bleeper.character_callback]
```

</details>

Basically, I add an `on show` callback `bleeper.screen_callback` to the say screen, in which the said text is tokenized into segments. Usually, there's only one segment per say statement but any {w} will split the text into multiple segments, since a after a wait the time at which the letters are displayed cannot be reasonably predicted. Each segment then contains a list of tuples of a soundfile to play and the delay after which to play it.

Regarding @jessebrands' problem: I don't think you can easily get the current `cps` value directly, but you can calculate it if you have the whole text with the tags, which I do with this approach. I set `cps_base = preferences.text_cps`, `cps_fixed = None` and `cps_mult = 1.0`. Then I go through the characters being displayed, and each character gets assigned a delay of `1 / (cps_fixed or cps_base * cps_mult)`, so if we're currently in a fixed cps block, it's based on that, otherwise it's based on `cps_base * cps_mult`. While I go through the text, if any `cps` block is detected, the fixed or mult value is set accordingly, and detecting a `/cps` resets both of them.

This will setup which sounds to play at which delay, since it immediately runs before the character callback is called with `show_done`. So I setup a global callback `bleeper.character_callback` for all characters. If it's called with `show_done` it starts a new thread that plays the next segment, if it's called with `slow_done`, it toggles a cancellation token, so that the thread terminates early if for example the player skipped clicked to skip the text.

This plays *reasonably* well with most things, wait tags and cps tags are handled good enough, and it allows for enough customization. In the code example I just use "a.wav" if the character speaking is "A", otherwise I use another sound, but this can easily be expanded, for example by giving each character a different sound, or passing a custom argument through when defining the character that contains the sounds that are to be used.

There are a couple issues with this (as you might guess), most importantly that a few tags mess the timing up. For example the {nw} tag (for a reason that I haven't figured out yet) doesn't immediately skip sometimes. Surely there are better options than this workaround, and I agree with @jessebrands that a callback for every character being displayed would be a valuable addition to RenPy.
