### ISSUE TITLE
Frame based ATL races within a screen

### ISSUE THREAD

**Issue by morganwillcock** [renpy/renpy#1650]
Hi,

I've been trying to optionally add an ATL based animation to a screen, but it seems this isn't possible using `if` or `showif` if the animation is based on individual images and the pause statement.

So given this animation of a door opening:
<pre>image door opening:
    "door d1"
    pause 0.10
    "door d2"
    pause 0.10
    "door d3"
    pause 0.10
    ...</pre>
This results in the animation already being played, before use_door is True:
<pre>  if use_door:
        add "door opening":
            xpos 26
            ypos 86</pre>
...which seems fair enough, but using `showif` doesn't work either unless use_door becomes True immediately after the screen opens:
<pre>  showif use_door:
        add "door opening":
            xpos 26
            ypos 86</pre>
It seems that the more time spent idle before showing the animation, the faster the animation will race in-order to catch up. I thought I would use a movie sprite as a workaround, but it seems there is no option to play a movie sprite without having it loop.

Test project with just this issue defined can be downloaded from [here](https://www.dropbox.com/s/5m75l4v6ns1bcpo/add_atl.tar.gz?dl=1).

Thanks!

**Comment by Andykl** [comment]
More obvious code
```
image solid_based_anim:
    Solid("#fff", xysize=(100, 100))
    pause 0.5
    Solid("#fff", xysize=(90, 100))
    pause 0.5
    Solid("#fff", xysize=(80, 100))
    pause 0.5
    Solid("#fff", xysize=(70, 100))
    pause 0.5
    Solid("#fff", xysize=(60, 100))
    pause 0.5
    Solid("#fff", xysize=(50, 100))
    pause 0.5
    Solid("#fff", xysize=(40, 100))
    pause 0.5
    Solid("#fff", xysize=(30, 100))
    pause 0.5
    Solid("#fff", xysize=(20, 100))
    pause 0.5
    Solid("#fff", xysize=(10, 100))
    pause 0.5
    Null()
    pause 0.5
    repeat

screen test:
    default time = 0.0
    default visible = True
    key "r" action Return()
    key "t" action ToggleScreenVariable("visible")
    timer 0.01:
        repeat True
        action SetScreenVariable("time", time + 0.01)
    text "[time]" align(0.1, 0.9) size 40 color "#f00"
    vbox:
        yalign 0.5
        xalign 0.5
        spacing 50
        hbox:
            spacing 10
            for i in range(10):
                fixed:
                    xysize (100, 100)
                    if time >= i * 0.5 and visible:
                        add "solid_based_anim"
        hbox:
            spacing 10
            for i in range(10):
                fixed:
                    xysize (100, 100)
                    showif time >= i * 0.5 and visible:
                        add "solid_based_anim"

label start:
    while True:
        call screen test
    return
```
For if, the image starts with st stored in the screen.
For showif, the image starts with st = 0 but starts the race to the stored value.

**Comment by renpytom** [comment]
I'm closing this as old, but please reopen if this hasn't been fixed.

**Comment by morganwillcock** [comment]
It still looks to be a problem. Andykl's test still shows the timing is wrong when using showif.

**Comment by Gouvernathor** [comment]
May get fixed by #3305

**Comment by Gouvernathor** [comment]
May get fixed by #3305

**Comment by mal** [comment]
I don't think that would impact this issue as it primarily deals with interpolations, whereas this issue revolves around distinct ATL instructions. With that said, there are certainly similarities how this presents, and both revolve around forced frames, which I'll circle back to in a moment (see last paragraph).

In reviewing Andy's test case the observed behaviour broadly matches what I would expect:
- When using `if` to control the display the displayable its `st` is linked to when the it (the displayable inside the `if`) is first shown. This seems both sane, and to solve the initial problem outlined in the issue. I believe this was fixed in 40fdecc0e0de9fe5cca88d64a9ae9e3dac3f244d.
- When using `showif`, then the documentation is very clear that anything within will be getting rendered all the time, and only its display will be limited, so it makes sense that the displayables internal understanding of `st` would be when it was first rendered, not when it first became visible, which explains why it does catch up.

The caveat to this is that when using `showif` the ATL catch up is visible due to forced frames. This can be avoided by setting `config.atl_one_frame = False`, which allows the catch up to occur without presenting frames to the viewer, however this setting can lead to oddities in other cases which is why it probably shouldn't be treated as a solution to this.

**Comment by morganwillcock** [comment]
Is it feasible to have the setting work per displayable by implementing it as a transform property?
```py
showif True:
    add "solid_based_anim":
        one_frame True
```

**Comment by Andykl** [comment]
@mal 's analysis is correct. Setting `config.atl_one_frame = False` fixes the race.
About the solution, I think @morganwillcock idea is good. But we need to invistigate what is more common, the need of `one_frame False` or `one_frame True` and set `config.atl_one_frame` to that value.

**Comment by Gouvernathor** [comment]
I'm not convinced this is a kind of issue where two solutions can be good in different contexts (like #3336 is). one_frame should be disabled in that specific context of racing towards a time, and enabled otherwise. I don't think it should be left for creators to patch manually.
Plus, the decision of adding a transform property shouldn't be taken lightly, since that's a very difficult thing to unsupport later.

**Comment by mal** [comment]
I agree with @Gouvernathor. I don't think an ATL property is the way to fix this. The one_frame behaviour was introduced to support single frame animations (i.e. displayables separated by `pause 0` in an ATL block), and revisited last year to also support the animated shader case (`shader xyz`, `pause 0`, `repeat`), both of which seem fairly specific, but also beyond the depth of knowledge we should expect or require a creator to have to not fall foul of this issue.

Unfortunately, I don't have a more comprehensive solution to this issue than the change I already PR'd for handling this issue strictly within the context of interpolations, and I suspect this issue ends up even closer to the core of the ATL state-machinery. :/

**Comment by Andykl** [comment]
@mal So, you think that the solution is to do one_frame only in case of `pause 0`?

**Comment by Gouvernathor** [comment]
If that's the sole context where atl_one_frame is useful, then I'd go that way. If not, we should special-case every context where it's useful.
The way I would have done it intuitively would be to detect whether we're racint towards a time, and disable one_frame in that context as one special case.

**Comment by mal** [comment]
I don't feel like I have a strong feeling on what the solution to fix the general case for this is at the moment. I was more seeking to present a little context around how one_frame became what it is today, and the explicit use cases involved; however, that shouldn't be interpreted as them being the only use cases, that now rely upon it.

The disabling/ignoring one_frame during catch-up is pretty close to the premise of the existing mitigations, including 3305, but with the complexities of nested-ATL blocks and so on it's not always a straight-forward proposition for the code to understand if it's in catch-up, which I think is really the core difficulty. Issues like this have come up in a few contexts during development, and it seems we keep managing to find more.

**Comment by morganwillcock** [comment]
I think based on the context of the displayable either behaviour could be valid. It just happens that in this case my animation of opening a door is not something that I would want to have an accelerated animation speed, but in some other circumstance it may be more appropriate to show all frames to catch up - possibly someone is already relying on it; it has been 3 years.

If not a transform option then the most flexibility might be that the timing expressions within the ATL definition indicate potential skips, or frames mark themselves as a dominant frame which is skipped to when timing needs to catch up. But I'm not really a fan of trying to jam more complexity into ATL definitions if it can be applied externally.
