### ISSUE TITLE
Menu sets not working.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1688]
https://lemmasoft.renai.us/forums/viewtopic.php?p=503285#p503285

**Comment by DragoonHP** [comment]
This bug was introduced with this commit > https://github.com/renpy/renpy/commit/56fe28955a44583978da4d8bfc054b7205a3a176#diff-c19da65f3630a916cdd2146185cebe95

When `config.menu_actions` is True, items list is made of [label_name, ui.ChoiceReturn] class and so it returns False in the `if value == rv` check.

Adding an `__eq__` method to ChoiceReturn class fixes it.
```
    def __eq__(self, other):
        return other == self.value
```

Though to note, the game will still get stuck if a circular menu is used (that is choosing an option returns you to the menu). The game will become unresposnsive when the player will have chosen all the options/caption.

**Comment by renpytom** [comment]
Thank you. You basically pointed me into the right place. I don't think that adding __eq__ was the right solution, so I implemented it a different way, by retaining the original values that were passed into menu(). But the `value == rv` check being wrong was the root of the problem, and I thank you for finding it.

**Comment by DragoonHP** [comment]
Cool. :)

What about the edge case, where a circular menu can get the game to become unresponsive?

```
    $ first_menu = []
    menu test_1:
        set first_menu
        "Choice A":
            "A"
        "Choice B":
            "B"
```
