### ISSUE TITLE
Python function runs twice if there is dialogue

### ISSUE THREAD

**Issue by newbiemate** [renpy/renpy#1794]
My python function keeps running twice IF I have dialogue in the same block.

Here is an example:
```
init -1 python:
    def testme():
        print "hello"
        return

label start:
    $ testme()
    
    "hi"
    return
```

This will print **"hello"** TWICE in the developer console (SHIFT-O). 

If I remove the dialogue **"hi"**, then the function will only print **"hello"** ONCE.

Is this issue a bug? I was only expecting it to run the function once since I'm making a call to it only one time.

I am using latest renpy v2.2.

**Comment by newbiemate** [comment]
I guess it doesn't really matter? From my tests, only the last run matters.

Ie,

    
```
init -1:
    default i = 0
    default j = 0
    
init -1 python:
    import random
    def testme():
        global i
        global j

        print "hello"
        i = random.randint(0,100)
        j += i

        print i
        return

label start:
    "dawg"
    $ testme()
    
    "hi"
    $ print(i)
    $ print(j)
    return
```

The value `j` will only be the result from the second run, not the first. 

But still, is this intended behavior from renpy or a bug?

**Comment by renpytom** [comment]
This should be fixed in the latest nightly, in the
```
print("hello") 
```

case, while the 

```
print "Hello." 
```

case will remain broken (since it's obsolete, and would be hard to fix). 

The problem was basically where Ren'Py chose to insert a rollback checkpoint, which was generally before the print statement. This means that upon entering the console, it would roll back past the statement, then re-run it. (The console uses rollback to enter itself.) Ren'Py now inserts checkpoints after debug prints, which should fix this problem. 

See e210147343ab6938ca9fc7352eb98deddfd953b9 and e4b33e595a656f4210a94465384be1938fb4a048 .
