### ISSUE TITLE
[QUESTION] Can we use the source code to mod RenPy in a way?

### ISSUE THREAD

**Issue by JavasPichu** [renpy/renpy#1974]
I'm sorry if we aren't allowed to ask questions on here, but I've been interested in RenPy's code and how it functions and such. And I had a question if we wanted to modify RenPy in a way could we use the source code?

If we can I'll respond with an additional question as soon as I can, if we aren't able to do so thank you for taking your time to respond to my question.
Thank you!

**Comment by renpytom** [comment]
Yes, please check the license for details.

I'm not really interested in supporting "mods" of Ren'Py, and to be honest it's very hard to distribute a changed version, just because it's difficult to compile for so many platforms. But if you'd like to contribute your changes back to Ren'Py, I'd be happy to review them.
