### ISSUE TITLE
Problem moving with keyboard / DPAD& selecting default button

### ISSUE THREAD

**Issue by ratalaika** [renpy/renpy#2059]
[buttonissues.zip](https://github.com/renpy/renpy/files/3841975/buttonissues.zip)
Hello,

We're having issues to move with DPAD/Left Sick/Arrow buttons on the options menu of the game and to select default buttons (repro project attached).

Issue 1.
Once we're on options screen [Unseen Text] is selected, if we move down till [START] button we can't get back to [Language...] button ever again untill we select options again. When we press UP button nothing gets selected instead of selecting any of the inside buttons of options screen.

Issue 2.
default_focus seems to not work with navigation buttons (for game menu and gallery), even though it should...?
When selection for example [ABOUT] menu ideally we would select the [ABOUT] button again so if you then press LEFT/RIGHT you do to either [OPTIONS] or [QUIT] but at the moment it doesnt get selected again. It's strange because on [LOAD] button it seems to work.
Also when selecting [OPTIONS] the first time [Unseen Text] get's selected but if we go down to [OPTIONS] button again and confirm [Unseen Text] is not re-selected we've to swap menus for it to be selected again.

Thank you very much.

Adrian,
Ratalaika Games S.L.

**Comment by morganwillcock** [comment]
I had a look, and it seem the first issue is because everything is in a viewport and the viewport is set to be draggable. How a viewport should accept controller focus I'm not sure, but once it has focus then directional control is a valid way to scroll it, perhaps being draggable prevents the focus being removed once you hit the viewport edges. For the general case with controller support it works if you stop the viewport being draggable, plus (in this particular case) everything already fits the screen so I guess you don't need a viewport and it is likely that a controller can never operate the drag mechanics anyway.

<pre>--- screens_old.rpy	2019-11-16 00:14:22.000000000 +0000
+++ screens.rpy	2019-11-16 00:14:57.000000000 +0000
@@ -432,7 +432,7 @@
                     yinitial yinitial
                     scrollbars "vertical"
                     mousewheel True
-                    draggable True
+                    #draggable True
                     pagekeys True
 
                     side_yfill True</pre>

For the default_focus, that worked when I tried setting it directly:
`textbutton _("About") action ShowMenu("about") default_focus True`
...and it looked like it was working for "Unseen Text" too, so I couldn't recreate that issue.

For the final issue, I'm not sure there is a way to override the control order. Perhaps someone else would know, but otherwise you can probably store the previous selection and restart the interaction once the lower screen is active or when you get the keycode for 'down' once you are on a control that is at the lowest level of the sub-menu, to then specify the default button using default_focus for the main menu.

**Comment by renpytom** [comment]
Closing this, as this is a specific case of focus being weird with viewports, that needs to be addressed at a higher level.
