### ISSUE TITLE
Removing attributes from a layeredimage with the Interactive Director

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2065]
https://lemmasoft.renai.us/forums/viewtopic.php?p=520593#p520593

**Comment by JackkelDragon** [comment]
I've been using a customized version of the director to try to get this functionality. It's not very clean/robust, in that it skips a logic check that I couldn't figure out how to modify. I've not seen any issues with it yet, but I can't promise it doesn't let something slip somewhere, since I'm guessing the logic check existed for a reason.

Functionality:
- left click on attribute not on line: as before
- left click on attribute not on line: as before
- left click on attribute negated on line: removes negation and adds attribute
- right click on attribute that is not negated on line: removes attribute (if present) and adds negation
- right click on attribute that is negated on line: removes negation

[sample](https://github.com/renpy/renpy/files/5962818/00director.zip)

(On a related note, I'd love to be able to use attributes like fadein/fadeout on music and the audio namespace from the director, but I've not had much luck with the former and had to hack around to get something like the latter.)

**Comment by Gouvernathor** [comment]
Merged in d5a816c4fe4abbcf73801714e198ffca1cc1e04c.
