### ISSUE TITLE
Self-voicing not respecting emphasize_audio setting

### ISSUE THREAD

**Issue by StefanGagne** [renpy/renpy#2079]
I've got the following code in my game, to ensure that whenever a voice line or sound effect is played, my music drops to a low volume to make sure nothing gets drowned out:

    preferences.emphasize_audio = True
    config.emphasize_audio_time = 0.25
    config.emphasize_audio_volume = 0.15
    config.emphasize_audio_channels = [ 'voice', 'sound' ]

But the problem is that the self-voicing system for visually impaired users does not follow these rules, applying no audio ducking whatsoever. This is especially noticeable on the main menu of the game, where things like "Start" and "Load" are drowned out by music.

I realize the voicing is being handled at the system API level by something outside renpy, but would it be possible for Renpy to still apply the same audio ducking rules?

**Comment by renpytom** [comment]
I don't believe this is possible, but I'll leave this open until I can check in more detail.

**Comment by stickbear2015** [comment]
If I remember how renpy’s implementing this, it’d have to be a duck the game volume first, speak whatever needs speaking through the sapi engine, then bring it back up. That could also, now that I think about it, introduce a whole other can of issues, lag/timing problems, etc. Now I could be in the wrong ballpark to, since I’m just digging into this thing myself.

**Comment by renpytom** [comment]
I'm going from memory here, but my vague recollection is that the SAPI command terminates immediately, without waiting for the voice to complete. That means that there isn't any feedback from tts back into Ren'Py proper, telling us that self-voicing is done.

**Comment by stickbear2015** [comment]
Oh, well balls.

I wonder if we could add something that comes up before the main menu of any game that’s built with self-voicing aspects that says to enable self-voicing for blind/vi users, press V. and when you hit V, that then tells the engine, ok, nock your musical volume back to 50-70% instead of 100.

Am I even coming up with the right set of ideas?

**Comment by renpytom** [comment]
I guess my question is - is this a real problem that needs to be dealt with on a game-by-game basis? Wouldn't a VI user that listens to any sort of media on their computer have SAPI's volume set to be higher than the media they listen to?  (I have no idea, to be honest.) 

Basically, I don't want to get into a situation where hitting the V key then makes a ton of changes the player has to undo. (We're already at the point where I have to talk creators out of disabling the self-voicing.)

**Comment by stickbear2015** [comment]
Not necessarily. Some users are just enough of a user they can do what the user I had do, load the game, and then can’t hear diddly squat, because the music barries SAPI.
By default the music volume on most games, is originally set at 100% and when you add self-voicing into the mix, especially when it’s not pre-recorded in the game, you have to strain to hear it enough to get into prefs then find your way over to music volume to change it to your liking so it balances so you have a good gaming experience.
If any of this isn’t making sense, I’m happy to take this off this thread and we can talk sapi and screen reader mechanic’s and gaming somewhere else. :)

**Comment by renpytom** [comment]
I'm actually finding this very valuable, and would like to continue it here. I do wonder if perhaps some sort of volume multiplier for the music and sound (sfx) mixers that kicks in when self-voicing is enabled might be the way to go. Rather than the duck-for-voice that we have, what would you think of something that just drops music by 50% when self-voicing is enabled. (I could make the amount adjustable in the accessibility menu - it would be hard to make it adjustable with the normal mixers.)

**Comment by stickbear2015** [comment]
That, actually makes a lot of sense.

Would it add any breakage to existing projects?

**Comment by StefanGagne** [comment]
That's pretty much my solution as well -- if the story starts and voice is enabled, I drop the volume back by half. But that's only AFTER they start a new game, and the issue here is the menus for a freshly installed game. So I'd be in favor of a config-variable controlled means of dropping the music mix.

If the default value is "nah dawg, don't change my mix" then it shouldn't break any existing projects.

**Comment by renpytom** [comment]
I can't think of it. I'll toss together an implementation later today, and ideally Stefan can backport it so we can try things out. (Ren'Py's master branch is kind of a giant mess at the moment, such that I haven't been able to make nightly releases.)

**Comment by stickbear2015** [comment]
can we also, probably on a game by game bases, put something in that, for example even before the main menu loads says something like. "This game has self-voicing capabilities for blind and visually impaired users. To enable this, press "V" when you hear the music.
note: we probably only need give this prompt once per installation.
I'm probably jumping ahead of the game. :)

**Comment by stickbear2015** [comment]
oh, I know it's a mess, because I can't currently build it. rofl.

**Comment by renpytom** [comment]
I'll let that prompt be the responsibility of the game developer. I don't feel it's my place to inject text into a game like that, and I think it's probably best to just spread the word that self voicing and the accessibility menu work in all modern Ren'Py games.

**Comment by stickbear2015** [comment]
that makes sense. :) I'm totally running on little to know sleep, so sometimes I don't think things all the way through. :)

**Comment by renpytom** [comment]
Get some sleep, then. :)

**Comment by stickbear2015** [comment]
I can't sleep at work. shhhh. :) even if their's nothing to currently do, that's why I'm poking around ren'py, because I don't have access to the tools I need to do my job! 👍 )

**Comment by renpytom** [comment]
So, just landed my proposed solution for this. 

It's a bit complicated, and includes some unrelated spacing changes (thanks, eclipse). But if you want to test this, probably the easy way would be to change line 377 of  renpy/audio/audio.py to be:

```python
￼        mixer_volume = renpy.game.preferences.volumes.get(self.mixer, 1.0)
￼
￼        if renpy.game.preferences.self_voicing:
￼            if self.mixer not in [ "voice" ]:
￼                mixer_volume = mixer_volume * 0.5
￼
￼        vol = self.chan_volume * mixer_volume
```

This is a simplified version that doesn't require the other changes. The 0.5 is the amount to duck the non-voice volumes by - I figured 50% is a good starting point, but feedback is welcome.
