### ISSUE TITLE
screen prediction not working while video playing. Introduced - 6.99.14.1

### ISSUE THREAD

**Issue by misterJL** [renpy/renpy#2082]
As stated. Image prediction does work however. Tested on multiple machines.
This is especially problematic when using video loops for BGs. Worked before 6.99.14.1.

**Comment by renpytom** [comment]
Screen prediction is very expensive, so we only do it when video is not playing. I believe it was disabled because it lead to skips in video playback. It's up to you to either leave Ren'Py time to predict screens, or to manually predict the images used by those screens. 

I don't think this is actually an issue.
