### ISSUE TITLE
Force Recompile doesn't delete rpyc files for removed files.

### ISSUE THREAD

**Issue by thatwannabecat** [renpy/renpy#2122]
When running force recompile it won't delete rpyc files if there is no corresponding file to it. This can produce unexpected results in the code, that will be confusing to developers.

https://www.dropbox.com/s/nr5gubgp59jfthp/ImproperClean.zip?dl=0 src.

https://www.dropbox.com/s/wkwapya0s3hfsrk/ImproperClean-1.0-dists.zip?dl=0 distribution. The rpyc survived even a force recompile.

**Comment by Andykl** [comment]
I came across this by accident and I think I've figured out what the problem is. Force Recompile from the main menu will replace all orphan rpyc with rpyc.bak, whereas Force Recompile in build does not do this.
I'm not sure what is correct behavior here.

**Comment by maLikiz** [comment]
I need some help. I generated translations and rolled back the changes in gitlab, thereby `.rpyc` files remained on my local machine (`.rpyc` files are ignored in `.gitignore`) and they are not deleted using **Force Recompile**. **Generate Translations** does not work, because it does not pay attention to the absence of source code in `.rpy` files, but looks at `.rpyc` and, accordingly, it does not generate anything since translations was generated earlier.

Here is what I see in my `tl` folder (example):
* `tl/en/some.rpyc`
* `tl/en/some.rpyc.bak`

I could use the command in the terminal:
```git
git clean -xdf
```
But this command is not safe, because if you forget to commit your changes, you can lose your changes (which happened to me).

I would like to be able to use the ren'py method to get rid of `.rpyc` files that do not have source code (at least for translations).
