### ISSUE TITLE
Tkinter error on change projects directory

### ISSUE THREAD

**Issue by ampheul** [renpy/renpy#2133]
I am getting the same error as #1678 in the latest release of RenPy (7.3.5) on fedora 31, only it happens any time I attempt to change the projects directory from preferences. It is not triggered by cancelling, it happens immediately.
```shell
Traceback (most recent call last):
  File "/home/thomas/Downloads/renpy-7.3.5-sdk/launcher/game/tkaskdir.py", line 31, in <module>
    from tkinter import Tk
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: /lib64/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas/Downloads/renpy-7.3.5-sdk/launcher/game/tkaskdir.py", line 34, in <module>
    from Tkinter import Tk
ModuleNotFoundError: No module named 'Tkinter'
```

**Comment by renpytom** [comment]
That's a totally different error, and probably because your system Python is incorrect. I'd suggest taking this up with Fedora. You should be able to run:

```
python /home/thomas/Downloads/renpy-7.3.5-sdk/launcher/game/tkaskdir.py /tmp
```

From the command line without Ren'Py. 

As a backup to get you goining, you can run:

./renpy.sh launcher set_projects_dir /path/to/my/projects/directory 

from the command line.

**Comment by ampheul** [comment]
Thanks, I was able to set the projects directory using the command.
