### ISSUE TITLE
renpy.loadable returns True for directories on PC, but not on Android

### ISSUE THREAD

**Issue by TropeCode** [renpy/renpy#2149]
`renpy.loadable` can be used to check the existence of assets folders by passing in a directory, however, this behaviour is inconsistent across platforms. Calling it with a directory path on PC returns True if the directory exists, but on Android it returns False even if the directory exists inside the APK.

The inconsistency arises because the function checks the APK archive's file info which only contains file paths.

I'm assuming that `renpy.loadable` wasn't intended for checking asset directories, but it's a useful behaviour.

**Comment by renpytom** [comment]
I've decided to resolve this by making renpy.loadable return False for a directory. 

I'd suggest that if you want to check that a directory is present, stick a sentinel file in it, like dlc/exists.txt, and then check ``renpy.loadable("dlc/exists.txt")``. The thinking here is that since a directory can't actually be loaded with renpy.file, it shouldn't return True.
