### ISSUE TITLE
_get_voice_info() did not return correct voice tag

### ISSUE THREAD

**Issue by fk1995** [renpy/renpy#2164]
Using project in this link: https://drive.google.com/file/d/1icHU-yZFthuCr5-HCCsEW9VeiR23f1L2/view?usp=sharing
Use renpy launcher to run this game and open in-game console with SHIFT+O.
_get_voice_info() will return an object, but its "tag" field is None, which should be "caocao" in this case.

**Comment by renpytom** [comment]
I don't believe that this is a bug. 

The thing that's happening here is that when you open the console, it ends the line of dialogue. Since the line of dialogue is no longer running, the voice tag stops being relevant, and hence it's None. If you were to use it in, say, a Character callback, it would work.
