### ISSUE TITLE
Request: Documentation Enhancement

### ISSUE THREAD

**Issue by founfabug** [renpy/renpy#2209]
Add to **Quick Start** and **Displayables** documentation
(1) A mention that some/all reserved words cannot be used as image attributes (ref. #2208)
(2) A link to a list of reserved words.
Thank you.

**Comment by Gouvernathor** [comment]
(1) seems obvious enough, since this is the case in every programming language I know (arguable).
(2) [reserved names](https://www.renpy.org/doc/html/reserved.html) is close enough, apart from that, trial and error for ast-reserved keywords should not be hard to avoid by trials and error - there aren't that many of them
