### ISSUE TITLE
Logging to a file using "with open()" but no file gets created?

### ISSUE THREAD

**Issue by newbiemate** [renpy/renpy#2214]
I want to write a file for my own logging purposes. I tried the following, but no log file is ever created.

```
init -1 python:
    def log(text):
        with open("test.txt", "a+") as f:
            f.write(text)

label start:
    python:
        log('hello, first line')
        log('another line')
        log('bye!')
```

What is being done wrong in the above? I know that renpy has its own logging through  `config.log`, but this only allows me to define a single log file to write to. Is there a way for renpy to define multiple log files, and have specific loggers write to their respective log file?

What I was hoping to achieve above was to define multiple log files to write to, just so I could organize the various outputs I have my own way. (ie, `log1()`, `log2()`, `log3()`).

---
**EDIT:** I also tried the following using `config.log`:

```
label start:   
    define config.log = 'testing.txt'

    $ renpy.log('one')
    $ renpy.log('two')
```

But `testing.txt` is also no where to be found in the game folder.

**Comment by kobaltcore** [comment]
Opening a file without a path will try to create it in the root of the filesystem. You can verify this in Ren'Py by executing `os.getcwd()` in the console, which will print the current working directory it assumes, which is `/`. Thus, setting either of these to `testing.txt` will make Ren'Py want to create this file in the root level, which either fails silently (thus the file never gets created) or it executes and you never found it because you were looking for it in the project folder.

To create a file in the project folder, you can use this:
```python
with open(os.path.join(config.logdir, "runtime.log"), "a+") as f:
    f.write("some stuff")
```
We use `config.logdir`, which is set to the root of the project folder by default and append the filename to get the proper path.

Also note that you're writing to the file without newlines, so all your text will end up being on one line, which is likely not the behavior you desire.

You can also use the [`logging` module](https://docs.python.org/2/library/logging.html) Python provides to get a bit of a nicer output and proper handling of log files, if you are so inclined:
```renpy
python early:
    import logging

    if not os.path.exists(config.logdir):
        os.makedirs(config.logdir)
    logger = logging.getLogger("custom-name")
    logger.setLevel(logging.DEBUG)
    formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
    try:
        # only initialise when in writeable directory
        file_handler = logging.FileHandler(os.path.join(config.logdir, "my_name.log"), mode="w")
        file_handler.setLevel(logging.DEBUG if config.developer else logging.INFO)
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)
    except:
        pass
```

Using this method you can then call things like this:
```renpy
$ logger.info("Some information")
$ logger.error("Some information")
```

**Comment by renpytom** [comment]
I think that @kobaltcore answered this, and that there is not really much else to say. So I'm closing this  issue.
