### ISSUE TITLE
config.missing_label_callback improvements

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#2261]
Can the callback allow returning a tuple to pass in parameters to the label when it jumps?

Also can the documentation for `config.missing_label_callback` be updated to indicate that it the callback may take in a parameter which is the label that was missing?  

e.g.

    def missing_label_callback(label):
        if is_event(label):
            return "missing_label"
        else:
            return None

    config.missing_label_callback = missing_label_callback

**Comment by renpytom** [comment]
I don't see how letting it return parameters would be useful, and because of the way it works, doing so would be difficult. The label missing_label_callback returns is given the same parameters that the original label would have been, and so we don't want to have two sets of parameters for the same label. I believe that the label that's reach should be able to set the parameters up appropriately and then call the appropriate label.

(Fundamentally, this is meant as a way of getting out of a horribly broken game, recovering to a safe state, and letting the player continue. I want to keep this as simple as possible.)

I'll update the documentation shortly to include the parameter in question.

**Comment by trajano** [comment]
OK it was more that we can tell the callback what label was attempted so we can display it.  The workaround for now is just to store it in a temporary variable and read it from there when in the jump script.
