### ISSUE TITLE
Live2D Support For Multiple Parameters

### ISSUE THREAD

**Issue by jbonesy** [renpy/renpy#2358]
Currently one parameter (expression) can be used for live2d models besides motions. Support for multiple parameters (especially custom parameters) would preferable, especially in terms of "paperdolling" sprites or modifying more assets than just expressions (i.e. clothing).

**Comment by benq66** [comment]
I support the request. Now, as it stands, applying expressions turns off the effect of the previous expression. Model resets to defaults + new expression. It would be very helpful to add parameter changes from the new expression to current state of the model. I.E. accumulate changes. And in order to reset the state of the model to the original, just add either a command or a "reset, default" expression. As a last resort, the creator of the model can create an expression "original, default" or something similar, where they will write all possible changes to the initial parameters.

**Comment by renpytom** [comment]
This was added. The idea is that there are exclusive (the default) and nonexclusive expressions. A nonexclusive expression lasts until the character is hidden, or the attribute is removed (show eileen -nonexclusive).
