### ISSUE TITLE
7.4 Bug: Layered Image lose its pose atrribute

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#2520]
https://lemmasoft.renai.us/forums/viewtopic.php?p=537497&sid=1e1227cd26a75fbefb88e46ce1edaf95#p537497
Probably related to my https://github.com/renpy/renpy/commit/f2470edaf4432a6f25314e1d1ae93c4509f4099b commit

**Comment by Gouvernathor** [comment]
I guessed maybe was when the attribute part of the layeredimage name is also an attribute name in another layeredimage having the same tag.
```
layeredimage eileen two:
    size (400, 400)
    xalign 1.0
    attribute ba default:
        Solid('#60c')
    attribute bb:
        Solid('#00f')

layeredimage eileen one:
    size (400, 400)
    xalign .0
    attribute aa default:
        Solid('#c60')
    attribute two:
        Solid('#f00')
```
`show eileen two` triggers the red square on the left, which means the "one" one with the "two" attribute. While this behavior is arguable, it doesn't trigger the reported error.
I'll do more tests with `side` now.

**Comment by Gouvernathor** [comment]
I've done some tests using this :
```
layeredimage eileen two:
    size (400, 400)
    xalign 1.0
    attribute ba default:
        Solid('#60c')
    attribute bb:
        Solid('#00f')
    attribute base:
        Solid('#0f0')

layeredimage eileen one:
    size (400, 400)
    xalign .0
    attribute aa default:
        Solid('#c60')
    attribute ab:
        Solid('#f00')
    attribute base:
        Solid('#0f0')
```
As reported, doing `show eileen two` then `show eileen base` triggers the error. However it can't be because of your commit, since the edited function, `get_side_image`, is not called.

**Comment by Gouvernathor** [comment]
I believe it to be caused by the new `ca is None` clause from 040ec21.
In my example, on the `show eileen base` call, it allows the tuple `('eileen', 'one', 'base')` from the "one" displayable to be entered in the list of matches, while it has only one required attribute and while the other one, `('eileen', 'two', 'base')`, has a required and an optional one.
So my idea of a solution is this : from the final list of matches, of which we need to keep only one, if there are several, we pop the ones with the least amount of optional attributes. If there's only one match left after that, that's our guy (and we avoid raising an exception). If there are several, well an exception was to be raised anyway.
I'll get to trials, but I can't really see where there would be an issue since it would only change the function's behavior when it's about to raise an exception.
