### ISSUE TITLE
[7.4.2+] Should rollforward be forbidden in call screen?

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2563]
The issue is with something like:

```renpy
screen test():
    vbox:
        textbutton "A" action [ SetVariable("result", "A"), Jump("done") ]
        textbutton "B" action [ SetVariable("result", "B"), Jump("done") ]

call screen test
```
The problem is that if a rollback and rollforward occurs, the jump will be re-done, but the SetVariable won't be, as the button itself isn't being clicked. So it might make sense to have rollforward be somethign that the user opts into, or that Ren'Py automatically manages by tracking if the actions run are simple enough.

**Comment by StudioErrilhl** [comment]
Wouldn't it make sense to make this behave kinda like choice menus, ie that a user interaction is demanded?

**Comment by renpytom** [comment]
Choice menus allow roll-forward, so this would be more restrictive than choice menus.

**Comment by jackmcbarn** [comment]
Would it be practical to make it so that the SetVariable would be re-done too on rollforward?

**Comment by renpytom** [comment]
I don't believe it would be practical to do so - what's more, it's easy to write an action that's equivalent to SetVariable. It's probably best to have a whitelisted set of actions (Jump and Return), and then not rollforward if it's something else.

**Comment by TheSchnappi** [comment]
It would really hurt me if I would loose the rollback feature completely with call screens because my game navigational structure is built and ancored around this feature.
So since I had the same problem with my ADV navigation system, I made a work around to prevent the rollback problem with simply passing the content in a `Return()` action and then execute the function I need with the parameter and jump to the label with `jump expression` outside of it based on the content of `_return`, instead of using it all in one place.

At the same time I still have to set (or better reset) a variable with the action that is modified by the screen during interaction (a different action) that is responsible for opening and closing a submenu inside the screen. So if RenPy would automaticly prevent me from rollback as soon as it sees a `SetVariable` action somewhere inside a call screen, that also would also break my rollback screen.

**Comment by renpytom** [comment]
There is 0 change of losing rollback. 

Roll-forward is a different feature, were you hit page down or scroll the mouse wheel forward.

**Comment by TheSchnappi** [comment]
Sorry I was very unclear there, I also meant Roll-Forward, exspecially in the second case.

**Comment by renpytom** [comment]
Sorry, but when you say that your game's navigational structure is anchored around rollback and rollforward, what do you mean?

**Comment by TheSchnappi** [comment]
It is not ancored around rollback and roll forward but around the call of this particular screen. If rollback and roll forward for calling screens break, the roll forward and rollback essentially break for all of the game and not just for one single scene.

I have an old style japanese ADV game system with a menu that contains verbs as text buttons like "Look", "Think", "Move", etc. to interact with the objects of the current room.
You click on a verb, for example "look", that use an action with SetVariable() that result in the display of a sub menu inside the screen that contains all interactions for the verb "look" as text buttons - for example "room", "table" or "chair".
Interacting with one of these buttons then set two variables (one to close the expanded menu so the screen won't show the verb expanded the next time it is called and one variable to keep track of the count of interactions with this object) and jump to a given label that then contains the game objects logic that often loop back to the label with the call screen statement.

**Comment by jackmcbarn** [comment]
Could you set your variable in the label that you jump to, instead of as a separate action before jumping?

**Comment by TheSchnappi** [comment]
Like I said before, that is what I basically do to make rollback and roll forward work.
The only `SetVariable()` that stayed in the action is a variable that is only needed for the screen itself to work. So there is no problem that rollback and roll forward will "reset" the variable, because it is what I do anyway in that case.

A dumb down version of the screen code with the button that is used to jump to the new label:
```py
screen adv_menu():
    frame:
        [...]
        for verb_id in adv_mode.verb_order:
            [...]
            button:
                # This is the button I was talking about when I said set and reset
                action SetVariable('adv_mode.verb_actions_visible', verb_id)
            if adv_mode.verb_actions_visible == verb_id:
            textbutton tmp_action_text:
                # This is the modified button I was talking about
                action [SetVariable('adv_mode.verb_actions_visible', None), Return(verb_action[1])]
            [...]
```

And the jump and set code that makes roll forward of the screen work:
```
label room:
    [...]
    call screen adv_menu
    # The last two code lines once where inside the textbutton
    $ increase_choice_repeat(_return)
    jump expression _return
```

And yes, the `SetVariable('adv_mode.verb_actions_visible', None)` could also be be just bleed out of the screen or maybe I could refactor the code so that it would use `SetScreenVariable()` instead (a little bit tricky because I use the `use` but with passing variables I think I could also make it work)

Anyway, the point I try to communicate is:
1. I already have done work to make roll forward and rollback work correctly on my end. So to simply disable roll forward for all call screen statements is a bad idea.
2. The idea to automatically enable or disable roll forward for a call screen based on whitelisted actions is better but could still hurt me (even if I "only" have to modify the screen). Also there will be corner cases where **only** whitelisting the two actions Jump and Return will still be problematic (like in my case). At the very least the whitelist has to be expanded with more then just these two actions and each action has to be reviewed if roll forward would break it. For example all `*ScreenVariable()` should also be whitelisted but I think there will be other action that also have no problem to be whitelisted.
3. Therefore I was trying to make a case for having an option to "opt in" from inside the screen to have roll forward because I think a whitelist option alone will be to fragile.
