### ISSUE TITLE
can't start 7.4.0

### ISSUE THREAD

**Issue by AnnaRosh** [renpy/renpy#2584]
good day!
first I want to say thank you very much. I really like your product.
there was a problem with the upgrade to 7.4.0. the launcher does not start. gives an error message. I attach screenshot. 
At the same time, 7.3.5 works fine.
Can you please tell me what's going wrong?
Thank you!)

[log.txt](https://github.com/renpy/renpy/files/5786707/log.txt)

![skrin](https://user-images.githubusercontent.com/72790385/104006424-2661c380-51af-11eb-93a1-e59db4d399c6.JPG)

**Comment by renpytom** [comment]
I'm unable to read this. 

But I'd like to know if a log.txt file was generated before the crash. I'll also ask you to hold down the left-shift key as Ren'Py starts, to see if you can get the graphics menu.

**Comment by AnnaRosh** [comment]
thanks for the answer.

the first time the log file appeared when starting the program. and it is updated with every launch.

yes, the left-shift key works. a window appears.

before writing to you, I tried to find a solution in Google by the error code, and followed all the advices - disabling the antivirus. defender and running Windows in safe mode, but the result is always the same...

**Comment by Andykl** [comment]
I have a player with simmilar problem. He says that the game is just a white screen and then the program terminates.
His PC is DELL OptiPlex 380 with Intel G41 Express.
Logfile of starting my game (gl2) - [log IW.txt](https://github.com/renpy/renpy/files/5791201/log.IW.txt)
Logfile of empty project (gl1) - [log test 7.4.txt](https://github.com/renpy/renpy/files/5791202/log.test.7.4.txt)
@renpytom Is there anything we can do because it looks like obsolete and unadvanced GPU cases?

**Comment by DiabetusSpell** [comment]
I have the same error. I went to test the 7.4.1 prerelease and it works just fine...
I decided to stay on 7.3.5

**Comment by renpytom** [comment]
Hopefully this is fixed for everyone by 7.4.5. It probably makes sense to open a new issue if it's not working in the 7.4.5 prereleases.
