### ISSUE TITLE
[7.4.2] Displayable disappears for a short time when using certain ATL transforms

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#2648]
So I just encountered this recently and I don't know if this is a bug or just a bad use case.

Consider the following:

```
show eileen:
   xanchor 0.5 xpos 100
e "Hello!"
show eileen:
   linear 1.0 xalign 0.5
```

In this case the eileen displayable will not move to the new position, but instead disappear and then reappear at the new position. The reason for that is that the linear transform uses xalign for positioning, but the original image wasn't set to be xaligned.

What I expected:
Since xalign just means setting xanchor and xpos to the same value the linear ATL transform should try to move the xanchor and xpos values closer together withing 1 sec until they are the same (0.5) - since xanchor is already 0.5 of the displayable, xpos should just increase (depending on game resolution).

This also happens with yalign and yanchor, ypos

**Comment by AndriWilford** [comment]
when the interpretation of positional parameters that can be float/int swaps type, the previous type is interpreted as the new type.

In the example above,  `xpos 100` move the anchor point to 100 pixels from the left edge of the parent. The next show, the xalign assigns xpos the value of  0.5, which is now a float and interpreted as a proportional distance.

For the interpolation that then takes place, the beginning position is interpreted to be  100.0,  or 100 times the width of the parent,  likely not the original position of  "100 pixels from the left".  The object appears to "disappear" because the interpolation moves very quickly since the distance is very large.

Either this is 'intended' behavior, or the positional parameters that can have different interpretations  will need to be able to interpret the value of a previous state of another type as the new type  (+100 px  -->  (100.0 / screenwidth) ).

**Comment by m-from-space** [comment]
Thanks AndriWilford. It's clear that the image does not disappear but just jumps from a high distance I guess.

This still seems not reasonable in my opinion on the other hand.
Ren'py sould not just change the original position and suddenly think it's a 100.0x image width distance from the anchor point when it knew that the current position is a 100px distance.

When I declare make xpos and xanchor the same over 1.0 seconds (linear 1.0 xalign 0.5) I don't want it to mess around with the current position, but just read it and then interpolate it to the new value.

**Comment by renpytom** [comment]
This is the intended behavior, as Ren'Py's one-pass rendering algorithm doesn't have a way to easily convert between relative and absolute coordinates.
