### ISSUE TITLE
nvl_list behaviour strange with multiple languages

### ISSUE THREAD

**Issue by npckc** [renpy/renpy#2669]
If using multiple lists for different nvl screens, the nvl_list does not seem to save the very first dialogue after the game starts to nvl_list when using a language other than the default (None). You can see the behaviour by playing through this game using the Default language and then playing using the Test language.

[testnvl_list.zip](https://github.com/renpy/renpy/files/5988868/testnvl_list.zip)

**Comment by renpytom** [comment]
For various reasons, the nvl-mode code replaces nvl_list on a regular basis, breaking the aliasing you're trying to do here. I don't know why it's only happening in the one language, but there are cases where it can happen in the default language, also. 

What I'd suggest is to copy the lists, rather than trying to alias them. 

```
python:
    nvl_list_e[:] = nvl_list
    nvl_list[:] = nvl_list_f
```

And vice-versa seem likely to work better.

**Comment by npckc** [comment]
Thanks for the reply. If it's intended behaviour I'll close this issue.
