### ISSUE TITLE
Character() constructor seemingly confusing name and kind

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2682]
```rpy
define sar = Character(_('Sardaukar'))
define hyr = Character((lambda : _("Hyrulan") if believe_hyrulan else _("Sardaukar Soldier")), dynamic=True)
default believe_hyrulan = false

label start:
    sar "hello" # works as intended
    hyr "hello" # wai
    Character(sar) "hello" # wai
    Character(hyr) "hello" # fails because "eval() takes a string or code object"
    Character(kind=hyr) "hello" # wai
```

**Comment by AndriWilford** [comment]
I don't think it is "confusing name and kind".
The string type conversion of the class does not evaluate a function.  "Character(hyr)" attempts to convert the object 'hyr' to string, so crashes, since there is no calling of the function. Strictly speaking   "Character(hyr.name())("Hello")" works, since it is 'calling' hyr's name instead of string conversion..

I think string conversion can just have function evaluation as in pull request #2683

**Comment by Gouvernathor** [comment]
Sure, but the system shouldn't try to evaluate `hyr` as a string, if `sar` is not. Whatever the specified behavior is, that's a discrepancy.

Furthermore, I removed it from my example but in my original code both `sar` and `hyr` have other custom settings other than its name, and they are carried along when calling `Character(sar)` or `Character(kind=sar)`, and they wouldn't if I called `Character(sar.name)`.

**Comment by AndriWilford** [comment]
The behavior on line 8 and 9 is the same. They are both type-cast to string for the parameter to the Character constructor. It's just that it works for  8, since it successfully evaluates to a string, while line 9's does not.

Can you give an example of code where custom settings are carrying over for line 9 and 8? The lines 9 and 8 and 10 create new character objects that are used once and discarded (the character object is not saved to any variable). Line 10 should work to bring over custom settings, from the use of the  "kind"  parameter,  however lines 8 and 9 should not... they are just creating new character objects,  with the string created from evaluating 'sar' and 'hur',  but with no parameters.

**Comment by Gouvernathor** [comment]
Indeed. I re-tried it and it turns out I had completely misunderstood how the constructor works.
I thought if you only give a Character instance as a name and no `kind` argument, the Character argument would be interpreted as a `kind`.
I believe that behavior would be more handy, but it would probably cause incompatible changes.

**Comment by renpytom** [comment]
I don't think there's a bug here.
