### ISSUE TITLE
`unhovered` not called anymore when opening modal

### ISSUE THREAD

**Issue by 0x52h52** [renpy/renpy#2743]
This commit 3ee379438ea51a5e0cf7eac2c441e981f8aa3ea8 prevents `unhovered` from being called when a modal is opened.

Before the change (how I would expect it to work):
![RP_working](https://user-images.githubusercontent.com/60195129/112882379-2ea20e80-90cd-11eb-92d0-6ba07cbd7d42.gif)

After the change (stays "hovered" until we hover it again):
![RP_failing](https://user-images.githubusercontent.com/60195129/112882416-3b266700-90cd-11eb-955c-d2d3cbfaf5b8.gif)

The button moving from left to right is a transformation.
The `True/False` is controlled by the button's `hovered` and `unhovered`

This is the code I used to test:
```python
transform hover_effect:
    on hover:
        linear .5 xoffset 10
    on idle:
        linear .5 xoffset 0

screen first_screen:
    default is_hovered = False

    vbox:
        align (.5,.0)
        textbutton 'Test' hovered SetLocalVariable('is_hovered', True) unhovered SetLocalVariable('is_hovered', False) action Show('second_screen') at hover_effect
        text 'Hovered: [is_hovered]'

screen second_screen:
    modal True

    frame:
        xysize (200,200)
        align (.5,.2)

        textbutton 'Close this' action Hide('second_screen')

label hover_demo:
    show screen first_screen
    "0x52" "The test button at the top has an hover effect.\nClick it to open another screen, which stops the hover effect"
```

**Comment by AndriWilford** [comment]
This is related to another problem I was helping someone with previously. If a screen is shown,  and the mouse is already  "on top of"  a button with a "hover" action (and/or image), then that hover event does not fire until the mouse is moved. This was overcome in this instance by hacking in an event, something like the following:
`init python:
    from pygame_sdl2 import event as pygameevent
    from pygame_sdl2 import MOUSEMOTION as pygameeventMM

    def screenmouseevent():
        pygameevent.post(pygameevent.Event(pygameeventMM))
        return None`
.. and then in screen ..
`on "show" action Function(screenmouseevent, _update_screens=False)`

The problem in this issue is a corollary, but also in 'reverse'. When a screen is shown, events like hover and unhover are not fired until the mouse moves,  HOWEVER, the  "unhover" event also only fires when the mouse actually crosses out of the hover area, which will not happen until the it is hovered first.

The change, in commit linked above, changed the behavior, since the unhover event is no longer passed to the screen below the modal screen.. in a sense, this is  "correct".  The previous behavior (where events still reached below a modal screen) was arguably wrong... you'll note that "unhover" would be passed to the screen below the modal one,  even while the button actually still has the mouse cursor on it.. this is because the modal screen was "covering up" the button, so it no longer had focus, but events would still reach the screen under the modal screen (which is also technically incorrect).
IOW,  the current behavior is "technically more correct",  but it is unexpected in that the "unhover" event that would be anticipated to occur on the button under the modal screen never is fired..

I don't see a straight-forward solution to this..  It could be the case that every time a screen is shown,  or comes to the top of the z-order,  that the hover/unhover state of all buttons are checked and those events fired,  but this can also be unexpected behavior, since the buttons are not really being  "unhovered". However,  NOT checking the state can also produce some unexpected results as above..
   Would another event like  "default_hover_action" or some such be warranted? Like, this could be fired on-show   or  when the screen becomes the top of the z-order,  THEN  the 'hover' state is checked on all buttons, then proceed..

**Comment by Lezalith** [comment]
Could be solved by simply calling a single event when the screen is done being shown.

Would that cause side effects or would that be an okay solution?

**Comment by AndriWilford** [comment]
This came up in another setup for me, as well. It was a visual 'glitch', so no game-breaking. A quick (dirty) solution was something like:
```
    def unfocuswidget(screenname, widgetname):
       sc = renpy.display.screen.get_screen(screenname)
       wid = renpy.display.screen.get_screen(screenname).widgets[widgetname]
       if hasattr(wid, "unfocus"):
          wid.unfocus()
```

 .. then in the screen, something like the following. Using the main-menu action for the example, since it puts up a modal confirmation screen which can cause this problem.
 
 ```
 id "mainmenubutton"
action [ MainMenu(), Function(unfocuswidget, renpy.current_screen().screen_name[0], "mainmenubutton") ]
selected MainMenu().get_selected()
sensitive MainMenu().get_sensitive()
```

Probably want to have "is None" checks and such in function.

Basicallty, it seems that widgets that were being interacted with, which may  *cause*  a modal object that intercepts events to the interacted widget,  may require a specific handling in some form, like one interact of still receiving events. This still does not seem like a simple problem to solve to me.
