### ISSUE TITLE
Triple quoted strings and newline preservation

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#2756]
I have discovered odd behaviour with v7.4.4 with regards to triple-quoted strings and newlines. Here is some sample code to demonstrate:
```renpy
init python:
    import re as regex
    def string_test(s):
        return regex.sub("\n", '\nNEWLINE', s)

define example_1 = """This is a test.
        Despite the indentation, the newlines should be identified.
        However, in v7.4.4, only some of the newlines are preserved.

        I haven't been able to determine the exact cause, however, having
        an even number of apostrophes in the string seems to cause it to miss
        newlines in some way.

        Here is a second apostrophe ' to make it format poorly.

        This is another test line which should be on a newline.

        The end."""
```
This performs as expected in 7.3.5, with each newline properly prefixed with `NEWLINE`. However, in 7.4.4, apostrophes cause newlines to be completely missed, resulting in the following: 
```
This is a test.
NEWLINE        Despite the indentation, the newlines should be identified.
NEWLINE        However, in v7.4.4, only some of the newlines are preserved.
NEWLINE
NEWLINE        I haven't been able to determine the exact cause, however, having
NEWLINE        an even number of apostrophes in the string seems to cause it to miss
NEWLINE        newlines in some way.
NEWLINE
NEWLINE        Here is a second apostrophe ' to make it format poorly.        This is another test line which should be on a newline.        The end.
``` 
Notably, the newlines after the second apostrophe are entirely lost. I have only observed this behaviour occurring when there are apostrophes or quotes (`"`) in the string, regardless of whether triple quoted `'''` or `"""` are used.

**Comment by AndriWilford** [comment]
It looks like this is a problem from renpy/python.py
https://github.com/renpy/renpy/blob/639d5d9ce107004662b9ac9bc546d8bcc31b2e98/renpy/python.py#L693-L696

If there's a  " ' " in the triple-quote string, then this block will be reached. While 'string' is set to   """   , it will 'fail' that first check (since len(string) == 3,  but the next 2 chars are not also 'c' ) and then set 'delim'  and 'string'   to  " ' ".

Not sure exactly what the intent of this parsing is in the wider context, so I'll leave it up to Tom to fix  >.>
