### ISSUE TITLE
The default of "nearest" change from None to 1.0 in 2b34259

### ISSUE THREAD

**Issue by Astrum-polaris** [renpy/renpy#2770]
https://github.com/renpy/renpy/blob/20a29b804745086f43c592dca8282c5637c75517/renpy/display/transform.py#L97
https://github.com/renpy/renpy/blob/2b34259319d1001410aea2192449935b192d4adb/renpy/display/transform.py#L959

Might related to https://github.com/renpy/renpy/issues/2764

**Comment by Andykl** [comment]
Good catch. I don't close this because I don't see config.nearest_neighbour being handled in the Transform render code. 
And I'm not sure that with `config.nearest_neighbor = True` Ren'Py will turn it off if `Transform.nearest = False`, because of https://github.com/renpy/renpy/blob/master/renpy/gl2/gl2draw.pyx#L1304-L1305

**Comment by renpytom** [comment]
Thank you for this catch, and thanks to @Andykl for integrating the fix. 

Transform.nearest = False isn't meant to turn it off, as once it's asked for it should apply to all children.
