### ISSUE TITLE
Automatic nvl-clear when block goes off the window

### ISSUE THREAD

**Issue by soryy708** [renpy/renpy#283]
RenPy currently has automatic line breaking. When a line's width is too  long to fit in the window, it's automatically broken into multiple lines  displayed one below the other.
I propose a similar system that would make sure blocks don't bleed off  the bottom of the screen the way they currently do. It's very  frustrating (and at times difficult to notice) when a line (or even  worse, a single word) is never displayed because RenPy renders it  outside of the window.
Having RenPy catch that and do an nvl-clear before the overflowing block  would be very convenient. Even if it is not desired behaviour, it will  at least be obvious that there's an overflow and then the writer will  fix it by doing an explicit nvl-clear where he wants it.

---

An alternative way to address this issue would be scrolling rather than  doing an nvl-clear. This will help the reading flow more naturally. I  personally find animated scrolling more appealing, but: On the one hand,  non-animated scrolling is easier to implement and is less annoying for  the reader on slow scrolling speeds, but on the other hand,  animated-scrolling feels more "polished", doesn't bother the user on  fast scrolling speeds, and in fact helps the reader keep track of where  he is in the text.

**Comment by renpytom** [comment]
This has been implemented for a few Ren'Py releases.

**Comment by hsandt** [comment]
It seems auto-scroll has been implemented for fixed size nvl_height, however, the main feature request, automatic `nvl clear` when block goes off the window, has not been (for both fixed and dynamic nvl_height).

This should be doable for fixed nvl_height since we already know when we need to auto-scroll, so we could just nvl clear instead when we need to scroll by at least 1px, before showing the next block.

For dynamic nvl_height (i.e. `gui.nvl_height = None`) we don't have proper auto-scrolling so I imagine we are not able to detect when text reaches the bottom at the moment (although it should be a matter of summing height?).

Ultimately it would be nice to have both though. Shall we reopen this issue or should I open a new one? (but I won't be able to describe it much better than the OP so it will look almost the same, without the alternatives).

**Comment by shawna-p** [comment]
Have you tried a viewport with `yinitial 1.0` like the history screen? It doesn't have to be scrollable.

**Comment by hsandt** [comment]
Indeed, that works! And I actually had a draft with some code that worked pretty well, but apparently I had some issues with scrolling and gave up. When I tried again, everything looked fine, there was only scrolling input conflicting with advance/back input but I can disable that.

Unfortunately I couldn't go as far as enabling smooth scrolling as suggested by the OP in the last paragraph... I tried an ATL with `linear [duration] yoffset 1.0` but for some reason `yoffset` doesn't behave like `yinitial` (it moves by a fixed amount of pixels even when passing a fraction apparently). That may need a longer discussion though so I opened a Lemmasoft thread to discuss this: https://lemmasoft.renai.us/forums/viewtopic.php?t=67577

I also put the code I used for instant auto-scrolling to bottom in that thread, so people who just need this can check it out.
