### ISSUE TITLE
Selecting Options on Quick Menu shows wrong background in latest Ren'Py

### ISSUE THREAD

**Issue by Stormsinger-Frostclaw** [renpy/renpy#2830]
Before updating from Ren'Py 7.3.5, selecting Options/Preferences from the Quick Menu loaded the correct background.

![screenshot0018](https://user-images.githubusercontent.com/54681480/119848559-4112ba00-bf4f-11eb-8c51-ea2ffbcd80ff.png)

However, since updating to the latest version of Ren'Py, when selecting the Options/Preferences from the main menu, it shows as normal. When selecting from the Quick Menu though, it produces this:

![screenshot0019](https://user-images.githubusercontent.com/54681480/119850081-8c799800-bf50-11eb-84ec-7a2b913613ab.png)

This background is the one used for my save/load data, although it's not loading the main background it normally would.

Project file has been provided.

**Comment by renpytom** [comment]
So, tracked this down to you setting gui.game_menu_background inside screens in screens.rpy, using statements like:

```        
$ gui.game_menu_background = "gui/menu/prefBG.png"
```

This isn't allowed for two reasons. 

1) Python in a screen isn't allowed to have a side effect, as the screen (including any Python inside it) can be run multiple times so Ren'Py can predict screen statements and images. 
2) You're not allowed to change gui.game_menu_background after the game starts. That's because it's set in gui.rpy using the ``define`` statement, which tells Ren'Py that the variable can't change. Ren'Py uses this in optimizations. 

What you probably want to do is what you're already doing in screen load and screen save, where you put the backgrounds you need into the screens themselves. That would let you get rid of the need to change gui.game_menu_background. 

I don't believe this is a bug in Ren'Py. While there was a behavior change, it was behavior that was undefined twice over, and the new behavior is the result of better optimizations to screens.

**Comment by Stormsinger-Frostclaw** [comment]
Oh wow, that fixed it. I can't believe it was something so simple.

Thank you so much for your assistance. You're absolutely amazing. :)
