### ISSUE TITLE
[7.4.6] Transform: on show non-functional

### ISSUE THREAD

**Issue by hasnogame** [renpy/renpy#2860]
Recently updated from an older version of Ren'Py to a newer build and found that `on show:` transform blocks were no longer functional.

To recreate the issue, create a new project and add this code:

```python
define e = Character("Eileen")

transform basicfade:
    on show:
        alpha 0.0
        linear 1.0 alpha 1.0
    on hide:
        linear 1.0 alpha 0.0

label start:

    scene bg room

    show eileen happy at basicfade
```

This code results in a failure to display eileen, as seen here:

![Image of failed code](https://i.ibb.co/Dkt9100/image.png)

If I run the exact same project in **7.4.5**, the code works fine.

![Image of successful code](https://i.ibb.co/gz1xNWj/renpy7-4-5no-Bug.gif)

Footnotes:
- The issue is still present when using a fresh install of the 7.4.6 SDK
- "on hide:" functions properly, completing the transform as expected (e.g. fading the character out using the above code)
- This issue affects character and image displayables

**Comment by AndriWilford** [comment]
This appears to be a result of
https://github.com/renpy/renpy/commit/db30a5a590e761ab6098d418313a3df107090730


There's alot of context I don't understand, but perhaps the following word work, or may give an idea.. 
1) Revert the above commit

2) At:

https://github.com/renpy/renpy/blob/db30a5a590e761ab6098d418313a3df107090730/renpy/display/transform.py#L886-L892

Change to:

```
    if not (self.at == 0 and self.transform_event == "replace" and self.atl.animation):
        fr = self.execute(self, self.st, self.at)

        # Order a redraw, if necessary.
        if fr is not None:
            renpy.display.render.redraw(self, fr)

    self.active = True
```

The idea is that, if the atl block is an 'animation' block (so timebase will be at), and if the action is a 'replace' and the "at" timebase is currently 0, then this is a 'replace' of an already-showing displayable with an "animation" atl block showing. The initial execute is just skipped, and the update is called later, after the old transform data has been copied into the new one..

This does have a possibly unintuitive side-effect:
   If one creates two different "animation" atl blocks, then "shows" them consecutively on a displayable with the same tags, then the second showing will continue at the same  "at"  time, even though the transform is a different transform.
   It seems that this was kinda intended already, since the original example this was fixing showed a displayable without a transform applied, then later showed the displayable with an "animation" transform, that then continued at the "at" time the first "show" had accrued...

**Comment by renpytom** [comment]
I believe this is fixed in the nightlies.
