### ISSUE TITLE
config.key_repeat's lack of functionality is not documented.

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#2899]
in renpy/display/core, pygame.key.set_repeat() is called when config.key_repeat is not None.

https://github.com/renpy/renpy/blob/04dbdd8f3011c067a1bf7b0fb321222b53d6e720/renpy/display/core.py#L2247

However in pygame_sdl2, key.set_repeat() and key.get_repeat() do nothing, apparently by design.

https://github.com/renpy/pygame_sdl2/blob/364d3bcfa005b0eaf897d38b336a97fa6e05e76b/src/pygame_sdl2/key.pyx#L77

This is not reflected in the documentation for config.key_repeat or listed under incompatible changes.

https://www.renpy.org/doc/html/config.html#var-config.key_repeat

Should the documentation for config.key_repeat be updated to warn users about deprecated functionality? (In this case, it would be fantastic if the linter warned users when this variable is used.) Or is there another mechanism for controlling key repeat that should be implemented?

**Comment by renpytom** [comment]
I've removed this entirely. It's not implemented in SDL2, and so there's no way to control the key repeat rate. (And since it's a system-global setting, that's probably a reasonable decision - I don't think it makes sense for a game running in the background to override key repeat in a word processor.)
