### ISSUE TITLE
Problem when rendering transparent image behind another with Model Base Rendering

### ISSUE THREAD

**Issue by lise-henry** [renpy/renpy#2947]
Hello,

(I hope I’m posting in the right place and I’m not missing something, sorry if I do anything wrong!)

I have issues when trying to render an image behind another one using zpos and gl_depth. The back image indeed appears behind the front one but it is not displayed entirely: where the front image is transparent (and the background image should appear), the background image is not rendered, as if the front image was opaque. Cf screenshot: 
![screenshot_renpy](https://user-images.githubusercontent.com/1961791/127658608-8ec57bc6-a1ff-44b2-8c9e-2f4fa568d48c.PNG)

Here is the code I used for this example:

````python
define config.gl2 = True

image a = Placeholder("boy")
image b = Placeholder("girl")

label start:

    camera:
        perspective True
        gl_depth True
      
    show a:
        zpos 2
        xalign 0.8
        yalign 1.0

    show b:
        zpos 1
        xalign 0.9
        yalign 1.0

    pause

    return
````

**Comment by renpytom** [comment]
This isn't really a bug, just some of the weirdness that comes with the OpenGL depth pipeline, which isn't really set up for images with transparency, like these sprites.

What's happening is that a is being drawn first. It's both writing a pixel into the framebuffer, and depth into the depth buffer, with some of the pixels it's writing being transparent, but all having a depth to them. When b is drawn, the depth is 'further away' than the already written pixels, the depth test is failing, and the second pixels isn't being drawn. 

There isn't really a good solution for this, since take the transparent pixels on  the edges of a - those need to be composited correctly as well. At least for now, gl_depth is really only suitable for opaque images.

**Comment by lise-henry** [comment]
Fair enough, and thanks for the quick answer!

It might be good to update the page at https://www.renpy.org/doc/html/3dstage.html in the "Depth" passage, maybe along the line of "Unfortunately, this solution currently only works for opaque images. If you use images with transparency, you should use the traditional ’behind’ and ’zorder’ properties" ?

**Comment by renpytom** [comment]
Makes sense. Let me leave this open until I get to that.
