### ISSUE TITLE
Shaders in transforms, texture_wrap does not apply

### ISSUE THREAD

**Issue by AndriWilford** [renpy/renpy#3024]
It seems that the gl_ property  "gl_texture_wrap" does not apply to transforms when created.

There are three observations I have, actually... I can split these up to different issues if desired

1) Unless Model()  is used to create a displayable, the transforms do not seem to use the model renderer (the class in display/model.py). Is this intended?
```
image testers:
    mesh True
    "myimage"
    shader [ 'renpy.texture' ]
```
 .. does not end up using the Model class, but the following does ..
 ```
image testers:
    Model().child("myimage")
    shader [ 'renpy.texture' ]
```

2) When "mesh True" is specified in a transform that DOES use the Model class (the second example in 1) ) it ends up not seeming to work. 
```
image testers:
    mesh True
    Model().child("myimage")
    shader [ 'renpy.texture' ]
```
   .. will produce nothing on the screen when this is shown
   
   
3) The texture_wrap property does not seem to apply.
The following is something of a copy of the "renpy.texture" shader, with an offset
```
    renpy.register_shader("custom.test", variables="""
        uniform sampler2D tex0;
        varying vec2 v_uv;
        attribute vec2 a_tex_coord;
        attribute vec4 a_position;
    """, vertex_900="""
        v_uv = a_tex_coord;
    """, fragment_900="""
        gl_FragColor = texture2D(tex0, vec2(v_uv.x, v_uv.y+0.4));
    """)
```

 .. and is shown as follows ...
 ```
 init python:
    from renpy.uguu import GL_CLAMP_TO_EDGE, GL_MIRRORED_REPEAT, GL_REPEAT
image testers:
    gl_texture_wrap (GL_REPEAT,GL_REPEAT)
    Model().child("myimage")
    shader [ 'custom.test' ]
label start:
    "Starting out"
    show testers
    "end"
```
 ... which will produce a render on the screen with CLAMP'd texture access

**Comment by mal** [comment]
Pinch of salt because this is only to the best of my understanding, but here goes:

1. I think this is expected; using the `Model` displayable is not the same as using `mesh` in a Transform; they support different use cases. A `Model` is a displayable you create and control, while a transform with `mesh True` could wrap many other displayables some, all, or none of which could be a `Model`.

2. This is also expected, I believe. Using `mesh True` in a transform results in the child being rendered before being passed downstream to the transform's own rendering pipeline. This is useful to "flatten" some displayables before manipulation (their opacity for example, the aim is to change the opacity of the displayable as a whole, not each individual texture with in it separately as they'd then bleed through one another). In this instance however, it's asking a `Model` to render itself, but you've not told the `Model` which shader to use to render itself, so the end result is an empty render.
```diff
 image testers:
     mesh True
-    Model().child("myimage")
+    Model().child("myimage").shader('renpy.texture')
     shader [ 'renpy.texture' ]
```
Note that this is redundant as you'd be using the GPU to render twice, first the `Model`, then the outer transform for no reason.

3. This is definitely the weird one of the bunch. Firstly, the intended way to achieve what you're aiming to do there with a `Model` alone would seem to be:
```
image testers = Model().child('myimage').shader('custom.test').property('gl_texture_wrap', (GL_REPEAT, GL_REPEAT))
```
However it would require the fix in #3025 first, as it's not currently possible to set a GL property on a model due the bug being addressed there.

The second and more interesting part is that `gl_texture_wrap` appears to be ignored on the transform even when simplifying the use case thus:
```rpy
image girl wrap:
    'myimage'
    gl_texture_wrap (GL_REPEAT, GL_REPEAT)
    shader ['custom.test']
```
Which is unfortunately where my understanding taps out. 😦

**Comment by renpytom** [comment]
1. This is correct. Model is basically a factory that's used to make GL2Models inside Ren'Py, so that I can isolate the internal details fro the rest of the game. 

2. Model() and mesh True don't make sense together. @mal's explanation is the right one. I've updated the documentation to mention Model and mesh are incompatible.

3. gl_texture_wrap and similar only make sense when a texture is being created, with mesh True or with Model(), with the latter being the intended use case. I've reorganized the documentation to make this clear.

**Comment by AndriWilford** [comment]
Ok, thanks for your time and explanations! This is very helpful (again).

I find that,  for  **3)** , the following still does not result in repeating textures when rendered, using the shader declared above.
```
image testers:
        mesh True
        gl_texture_wrap (GL_REPEAT,GL_REPEAT)
        "arrow"
        shader "custom.test"
```

Should this be repeating the texture when rendered?

**Comment by renpytom** [comment]
0a5e763ebc9a5e7635c4bba106dcd8145bb1c865 seems to fix this entirely. 

As a side note, I'd suggest with a mesh, using:

```
shader [ "custom.test", "-renpy.texture" ]
```

To remove the standard renpy.texture shader from the mesh.

**Comment by AndriWilford** [comment]
It seems to work at this point.
I attempted a few transforms with various altering properties (crop, rotate, zoom) and the results appear to be 'correct'.

I don't have any other points, so am closing this issue as resolved, thanks both your help and patience.
