### ISSUE TITLE
Behaviour for imagebuttons with atl images has changed from 7.4.6 to 7.4.7

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#3040]
In 7.4.6, the following screen results in `image a_h` always being at the last image frame. The idle and hover images both move at the same time, even if only the idle image is visible.

in 7.4.7+, the following screen results in `image_a_h` not playing until the button is hovered. The hover image is not triggered until the image is actually hovered.

```
label start:

    call screen zoom_button

    return


image a:
    "a.png"
    linear 0.2 zoom 2.0
    
    "b.png"
    zoom 1.0
    

image a_h:
    "a_hover.png"
    linear 0.2 zoom 2.0
    
    "b_hover.png"
    zoom 1.0
    
    
screen zoom_button():
    textbutton "Restart Animation" action TestAction

    imagebutton:
        idle "a"
        hover "a_h"
        xalign 0.2
        yalign 0.2
        action NullAction()
        
init python:
    def TestAction():
        Hide("zoom_button")()
        Show("zoom_button")()
```

**Comment by jsfehler** [comment]
@Gouvernathor Using the animation timebase works, thanks. You're probably right that idle/hover images for an imagebutton sharing the same timebase no matter what was unintended.

This seems like the sort of thing that's worth a mild warning in the changelog. It's either a bug fix or a bug, depending on your perspective.

**Comment by ZusYar** [comment]
Let me bump this issue.
Seriously, 7.4.7 has changed buttons' behaviour in a bed way (IMO)

Example: i have an image with a set of tiles that represent a button's states: idle, hover, active, etc

I could simply program the buttons with a transform like

transform tile (x, y, w, h):
    'tiles.webp'
    crop (x * w, y * h, w, h)

        imagebutton:
            idle tile (0, 0, 100, 20)
            hover tile (200, 80, 100, 20)
            insensitive tile (100, 180, 100, 20)
            action NullAction()

It worked perfectly and I could change tiles programmatically on key pressed and all
Well,  not now. Buttons won't get idle state ever again after you unhover them

    button:
        add tiles at some_cropping_transform()

doesn't work either, because whenever the button is insensitive it doesn't get transformed at all.
I'm not sure how i'm supposed to create such buttons anymore.
This is very frustrating, and it's practically impossible (tedious) to migrate a ready project to newer renpy.

**Comment by renpytom** [comment]
This was cleaned up in a recent change, so I'm documenting this in the 7.5 changelog.
