### ISSUE TITLE
Issue with text speed resetting during autoreload & reopening renpy when adding preferences.text_cps

### ISSUE THREAD

**Issue by thugzillaDev** [renpy/renpy#3047]
Hello, I'm using Ren'py 7.4.8, and I found out that my text speed, no matter what I set it as, resets whenever I autoreload or reopen the game. This has not happened in previous versions. This still occurs when persistents are deleted.

https://user-images.githubusercontent.com/57463682/133952002-74f2a7b4-4395-432a-8cf6-29cd15c2f0b2.mp4

This is happening to all my games, and easy to reproduce in a test game.

add ```default preferences.text_cps = 1``` in gui.rpy (Or whatever number)
For some reason, ```default preferences.text_cps = 0``` keeps my settings as they are.

Example test game: First reload is when cps = 0, second reload is when cps = 5
https://user-images.githubusercontent.com/57463682/133952213-14e7268d-1dd6-4747-9c52-480dc7813b18.mp4

.

**Comment by renpytom** [comment]
The problem here is that you have two ``default preferences.text_cps = ...`` statements in your game. The one you added in gui.rpy, and almost certainly the one that's present from the start in options.rpy. I've checked how Ren'Py works, and it looks like the two of them will change the default, then change it back, which would cause the problem you're seeing. 

So it's likely caused by that duplication.

**Comment by thugzillaDev** [comment]
Ok, thank you!
