### ISSUE TITLE
[Question] Build Android dists on CLI

### ISSUE THREAD

**Issue by H4M5TER** [renpy/renpy#3048]
Versions:

- Debian 11
- Linux 5.10.16.3-microsoft-standard-WSL2
- Windows 10 Professional 21H1 19043.1237
- RenPy 7.4.8
- RAPT 7.4.8

I'm trying building on CLI for migrating building to CI.
Following [this thread](https://lemmasoft.renai.us/forums/viewtopic.php?t=51133), `./renpy.sh launcher distribute --dest ~ --package pc /path/to/game` just work for me.
Following [the old Android Building Document](https://github.com/renpy/rapt/blob/master/0old/doc/android-packaging.rst), everything was fine until started building.

-2. OpenJDK 1.8 installed, Python 2.7 installed.
-1. `python2 android.py installsdk`
```log
Traceback (most recent call last):
  File "android.py", line 9, in <module>
    import pygame_sdl2
ImportError: No module named pygame_sdl2
```
0. Python2 uninstalled.
1. `../lib/linux-x86_64/python android.py installsdk` succeed
2. `../lib/linux-x86_64/python android.py configure` completed
3. `../lib/linux-x86_64/python android.py build /path/to/game release`
```log

Updating project.


Creating assets directory.


Packaging internal data.

Could not import runpy module
Traceback (most recent call last):
  File "android.py", line 69, in <module>
    main()
  File "android.py", line 56, in main
    build.build(iface, args.argument[0], args.argument[1:], launch=args.launch)
  File "buildlib/rapt/build.py", line 548, in build
    iface.background(pack)
  File "buildlib/rapt/interface.py", line 252, in background
    f()
  File "buildlib/rapt/build.py", line 543, in pack
    make_tar(iface, private_mp3, private_dirs)
  File "buildlib/rapt/build.py", line 184, in make_tar
    compile_dir(iface, sd)
  File "buildlib/rapt/build.py", line 138, in compile_dir
    iface.call([PYTHON, '-O', '-m', 'compileall', '-f', dfn])
  File "buildlib/rapt/interface.py", line 235, in call
    subprocess.check_call(args, cwd=plat.RAPT_PATH)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/subprocess.py", line 191, in check_call
subprocess.CalledProcessError: Command '['/home/debian/renpy-7.4.8-sdk/rapt/../lib/linux-x86_64/pythonw', '-O', '-m', 'compileall', '-f', u'/home/debian/renpy-7.4.8-sdk/rapt/project/renpyandroid/src/main/private']' returned non-zero exit status 1
```

How to use RAPT correctly? Will there be CLI building documents? (I'd like to contribute.)

**Comment by Dobby233Liu** [comment]
Try adding Ren'Py's own Python 2 to PATH (add the executable path and the python2.7 directory)
> For reference: [my hack GitHub Actions CI workflow for building an Android build](https://github.com/Dobby233Liu/renpy-SideProj/blob/rpy7.4.8-android/.github/workflows/android.yml), [plus a version edited for nightly](https://github.com/Dobby233Liu/renpy-SideProj/blob/prepare-for-nightly-rapt/.github/workflows/android.yml). This felt like an advertisement of my shitty project

**Comment by kobaltcore** [comment]
I can provide some info on this since I've been working on some tools to manage Ren'Py from the command line.

Three things:
1. Ren'Py has some custom libraries/files built in that it imports. As such, starting it with anything but the Python version shipped with each Ren'Py release is prone to failure. Instead, you should enter through renpy.sh or a similar way to use the integrated version, since that has all the necessary modules available.
2. Building Android apps is accessed via the `android_build` subcommand, not the `distribute` subcommand, i.e. `./renpy.sh launcher android_build <input_dir> assembleRelease --destination <output_dir>`
3. You should be able to get command-line help by running `./renpy.sh launcher -h` which will explain the commands and arguments to you.

In case you're curious, I'm also building some tools to automatically install and used Ren'Py via CLI and on headless servers [here](https://github.com/kobaltcore/renkit). It's still WIP though.

**Comment by H4M5TER** [comment]
@Dobby233Liu
Thanks. `export PATH=~/renpy-7.4.8-sdk/lib/linux-x86_64:~/renpy-7.4.8-sdk/lib/python2.7:$PATH` did'nt work for me

@kobaltcore
Thank you for your information. It's good to know that renpy.sh launcher has (much) more subcommand than `distribute`.
`assembleRelease` works for me. Are there other options (gradle commands?) for choose?

**Comment by kobaltcore** [comment]
The two I know of are `assembleRelease` and `assembleDebug`. Since the launcher says it'll forward arguments to Gradle, I would assume that you can take a look at Gradle's documentation to find some other useful things to pass in, though most likely you only really need the release assembly step.
