### ISSUE TITLE
"Skip Mode" in Ren'Py Launcher for 6.17.0.282

### ISSUE THREAD

**Issue by weetabix-su** [renpy/renpy#307]
The word "Skip Mode" appeared while I was using the Ren'Py Launcher, then it disappeared after a few screens (and some keyboard presses). I don't know what triggered it and I don't know what made it go away.

![20140223](https://f.cloud.github.com/assets/2226326/2240218/66101414-9c80-11e3-9142-7127391135e4.png)

**Comment by brimbel** [comment]
It might be caused by typing non-ASCII characters? I have an AutoHotKey script for typing ç (C-cedilla), — (em dash), • (bullet point) and pressing my usual shortcut for them causes Skip Mode when the AHK script is enabled (and not when the script is disabled). It seems to toggle skipping and even works in Ren'Py games too.

Holding down either "ctrl" will also make the "Skip Mode" text appear in the Launcher.

**Comment by renpytom** [comment]
It's there to allow you to skip the work of actually making your game... or else, just a mistake. Fixed.
