### ISSUE TITLE
[Request] Ability to click buttons without pre-focusing game window

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#3112]
If the Ren'py game window is not currently focused and you intend to click a button in it, you must first click on the window and only then after the window has gained focus will you be able to click to activate the button. So something that would otherwise take only one button click will require 2. Admittedly this is not an issue for normal usage since you don't expect users to tab in and out during play a lot, but for the users who do this can be a small appreciated QOL feature, and for other fringe cases it can be a bigger deal.

Case in point, I created a model viewer tool (as a standalone Ren'py project) to help me visually select expressions during the scripting process and it's been a super handy tool, but at the moment it takes me twice as many clicks to select expressions because I first have to click on the game window to focus it, and only then can I select the expression I want. Being able to do this in one click would reduce the amount of clicks I have to do in half. For a long project this results in a non negligible time gain.

I brought this issue up on the discord server and Somniarre said they remember being able to do this in 7.3.5, but no longer after 7.4.0. I rummaged through the changelog but didn't find any note related to it, so I imagine it got changed as a result of some other feature being addressed. Is it possible that this specific thing could be reversed, or to give developers the option to toggle it?

ps: For what it's worth, the standard in software is for you to be able to activate buttons without needling to pre-focus the window. Web browsers and game engines like Unity work this way.

**Comment by renpytom** [comment]
7.3.5 had the same behavior as 7.4, so it wasn't a change. My guess is it's been this way since the switch to SDL2 in 6.99. 

That being said, I think it might make sense to make this change in non-visual novel tools, like the launcher. So I'll add a config variable to control this. I don't think that this is a good behavior to have in visual novels, as that first click would advance the game, which I don't think we want. 

For my own reference,

https://discourse.libsdl.org/t/sdl2-on-focus-gain-first-click-detection/23185

has the hint that needs to set for this.

**Comment by Kuroonehalf** [comment]
Presumably the user has already read the current piece of text before they tabbed away, so it being skipped when they return shouldn't be a problem. And even if hadn't read it, the text log menu is there to help.

But yeah, for regular play it's not a big deal.
