### ISSUE TITLE
.__doc__ returns None

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3119]
Whenever I try to retrieve the doc string of a class or function it returns None.

For example:

`getattr(Class, "__doc__") `
or
`Class.__doc__`

I try to display it as text inside a screen using: 
text `str(Class.__doc__)`

My intention is building documentation using sphinx just like Ren'Py does.

**Comment by Gouvernathor** [comment]
The simple answer would be that most functions and classes exposed by Ren'Py, with some notable exceptions such as Displayable or Transition, are not available for anything other than calling them (or their constructor, in the case of classes).
This means that you're not supposed to subclass random elements of the renpy API, as you can see in #2813 for example, and this extends to the `__name__` attribute for example, which is often not equal to the name the object is exposed as.
Just as well, the `__doc__` attribute should not be accessed by renp'py creators even when it exists, because they are intended for internal developpers (people who develop renpy itself, as opposed to people using renpy to create games).

If you still want to make something which displays infos about renpy's internals, know that it will scarcely work, that you're not supposed to do it, that even the parts which work may unexpectedly break from one version to another, and that classes' docstrings, if any, are usually in `Class.__init__.__doc__` rather than `Class.__doc__`.

**Comment by Booplicate** [comment]
> Just as well, the `__doc__` attribute should not be accessed by renp'py creators even when it exists, because they are intended for internal developers (people who develop renpy itself, as opposed to people using renpy to create games).

That's not how documentation works. Anyone be it a game creator or a renpy developer should be able to read what a class/function/variable does. Especially that applies to people who want to contribute to this project. It feels like there's a massive wall when you try to understand how the internals work. As well as some people might need those "undocumented" functions when they feel like the engine is being too restrictive. It's also easier to code when you can get all the info you need in the editor (or game console) than having to open a browser to read *available* documentation somewhere else.

> Some functions are actually classes (like Dissolve), and some classes are actually functions (like Character) or objects (like Fixed).

Wouldn't be a problem with proper documentation.

**Comment by renpytom** [comment]
Ren'Py runs with the Python optimizer (-O) enabled, and part of that means that the __doc__ strings are stripped at runtime. I may change that in Ren'Py 8 (the Python 3 version), but not before then. I don't see a good way to make this change before then. 

Note that while you can use undocumented functions, you can't then come here and ask us to support them. The documentation is the documentation.

**Comment by raspberry-soft** [comment]
Thank you very for the explanation. I understand it now.
