### ISSUE TITLE
Document mismatch about u_viewport uniform variable

### ISSUE THREAD

**Issue by ruu2** [renpy/renpy#3225]
There is a description about u_viewport uniform variable at https://ja.renpy.org/doc/html/model.html#uniforms-and-attributes, but there isn't at https://www.renpy.org/doc/html/model.html#uniforms-and-attributes.
I don't know why, but there seems to exist document mismatch.
As long as I have tried, u_viewport uniform variable is not defined by default in renpy version 7.4.11.2266.

**Comment by Gouvernathor** [comment]
According to the basefile's [git blame](https://github.com/renpy/renpy/blame/master/sphinx/source/model.rst), the `u_viewport` uniform has been documented since no more than 2 months, so the reason is probably as simple as that the online english doc not having been regenerated since.

In such cases of doubt, you can read the documentation relevant to your specific renpy version (including nightlies) by going to the `doc` subfolder in the directory where renpy is installed. You'll find the entire doc generated as html pages.

> u_viewport uniform variable is not defined by default...

This may be that the version of renpy you quoted dates from before the uniform was added. If not, the question may deserve a separate issue about the uniform variable itself (and not about its presence in the doc).

**Comment by ruu2** [comment]
In my offline document, there is no description about u_viewport.

I think 7.4.11.2266 is today's latest stable version. So now I know problem is that online jp document, which page is yet written in English, is perhaps beyond current stable version. (Now for me it's OK because I understand u_viewport will be added in future release and it's not problem that I can't use u_viewport in my version of renpy.)
