### ISSUE TITLE
Renpy Crash when trying update to Nightly build

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#3248]
Hello, I'm having an issue updating Renpy (current version 7.4.11.2266) to either Renpy 7 or Renpy 8 Nightly. Both version crash due to same error regarding a missing file or directory. This is from updating to Renpy 8, Renpy 7 is the same except it's "py2-linux-x86_64".
`IOError: [Errno 2] No such file or directory: u'\\\\?\\C:\\Users\\Desktop\\Renpy\\renpy sdk\\lib\\py3-linux-x86_64\\_renpysteam.so.new'`

I've attached a log file from update folder, hope that helps.
[log.txt](https://github.com/renpy/renpy/files/7920654/log.txt)

**Comment by Gouvernathor** [comment]
Does this still happen with the recent nightlies ?

**Comment by KatieCheerios** [comment]
Yes, it does. Same error. I don't even have steam libraries installed.

**Comment by Gouvernathor** [comment]
When this happens, you're using an installed version of the last Release (7.4.11.2266), correct ? And updating to... any of the two available versions fail ?
If so, can you try [installing ren'py again](https://www.renpy.org/latest.html) somewhere else in your PC, and try to update the version you just installed ? This is to see if your current installed version is corrupted, or if the bug is more general.

**Comment by KatieCheerios** [comment]
Redownloaded the Renpy and now it worked. Maybe something in mine is corrupted. Both versions are the same though.

**Comment by Gouvernathor** [comment]
Yes, it's most likely a failed update or something which corrupted your installed version. You should use the clean install, or delete your old one and reinstall it anew,
I'll consider this closed, but you can reply here if the problem persists or strikes again.
