### ISSUE TITLE
[Request] Button to delete saves and game cache in the launcher.

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3273]
I was thinking that it would be a good idea to implement under force recompile in the launcher an option to delete the cache and saves, I think this would facilitate having to open and delete the games manually or having to go to the game folder and delete them.

**Comment by via-my** [comment]
That would be pretty helpful. I just spent an hour fixing my project. The backups didn't work and Ren'Py didn't throw any tracebacks. The reason it broke was under the "AppData/Roaming/RenPy/ProjectName" folder. If there was a simple button to delete this folder, that would add another way to fix things like this since it's not that obvious.

**Comment by renpytom** [comment]
I'm not sure i want to commit to this. Why do you need to delete these things?

**Comment by via-my** [comment]
In my case seems like Ren'Py broke the save file. So I managed to fix it after manual deleting.

**Comment by Neyunse** [comment]
In my case, the files for some reason were not updated and for some reason gave me the errors that were already fixed and persisted. This happened by using the auto-save of visual studio code, and even if I deleted the cache and saved files, the old changes were still appearing. I also deleted the backup folder and after a couple of tries it was fixed.
