### ISSUE TITLE
[Question] Linux version (Flatpak | Wayland)

### ISSUE THREAD

**Issue by BirdInFire** [renpy/renpy#3290]
My two question are pretty simple, 
First : i have read that SDL2 who is used in renpy is capable to render directly on wayland (so ignoring xwayland) is renpy launcher launch on wayland or does it use the Xwayland to actually work ?
If it use xwayland does in the next major version (8) will it be using Wayland by default ?

Second : Do you think it's possible to make a flatpak of the launcher and publish it on flathub.
Like that you generate only 1 version of the package and it erase the actual way where some distro isn't up to date with renpy.

Thanks for the answer.

**Comment by renpytom** [comment]
Sorry for the delay getting back. 

I suspect support for wayland will be coming eventually, though probably not until after 8.0/7.5. 

I don't have plans to make flatpaks, but the .tar.bz2 on the Ren'Py site should work with most modern distros, as it carries the vast majority of libraries that Ren'Py uses.

**Comment by BirdInFire** [comment]
> Sorry for the delay getting back.
> 
> I suspect support for wayland will be coming eventually, though probably not until after 8.0/7.5.
>
> I don't have plans to make flatpaks, but the .tar.bz2 on the Ren'Py site should work with most modern distros, as it carries the vast majority of libraries that Ren'Py uses.

Thanks for the answer hope to see a native (if it not already the case) wayland support, for the flatpak i asked only for a more secure experence sandboxed, if i PR a firejail profile do you think it will be accepted ?

And if i manage to create a flatpak myself, do you think it can be added as "unofficial" version on the website ?

**Comment by renpytom** [comment]
I'd strongly consider a firejail profile. 

I don't really want to promote unofficial versions on renpy.org, but if you can come up with reasonable scripting to make it, I'd be very interested in adding that to the build process.

**Comment by renpytom** [comment]
Marking as an enhancement for the wayland support. I don't plan on working on flatpack or firejail, but would accept scripting, as described above.

**Comment by BirdInFire** [comment]
@renpytom after some test i have a renpy.profile who seem to work : 
The two last line are spaced & comment because not everyone want them ("net none" disable internet, "x11 none" force wayland only mode (on gnome decoration are missing).
in this config i take the default that renpy launcher is in "/opt/renpy" & the game are in "/opt/renpy/Games"

include disable-common.inc
include disable-devel.inc
include disable-exec.inc
include disable-passwdmgr.inc
include disable-programs.inc
caps.drop all
nodvd
nonewprivs
noroot
nosound
notv
nou2f
seccomp
seccomp.block-secondary
shell none
noexec ${HOME}
noexec /opt/renpy/Games/renpy
private-dev
private-tmp
whitelist ${HOME}/.renpy
whitelist /opt/renpy

#net none
#x11 none

**Comment by BirdInFire** [comment]
for the desktop entry i have : 

[Desktop Entry]
  Encoding=UTF-8
  Name=Renpy
  Comment=Renpy Launcher
  Exec=/usr/bin/firejail --profile=/opt/renpy/renpy.profile /opt/renpy/renpy.sh
  Icon=/opt/renpy/renpy.png
  Type=Application
  Categories=Utility;Application;

**Comment by lavilao** [comment]
Renpy has native wayland on versión 7.4, just export SDL_VIDEODRIVER=wayland. Unfortunately is versión 7.4.x only as later versions complains about sdl not having the wayland driver available

**Comment by lavilao** [comment]
Try using this ```export SDL_DYNAMIC_API=/usr/lib64/libSDL2-2.0.so``` and ```export SDL_VIDEODRIVER=wayland```

**Comment by orowith2os** [comment]
@lavilao is there some reason why `SDL_DYNAMIC_API` is needed? Shouldn't it be loading in the system SDL in automatically if it's available? I'm not too interested in poking around the codebase to see what it does to override it, so asking here.

**Comment by lavilao** [comment]
> @lavilao is there some reason why `SDL_DYNAMIC_API` is needed? Shouldn't it be loading in the system SDL in automatically if it's available? I'm not too interested in poking around the codebase to see what it does to override it, so asking here.

It does not use the system sdl by default thats why `SDL_DYNAMIC_API` is needed, if You don't use it it Will throw an error saying that wayland is not available.

**Comment by Inui-senpai** [comment]
> Try using this `export SDL_DYNAMIC_API=/usr/lib64/libSDL2-2.0.so` and `export SDL_VIDEODRIVER=wayland`

I've searched incorrect resolution detection fix on my Linux distro for too long, and only these exports fixed that. I have two 1080p monitors, and because of that Ren'Py and some other apps thinks I have a **one** 4K monitor, and they looks way too small because of that.

But there's a nuance, as they say: although the resolution of the primary monitor now detects properly, launcher's and my projects' windows looks slighly downscaled. I can resize them, yes, but I would prefer proper look after startup.

Here's hoping that migration to SDL3 fixes this once and for all.

--
Edit: I've made a workaround for my companions in misfortune:
1. Create .sh file with this content and name it something like `renpy_wayland_fix.sh`:
```bash
export SDL_DYNAMIC_API=/usr/lib64/libSDL2-2.0.so.0
export SDL_VIDEODRIVER=wayland
sh renpy.sh
```

2. Launch it as app and don't be surprised that Ren'Py Launcher's window is kinda small:
<img width="600" height="450" alt="Image" src="https://github.com/user-attachments/assets/ba4d5fea-a068-4ea6-b9fb-8ca75d040b30" />

3. Open the Console (Shift+O) and send this command:
```
renpy.reset_physical_size()
```

4. After that launcher's window will take the correct size:
<img width="800" height="600" alt="Image" src="https://github.com/user-attachments/assets/18dd6c4e-a123-4fd5-95d4-50a7f76770f4" />

Note: You should send the aforementioned command in Console **every** time you start Ren'Py anew **(and when you launch your projects too!)**, otherwise its window will become smaller and smaller, until you cannot see anything.
