### ISSUE TITLE
[Request] Any plan for supporting h.264 codec videos?

### ISSUE THREAD

**Issue by sweater2** [renpy/renpy#3293]
Do we have the plan of supporting h.264 codec (ffmpeg libx264), which is very commonly used for mp4 videos? Thanks!

**Comment by uyjulian** [comment]
H.264 is patented, use VP9 videos instead.

**Comment by renpytom** [comment]
Correct - I don't think there's much of a need for patented codecs when there are open codecs without licensing issues.

**Comment by VXsz** [comment]
Please devs, if you could, I hope you do revise this decision, I know it's patented but there are a lot of use cases where h264 is actually better than the vp9 codec.

Now to the most important reason. Both vp9 & vp8 (and even currently av1, but it's getting better by the day) look way worse and retain details way worse on grainy videos than h264 videos, I did a lot of tests, and in every single one of them the vpx encoder (vp9) is way worse than the x264 encoder's result, also other reasons why it's better overall:
* Practically every device nowadays has an HW decoder (and they can handle extreme sizes) for h264, which means better playback and compatibility, it's really the industry standard in like every platform & service. 

* The x264 encoder, compared to vpx is a lot, _a lot_ better. the example below to showcases it, it's because of how mature x264 has become and how good it is, if done right it outright blows vp9. vpx is no-where as good as x264, even with the most intense settings it still misses the quality target by a lot, even the ffmpeg docs for the vpx encoder has scarce info, and there aren't many options for the encoder to play with, opposite if what you could do with x264 which in contrast has million knobs (and they all do matter and help a lot). You can see the difference by visiting ffmpeg both docs for x264 & vp9.

* It's saves much more space while retaining details more than vp9 on some cases (more often than not, unless static elements are everywhere), it looks better overall even when starved, opposite of vp9 that begins to become blocks of smears which isn't that great, specially if someone is space constraint.

I've tried and got a little sample so you can see it yourself, this is huge for me and many developers as it allows for me to encode the videos and cut-scenes way better and make the filesizes a lot smaller while maintaining the vision I want to show. Grain and fine details get absolutely killed, and with 3D renders there are a lot of 3D fine detail that gets lost (say, noise and film grain effects), and the quality degrades a lot worse. It's noticeable when people try to compress the content further (it looks much worse and blurry) with vp9.


Now to the meaty bit, and to show how significant adding h264 could be;

* Grainy video, a clip from the show "The Walking Dead" which falls under fair use in this case (it's one of the prime examples of intense grain), both encoded at 8mbps from a high quality source [1080p/23.976fps/24mbps] at the respective encoders' best settings possible. 

Screenshots: https://slow.pics/c/oUtWycp0 (you can switch between h264 & vp9 with the left and right arrow keys. Down for the next comparison)
Video files can be found here for further inspection: https://drive.google.com/drive/folders/1eBL8irymMnTPp68A2jMc5IeFvJ7uYMSU?usp=sharing
Notes: As you can tell, it's **extremely** blocky and washed on the vp9 (just like the number "5" beside the door on the first screenshot, it is much better on the h264), and they are both at the same _given_ bitrate through ffmpeg command (results are: vp9 is about 7.3mbps, and the h264 is 7.9mbps) this even goes to show how unreliable vp9 encoder could be, it missed the mark by a bit which could make a slight difference, both were 1 pass encoded as I didn't have the hardware time, but generally the h264 is just a lot better. Also vp9 only worked with a few cores and was much slower, I think this happens with extremely slow settings but I'm not sure due the lackluster documentation.

I only encoded that scene since they cover a lot of the bad part of vp9 and show why x264 is overall better in the regard of grain and high motion scenes, I'm not gonna fully bash vp9 & the vpx encoder as they can be slightly better than h264 when it comes to very static content, where's the motion is slow/minimal, but anything more than minimal, x264 really does surpass it. The Big Buck Bunny for example, static shots are a bit better on vp9 but once there is any movement, rocks and other textures like grass get completely blurry and the bunny's fur too. I can provide many examples if required of various scenarios.

I hope this suggestion is taken into consideration, I was actually surprised when I realized h264 wasn't supported, but I can see why, yet I feel it should be as it's really an old codec and is still great in terms of quality and compression not to mention how extremely wide supported it is, almost any device can play it back with relative easy and minimal power use (so less battery drain).

**Comment by uyjulian** [comment]
YouTube videos are in VP9 and they look quite good. They have their own encoders.  

In that case I recommend you upload video to Youtube then download VP9 encoded video using e.g. youtube-dl.

For mobile device, video playback will be done using native decoder, so in that case you can use H.264 in mp4 there and you can save battery life with hardware decoder. In other case, please use the open codec like VP9.

**Comment by renpytom** [comment]
It's not worth me getting sued over.

**Comment by suphamster** [comment]
> It's not worth me getting sued over.

At least if you would not merged all ffmpeg shared build dlls (in v7 and newer) to one named librenpython.dll it could allow at least on Windows builds to manually replace avcodec-57.dll and etc to which one that has h.264/265 support and it would solved your fears about sue.
P.S. Btw why you decided that somebody would sue for it since your project is free (non commercial) and since nobody sued ffmpeg and tons of other software like players and encoders that are using it,,,

**Comment by morganwillcock** [comment]
> .S. Btw why you decided that somebody would sue for it since your project is free (non commercial) and since nobody was sued ffmpeg and tons of other software like players and encoders that are using it?

ffmpeg is a good indicator that the situation isn't that straight-forward:
https://ffmpeg.org/legal.html

**Comment by bzalel** [comment]
ffmpeg uses the x264 library.
https://en.wikipedia.org/wiki/X264
The same applies to the lame library for mp3s.
https://en.wikipedia.org/wiki/LAME
These libraries have been created from scratch and are open source.
For this reason, ffmpeg can use these formats without any legal issues.

Currently, H264/X264 is one of the most widely used formats.
Why spend hours converting videos when it's as simple as including the same support that ffmpeg has without restrictions?

Please consider this possibility.

**Comment by bzalel** [comment]
ffmpeg uses the x264/OpenH264 libraries.
https://en.wikipedia.org/wiki/OpenH264
The same applies to the lame library for mp3s.
https://en.wikipedia.org/wiki/LAME
These libraries have been created from scratch and are open source.
For this reason, ffmpeg can use these formats without any legal issues.

Currently, H264/X264 is one of the most widely used formats.
Why spend hours converting videos when it's as simple as including the same support that ffmpeg has without restrictions?

Please consider this possibility.

**Comment by uyjulian** [comment]
h.264 patents have not expired yet. https://meta.wikimedia.org/wiki/Have_the_patents_for_H.264_MPEG-4_AVC_expired_yet%3F

It will probably be safe to include h264 once Fedora legal reviews and starts including ffmpeg with h264 enabled in their distribution.

**Comment by bzalel** [comment]
Your reference is correct for H264
But OpenH264 is free
At the end of the very article you posted, it references what I mentioned.
I quote in your link:
Cisco's OpenH264 binaries can be used for free.

I'm not asking to infringe on anything, just showing a free alternative, and I'd like it to be considered.

**Comment by uyjulian** [comment]
Using OpenH264 with patent license requires the user to accept license agreement and download from Cisco servers (bundling is not permitted)

**Comment by bzalel** [comment]
In case you do not want to impose Eula in all Ren'Py installations.
For example, it can be added as an optional library, with its corresponding Eula, in the case of enabling it.
Where is the problem?

H264 is the most widespread format today, along with H265.
The refusal implies, for example for a 10 minutes video (1Gb or 2Gb).
It would take about 1 hour with processors at 100%. With all the power consumption that entails.
If we multiply by all those who use the application, it is an not very sustainable solution, ecologically speaking.

Please, I think I speak for more people, asking to at least consider the feasibility of this option.

**Comment by VXsz** [comment]
> I recommend you upload video to Youtube then download VP9 encoded video

This should NOT be a serious suggestion. I hope you realize that.
Not only is it a wild way to get a VP9 encode, that doesn't even resemble any real workflow, nor should any creative be doing this. Running VPX with medium setttings on an Intel Core Duo would probably be faster than even starting the upload to YouTube (ps: I know youtube encode flow and qualities very well) and produce a much higher quality video at lower sizes than YT. 

> Please, I think I speak for more people, asking to at least consider the feasibility of this option.

I'm hopeful. IMO this issue should at least be opened and be in considerations.
H264 is the defacto standard. I'm sure even Samsung smart fridges support it in HW.
