### ISSUE TITLE
[Request] More builtin packages

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3302]
While not every package is being used by every developer, it's very handy to have them when you need them. Some packages you can add by yourself, but usually that's very hard and requires a lot of trial and error to add even simplest packages. You add one, it starts missing another. And then there's different libs for different platforms.
There's 2 reasons why a developer may need it. First, you may want to use it yourself. Second, a 3rd-party package may require some of the builtins. With the latest Ren'Py we got a lot of new packages to work with, that's really nice and almost 1:1 to real Python programming, but sometimes *almost* isn't enough.
As I understand, Ren'Py doesn't ship all default packages to save some space? I don't think that's a big issue. Although, maybe it's worse for mobile platforms? I don't know.

I want to propose to include all builtin Python packages with Ren'Py.
* If it's hard, I'm willing to help you with it, just guide me a little where to start.
* If there's an issue with including them all and you're sure we can't do anything about it, can we get an option to select which packages we want to include in the build? Basically make them opt-in.
* If nothing of the above is acceptable for you, can you guide me how I can build Ren'Py with all the builtin packages included with it?

**Comment by renpytom** [comment]
Is there something you're thinking about that's missing? IIRC, the stuff that's missing is either because it has a dependency I don't want to ship wiht Ren'Py, or because it really makes no sense as part of a visual novel.

**Comment by Andykl** [comment]
I think it would be good to have access to your local installed packages during development. Right now I have to wrap around subproccess or other workaraounds. 
One of the packages I think may be good to ship with is PIL especially if there will be some way to transform its Image structure into pygame.Surface.

**Comment by renpytom** [comment]
I don't think that's possible. Ren'Py doesn't use your local Python interpreter.

**Comment by Booplicate** [comment]
One of our side packages requires sqlite3, for example. The package uses it to read some cities data from its db. We need it because it's one of our main features we can't drop now.

That one is probably the most important for us, but there are a few more. It's understandable if most VN won't need it, right now even we only need it because it's a dependency (although, there's a possibility we could use it in our code, too). But it'd be really cool if there was an option to select which builtin packages your VN will use, or if we could just build Ren'Py with the packages we need.

**Comment by Gouvernathor** [comment]
I think we should document a canonical easy way to include python builtin packages in a game, like including third-party ones currently is.
Given that (pure) python misbehaves with rollback among other things, I don't think we should ship-in more packages than strictly necessary. It should be a voluntary thing done by devs knowing what they're doing.

**Comment by renpytom** [comment]
There are a couple of things going on here. 

The first is that as of Ren'Py 7.4. we've moved to a model where all of the non-Python modules are linked together into a single binary, rather than having .pyd/.so/.dylib files all over the place. That had a bunch of advantages to it - the big one being that "antivirus" doesn't seem to be making nearly as many false positives with Ren'Py, and it also allows the one-step startup on Windows. But it does mean that swapping binary modules in an out isn't possible. 

I don't think it makes sense to include sqlite with Ren'Py, either. Fundamentally, I don't think that a visual novel engine needs to ship with an SQL database engine, and I tend to think supporting a SQL database engine across multiple platforms would be hard. (I'm especially thinking of Android, where the game isn't unpacked into files on disk.)

I'd suggest focusing your efforts on your dependency, and figuring out how to extract the data from it into a format that doesn't need a database engine to access. 

Beyond that, you can take a look at renpy-build. It should be possible to add a task (define it in tasks/sqlite3.py, add it in tasks/__init__.py) to build sqlite, and then edit the Setup files in source/ to include it as a Python module. Building Ren'Py requires a lot of resources (Probably about 50GB), but renpy-build does automate the process. 

I don't think that as a project, we want to go down the rabbit hole of adding tons of binary dependencies in the hope of getting third-party Python modules to work. I don't think it's likely such modules will fit well into the Ren'Py environment if they're not designed for it, so we're just pushing the problem out a single step. Modules that do work with Ren'Py should limit themselves to the set of supported modules.

**Comment by Booplicate** [comment]
Sadly we haven't had any luck, possible because we don't have ubuntu (it's specified in the requirements). We might try again later. We also discovered that we could use the unittest module in our project, too. So not giving up yet.

I'll close this as the former question has been answered. That said, would be cool to get the building process a bit more documented.

**Comment by renpytom** [comment]
You should be able to get Ubuntu running in a VM, and build from there. (The specific version of Ubuntu is also important.) That's how I test the build process.

**Comment by farzher** [comment]
i need to use sqlite. it's built into python. yet somehow isn't possible to use in renpy...? .-.
use case is reading the browser history for an ARG style visual novel.

**Comment by renpytom** [comment]
@farzher I'd strongly suggest distributing a second program, and using subprocess to call it.

**Comment by multimokia** [comment]
So, revisiting this as I'm taking a crack at building the engine via renpy build

So far I got it spun up and able to build renpy alright, I've added the extra libraries that python requires to build SQLite3 into it to the prepare script, added `sqlite3/` to `pythonlib.py`, which does export the sqlite3 folder in the build now
and added the `--enable-loadable-sqlite-extensions` to the configure calls in `python3.py`, however looks like when trying to `import sqlite3` in projects run by the sdk, the issue of `ModuleNotFoundError: No module named '_sqlite3'`

I did have a couple ideas on where to go from here but I'm not too familiar on how the build process works here, like binary linking etc. so I had a question which could help me get there
1. Should I add the amalgamation `sqlite3.c` file into `tars` and point to it from somewhere? If so, how do I link that?

While I understand I can create a subprocess and interact with it, however i fear the latency might be too great to make it a viable option and would rather bake it in directly for the speed.

If you have any tips on where I might be going wrong, or anything I can look at to get a better grasp on the build process, that'd be super helpful!

**Comment by qTich** [comment]
@multimokia

You need to add - https://github.com/python/cpython/blob/3.12/Modules/Setup.stdlib.in#L145
by analogy - https://github.com/renpy/renpy-build/blob/master/source/Python-3.12.8-Setup.stdlib

Also you will need to build `sqlite3` from sources by analogy of some
of https://github.com/renpy/renpy-build/tree/master/tasks

You will also need to add `-lsqlite3` when `renpython`
(aka https://github.com/renpy/renpy-build/blob/master/tasks/renpython.py#L45).

**Comment by multimokia** [comment]
I'll give this a shot, thank you

**Comment by multimokia** [comment]
As for building, would simply providing the amalgamation C file suffice? Or would I need to build out the `make` commands?

**Comment by qTich** [comment]
> As for building, would simply providing the amalgamation C file suffice? Or would I need to build out the `make` commands?

https://www.sqlite.org/howtocompile.html
