### ISSUE TITLE
Odd behaviour when using Transform or ATLTransform with a child in a transform statement

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3350]
If a Transform without child passed as expression statement, it will be interpreted as displayable and will be rendered as Null. Assuming that Transform is a simplified version of ATLTransform, it is expected that the parent transform will only take transform state from it.
```py
label main_menu:
    return

define config.default_transform = None

image img 1 = Solid("#0ff", xysize=(100, 100))
image img 2 = Solid("#ff0", xysize=(100, 100))
image img 3 = Solid("#fff", xysize=(100, 100))

define centr_transform = Transform(align=(0.5, 1.0))
transform centr_atltransform:
    align (0.5, 0.5)

image test:
    align (0.5, 0.0)
    "img 1"
    pause 0.5
    centr_atltransform  # works
    pause 0.5
    "img 2"
    pause 0.5
    centr_transform  # used as Null child
    pause 0.5
    "img 3"

label start:
    show test
    pause
    return
```

And vice-versa, if ATLTransform with the child passed to another transform, it tries to execute it ignoring the child. 
```py
label main_menu:
    return

define config.default_transform = None

transform test:
    zoom 1.0

image test:
    test(child=Solid("#0ff", xysize=(100, 100)))
    # or At(Solid("#0ff", xysize=(100, 100)), test)

label start:
    show test
    pause
    return
```

**Comment by renpytom** [comment]
Here are my thoughts on these: 

The first example is operating the way Ren'Py is designed, I think. The documentation for this case is wrong - it should only work with ATL transforms, while non-ATL transforms are treated as other displayables. I'll fix this.

The second example requires a change. I think the right answer is that if an ATL transform has been given any parameters (including a child), it should be treated as a displayable. Otherwise, it should be included.

I'll make the changes to the documentation, and then the code.
