### ISSUE TITLE
Improvements of im.Cache

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3381]
This is probably should be done in a same way as pyanalsyis, i.e. to have old version as py2 and improved as py3 only.
1. Change `get_total_size` method to `current_size` field, changing only when CacheEntry is added or removed, because right now it repeatedly calculates the same thing in `cleanout`.
2. Get rid of `pin_cache` as it was depricated 8 years ago.
3. Revisit `config.cache_surfaces` and maybe get rid of its usage, as every `im` entry that uses it has an improved replacement.
4. Since the dictionaries are ordered natively in Python 3, it is possible to get rid of the slow (for large caches) `sorted(self.cache.values(), key=lambda a : a.time)` and just `self.cache[CacheEntry] = self.cache.pop(CacheEntry)` to move CacheEntry to the end.
5. Revisit threading stuff to see if there are more efficient way to preload images in a thread like asynchronous code or multiprocessing?
6. Potentially use existing C-boosted `functools.lru_cache`?

**Comment by trothamel** [comment]
I've done 1 and 2. 

3 isn't a good idea, since old games still use image manipulators. 

4 doesn't seem necessary - the sorting should be very fast. 

5 we could plausibly run a second preload thread, if it's a problem. The real issue with preloading is the prediction, I think - that runs n the main thread. 

6. Probably not needed - I doubt the actual image cache manipulation takes up enough time.
