### ISSUE TITLE
Movie with not found play parameter crashes with image parameter

### ISSUE THREAD

**Issue by YoruZakura** [renpy/renpy#3394]
Hello,

When trying to use the `Movie()` `image` parameter like described in the documentation for a fallback behavior in case `play` is not found, a blocking `IOError` is raised, which prevents the fallback.

Example code (in a blank Ren'Py project, with the gui/frame.png image present):
```renpy
image movie_fallback = Movie(play="notfound.webm", image="gui/frame.png")

label start:
    scene movie_fallback
    pause
    return
```

The following error happens during the interaction handling:
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 5, in script
    pause
  File "renpy/common/000statements.rpy", line 455, in execute_pause
    renpy.pause()
IOError: Couldn't find file 'notfound.webm'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 17, in script
    pause
  File "/home/selenyhr/renpy/renpy/ast.py", line 2015, in execute
    self.call("execute")
  File "/home/selenyhr/renpy/renpy/ast.py", line 2003, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/selenyhr/renpy/renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 455, in execute_pause
    renpy.pause()
  File "/home/selenyhr/renpy/renpy/exports.py", line 1563, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay)
  File "/home/selenyhr/renpy/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/selenyhr/renpy/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/home/selenyhr/renpy/renpy/display/core.py", line 4025, in interact_core
    renpy.audio.audio.periodic()
  File "/home/selenyhr/renpy/renpy/audio/audio.py", line 1162, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/selenyhr/renpy/renpy/audio/audio.py", line 1140, in periodic_thread_main
    periodic_pass()
  File "/home/selenyhr/renpy/renpy/audio/audio.py", line 1082, in periodic_pass
    c.periodic()
  File "/home/selenyhr/renpy/renpy/audio/audio.py", line 518, in periodic
    topf = load(filename)
  File "/home/selenyhr/renpy/renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "renpy/loader.py", line 1010, in load
IOError: Couldn't find file 'notfound.webm'.
```

Using the GNU/Linux 7.4.11 official release.

Could you please take a look at this and see what can be done please?

**Comment by YoruZakura** [comment]
I have created a sub-class of `renpy.display.video.Movie` to temporarily get around this issue:
```renpy
init python:
    class MovieFallback(renpy.display.video.Movie):
        def __init__(self, *args, **kwargs):
            from renpy.loader import loadable

            if kwargs.has_key("play"):
                if not loadable(kwargs["play"]):
                    kwargs["play"] = None

            super(MovieFallback, self).__init__(*args, **kwargs)
```

Quick and dirty :) since this removes the faulty `play` argument, `Movie()` then functions as normal, and displays the fallback image.

**Comment by Gouvernathor** [comment]
I'm 99% sure the problem lies in the `default_play_callback` function, because _play is passed to the music.play function without checking if the file actually exists.
There are three solutions I can see, none of them good.
1) We could check the existence of the file within the constructor, and replace it with None, like in the MovieFallback example shown above.
The problem in a solution like this is that if you're playing on a platform where that movie file exists, save while it is displayed, and load that save, there's a good chance the error will strike back.
2) We could change what the `default_play_fallback` function does, to make it check for the existence of _play as a real file.
The problem with that is that the *content* of the default function is actually documented, so changing is not retro-applying (old games where it's replaced with a slightly modified version will still have the bug), and maybe retro-incompatible.
3) We could change what happens in the play() function, to somehow keep the problem from happening.
That's probably the worst solution, because it would effectively mask every missing file issue and replace it with playing silence.

**Comment by Gouvernathor** [comment]
Update : the problem doesn't come from default_play_callback at all.

**Comment by geomat0101** [comment]
fyi, re: your point number one above.  I wired up the MovieFallback class as a displayable and modified the tutorial_video to use 
`
image launch = MovieFallback(play="oa4_launch.webm", pos=(10, 10), anchor=(0, 0), image="target1.png")
`
I took a save while the video was playing, quit, moved it out of the way, and when it reloaded I got the alt image as desired instead of the movie.

Not conclusive, but hopefully instructive

![image](https://user-images.githubusercontent.com/102607949/162229616-71d3b7a3-b2e5-4f30-9f41-ffb0ca0d850b.png)

![image](https://user-images.githubusercontent.com/102607949/162229821-d7b46821-b340-4997-a91b-a15413a5c261.png)

**Comment by geomat0101** [comment]
N.B. renpy.movie_cutscene could probably do better about missing media files also...

**Comment by Gouvernathor** [comment]
@geomat0101 your test was indeed instructive, we learned thus that @YoruZakura didn't use the nightly version.
About renpy.movie_cutscene : it's not intended to prepare an object which can be saved afterwards, like Movie. Manually using the documented renpy.loader.loadable function before passing an argument to movie_cutscene is what creators should do in this case. Some may perhaps choose to branch to something else, an ATL animation for example, since unlike a Movie call that will definitely happen at play time rather than init time.
Errors should not pass silently, unless explicitly silenced.

**Comment by renpytom** [comment]
I think I prefer #3396, as the fix. I don't think that we should be trying to fix renpy.movie_cutscene when the movie file doesn't exist - that can be fixed with renpy.loadable, and of course you could wrap the whole thing in your own Python function if there's a common idiom.
