### ISSUE TITLE
Scroll down with scroll wheel to go to next line of unread text

### ISSUE THREAD

**Issue by NintendoManiac64** [renpy/renpy#3416]
While reading Clannad recently, I re-discovered what is for me the most physically comfortable way on my hand to go to the next line of text - scrolling down via a mouse's scroll wheel.

For reference, this is also present in Fate/stay night and is also how I read through that VN over a decade ago.

However AFAICT, on Ren'py, the scroll wheel only works for scrolling up or down through previous text and does not work on going to whatever the next new line of text would be.  This similarly differs from both Clannad and Fate/stay night where both of them allow you to also use the scroll wheel to go through previous text as well as to continue to the next line of new text.

(one minor difference though is that, for Clannad, when you reach the last line of previously-read text, you have to click an on-screen button to return to the current line of text; with Fate/stay night you can keep scrolling down even when you reach the final line of previous text and it'll switch back to the current line of text)

**Comment by raspberry-soft** [comment]
I agree, that is the most comfortable way of reading a VN but you can easily change that in your own VN. Check out the keymap documentation.

**Comment by NintendoManiac64** [comment]
Wait, so this DOES already exist in Ren'py but it's just not configured as such by default?

Then maybe it's be more accurate for the request to be this to be part of the default keymap.

**Comment by Gouvernathor** [comment]
You can *try* enabling it with something like:
```rpy
init:
    $ config.keymap['dismiss'].append('mousedown_5')
```
This will enable dismissing a say statement (a dialogue) and passing to the next, with the mousewheel going down.
However, this may conflict with the normal behavior of rollforward, as both actions are not meant to be triggered by the same keystroke. You may very well trigger the "dismiss" action by mistake in cases when you would have wanted to rollforward. Ren'py's behavior in that case, to the best of my knowledge, is not documented and will not be guaranteed.

Now, there are basically two things we could do to change renpy. The first would be that in the case where there are conflicting keys for both the rollforward and the dismiss, and a rollforward is possible, no dismiss is done. The second would be to (then) add mousedown_5 to the default keys for dismiss.
The first may or may not be done, because we would have to maintain that feature through future versions and that's something we're generally not eager to do.
The second one would be a change in the way renpy works by default, so I would be rather against that change for the reasons marked as warning on the top of [the doc page](https://www.renpy.org/dev-doc/html/keymap.html).

**Comment by NintendoManiac64** [comment]
I just did some testing and it generally does seem to work without any problems but there's one niggle - the "rollforward" basically gets completely eliminated.  So when you're viewing previous text, 'mousedown_5' instead has the text appear as if it were the next new line of text even if it's still previously-read text (basically it behaves the same as if you had left-clicked).

Now I have absolutely no skills with coding and/or software-dev (I am a hardware person through-and-through), but I would think that the easiest solution would be to simply mimic Fate/stay night's behavior in this regard where 'mousedown_5' will operate as "rollforward" until you reach the end of previously-read text at which point 'mousedown_5' will then behave as 'dismiss' instead.

**Comment by NintendoManiac64** [comment]
...that being said, if the concern then is that users may end up 'mousedown_5" quickly to get through existing previously-read text and expect it to automatically stop when they get to the current line of text, then maybe the Clannad method where you have to click or select an on-screen button to return to the current text is the safer way to go but that would presumably require much more work to implement.

That being said, an on-screen button to return to the current line of text would actually be particularly handy when you have indeed done a lot of the "rollback" action and are reading text that is far away from the current line of text.  Therefore, the Clannad method would actually automatically mitigate the possible issue caused by the Fate/stay night method, meaning that, dev-time notwithstading, one could even just straight-up implement both concurrently.

**Comment by renpytom** [comment]
This isn't something we'd change by default, at this point. We have thousands of visual novels made with Ren'Py, and I don't think that we're going to suddenly change the bindings of the mousewheel so half the games work one way by default, and half the other. 

What is probably a better idea would be to have some sort of input configurator, to let the player rebind buttons as they like. I'm pretty impressed by the way Steam Input does it - I think extending that to the keyboard and mouse, and re-implementing it for controllers, would be a good idea. That's a longer term project, though. 

As an adaptive technology, many mice come with the ability to rebind the mouse wheel to what you want, and I'm sure there are third-party tools that can do it too. 

So, no to key-binding, yes to a more general configurator. (No ETA on the latter, though.)

**Comment by renpytom** [comment]
Closing this in favor of #3429.
