### ISSUE TITLE
{a} tag doesn't take a URL variable as an argument.

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3418]
I want to write:

```
define URL = "www.url.com"
define HOMEPAGE = "{a=URL}Homepage{/a}"

label start:
    "Visit my [HOMEPAGE]"
```

But Ren'Py takes the URL variable as a label and uses `config.hyperlink_protocol = "call_in_new_context" ` instead of opening the browser.

If I define it like this it works:

`define HOMEPAGE = "{a=www.url.com}Homepage{/a}"`

But that will mean having to write my URL multiple times and gets the code difficult to mantain (I want to make just one URL variable to use it everywhere)

I find this behavior counterintuitive and thought it was a bug until I read the docs.

Edit: So my question is why `HOMEPAGE = "{a=www.url.com}Homepage{/a}"` works but `HOMEPAGE = "{a=URL_VAR}Homepage{/a}"` doesn't.

**Comment by mal** [comment]
This is a feature of Ren'Py to allow clickable text to call labels, which is what you're seeing - Ren'Py is trying to use the literal string `URL` as a label to call. I doubt it's possible to change this as there would be no way to distinguish between (for example) `google.com` and a label `google` with a sub-label `com`.

Thankfully, using this knowledge it's possible to support the behaviour you were hoping for with just a little extra code. Since we know that it's going to try and call a label, let's give it one, one that opens the URL stored in the variable.

```rpy
define URL = "https://www.renpy.org"
define HOMEPAGE = "{a=url}Homepage{/a}"

label start:
    "Visit the Ren'Py [HOMEPAGE]"
    return

label url:
    $ renpy.run(OpenURL(URL))
    return
```

**Comment by raspberry-soft** [comment]
Hi! Thanks for the workaround. I get why labels are prioritized, but my question is why using `{a=url}` during a script opens the browser but `{a=url_variable}` don't. If labels are called then `{a=url}` wouldn't work or viceversa, if one work, the other should too. That's what made it counterintuitive to me.

**Comment by mal** [comment]
Literal URLs i.e. `{a=https://www.renpy.org}` include `http:` or `https:` which Ren'Py understands to open in a browser (see docs link below). Your `{a=url_variable}` example doesn't give Ren'Py any way to identify what the string `url_variable` means, so it gets the default behaviour - trying to use it as a label.

src: https://www.renpy.org/doc/html/text.html#a-tag

**Comment by raspberry-soft** [comment]
Oh I get it. Could Ren'Py try getting the `url_variable` value before deciding what to do?

**Comment by mal** [comment]
It's possible that you could write your own hyperlink handler with those semantics and set it as the default if you wished it, but I don't believe that would be a good thing for Ren'Py to actively support.

Imagine you got `a=url_variable` working the way you suggest, and then months from now while working on unrelated code it makes sense to create a label named `url_variable`. Now your link which you weren't changing at all sends you to this new label instead of the web address inside the variable with that name. That's pretty confusing, and probably a bit annoying.

**Comment by renpytom** [comment]
If you want a double interpolation like this, you have to ask for it. Writing the example as:

```
define URL = "www.url.com"
define HOMEPAGE = "{a=[URL]}Homepage{/a}"

label start:
    "Visit my [HOMEPAGE!i]"
```

Will work, since the !i causes the interpolated text to undergo interpolation.

**Comment by raspberry-soft** [comment]
Thank you so much!
