### ISSUE TITLE
unexpected behavior of after_load label and callbacks

### ISSUE THREAD

**Issue by the66F95** [renpy/renpy#3480]
```py
default test1 = 0
default test2 = Test(10)

init python:
    class Test():
        def __init__(self, v=0):
            self.v = v
        def inc(self):
            self.v += 1

    def after_load():
        global test1
        test1 += 1
        test2.inc()

    config.after_load_callbacks.append(after_load)

label after_load:
    $ test1 += 1
    $ test2.inc()
    return

label main_menu:
    return

label start:
    while True:
        "[test1], [test2.v]"
```
a changed object within label or callback doesn't retain its value after rolling back prior the loading point. (clean 7.4.11.2266)
is this an undocumented change in 7.4.x compared to 7.3.x?
it basically takes away the ability to update stuff for new versions or you have to block rolling back.

**Comment by renpytom** [comment]
I don't believe this is a change, as it should have worked this way from the start. 

This is a hard problem, as I don't see a good way to retain the changes while rolling back to the original value when required. I'd suggest  calling renpy.block_rollback() in the after_load label, which should solve this problem.

**Comment by the66F95** [comment]
hmm sure, blocking roll back is an option but also a restriction for the user.
try the code in 7.3.5 for instance and it works as expected, the changes are being retained.

**Comment by the66F95** [comment]
ok, i went through the 7.4 branch and adding this in 7.4.7
```py
        if self.log:
            self.current = self.log[-1]
        else:
            self.current = None
```
in python.py l.2091[commit](https://github.com/renpy/renpy/commit/62e4f3017bbd67261c063cef8983112ecca90360) broke the desired functionality.

**Comment by renpytom** [comment]
That's a bug fix, though. Ren'Py wasn't rolling things back when it should have, which was an error.

I'm thinking the right thing to do might be config.after_rollback_callbacks. Since a rollback occurs whenever a load does, this could be responsible for upgrading things in both the load and rollback cases.

**Comment by the66F95** [comment]
you would still need to somehow mark that this is an after_load rollback and not an ordinary rollback.
and even then, wouldn't rolling back after a called callback function also undo the changes made?
i basically had to block the rollback again after upgrading things and am back at the initial problem (-_-)ゞ

**Comment by Booplicate** [comment]
What's your use case for this? I'd use `after_load` if I need to fix some game variables. For example, if I had code where I set a variable to a value that's too high. I'd reduce the value in `after_load`, but also change the code in the script where I set the variable in the first place so it doesn't get over bounds. In that case even if you rollback, the value will be within the bounds.

In your example above you're just counting how many times the game was loaded. And since you rollback behind the loading point, it gets reset. Then you just continue the game, you never get to those loading callbacks, so your counter never increments. It makes total sense to me.

**Comment by the66F95** [comment]
> What's your use case for this? I'd use `after_load` if I need to fix some game variables. For example, if I had code where I set a variable to a value that's too high. I'd reduce the value in `after_load`, but also change the code in the script where I set the variable in the first place so it doesn't get over bounds. In that case even if you rollback, the value will be within the bounds.
> 
> In your example above you're just counting how many times the game was loaded. And since you rollback behind the loading point, it gets reset. Then you just continue the game, you never get to those loading callbacks, so your counter never increments. It makes total sense to me.

```py
default test = Test(10)

init python:
    class Test():
        def __init__(self, v=0, new=0):
            self.v = v
            # self.new = new

label after_load:
    $ test.new = 1
    return

label main_menu:
    return

label start:
    while True:
        call print

label print:
    "[test.v]"
    return

# label print:
    # "[test.v] [test.new]"
    # return

# create a save without the 'new' attribute
# update your class, use the new `print` label, restart and load the save file
# now roll back
```

**Comment by Booplicate** [comment]
I had to change your test a little:
```renpy
label start:
    while True:
        call print_test

label print_test:
    $ i = "value: {}\nhas new: {}".format(
        test.v,
        hasattr(test, "new")
    )
    "[i]"
    return
```
But I see the problem now.
I can suggest to modify `__setstate__` of your class.
```renpy
init python:
    class Test():
        def __init__(self, v=0, new=0):
            self.v = v
            self.new = new

        def __setstate__(self, data):
            if "new" not in data:
                data["new"] = 1
            self.__dict__ = data
```

**Comment by the66F95** [comment]
look, that class was just an example, any modification to any object is reverted by a rollback.

imagine a simple variable that is holding a description of whatever. at some point in the game/vn its value is changed depending on the value of another variable.
in the new release i want to update that description. without retaining the changes made in after_load, the user would have to start again if i would change the code entirely.

**Comment by Booplicate** [comment]
That's why I asked you for your use case. You gave that class, I gave you a solution.
> imagine a simple variable that is holding a description of whatever. at some point in the game/vn its value is changed depending on the value of another variable.

I don't think there's an existing solution for that if you want to allow to rollback prior to loading point.

**Comment by the66F95** [comment]
i still hope @renpytom takes a second look at that [commit](https://github.com/renpy/renpy/commit/62e4f3017bbd67261c063cef8983112ecca90360), because if it fixes console problems and makes production code somewhat less usable, there might be a chance for a change. ;)

**Comment by renpytom** [comment]
I'm thinking the right answer might be to run after_load when rolling back past the load point.

**Comment by mal** [comment]
That could place a particularly heavy toll on games that do a significant amount of work to achieve save compatibility, not to mention break some that are using NoRollback classes to help do so. Changing rollbackable values during after_load seems like the perfect case for blocking rollback if it's not possible via other means.

As Booplicate tried to get to, having a real world case for this would be useful to understand the actual problem being faced, as in the abstract it seems somewhat of an extreme edge case running counter to all current expectation of after_load and at least middlingly probable that there may be a better solution specific to the problem, rather than changing a reasonable expectation within Ren'Py - that values supporting rollback, get rolled back. :/

**Comment by renpytom** [comment]
I've documented this change, and the need to block rollback when migrating data. My fundamental thought is that if rollback is allowed over the load point, it has to work correctly, since in the normal case (loading a savegame when the underlying game isn't changed) could lead to data not being rolled back correctly, and hence problems.

**Comment by the66F95** [comment]
my ideal solution would be retaining made changes until they get reverted/changed by the script during rollback.
but blocking rollback if necessary is fine, it just limits somewhat the user experience.
