### ISSUE TITLE
Ideas for launcher's Navigate Script section

### ISSUE THREAD

**Issue by Moshibit** [renpy/renpy#3567]
- Files tab
1. Ability to sort by init offset priority. (I think it's easier than sort blocks and statements that can have the init statement)
2. Ability to filter translation files.

- Screens tab
1.  Ability to sort screens by zorder value

**Comment by Gouvernathor** [comment]
Several init blocks with several priorities can exist within the same file, and the init offset statement can also be included several times.
Usually it's not even the first statement in a file, so you would have things (define, default and stuff) at init 0 priority, then you would get your init offset, so sorting that file relative to that init offset would shadow those first statements.

The translation bit, if I understand that correctly that would be to filter out all translation files and/or to view only files of a specific language. Well translate blocks actually can be included anywhere, so we can't do a meaningful filter based upon translate blocks, it would have to be based upon the location of a file within the tl/ directory (or outside of it). But it would remain a good idea, imo.

For the screens' zorder, I'd be surprised if only integer litterals were authorized instead of general python expressions, so there would be quite a number of unsortable screens. If one of these expressions takes for example a parameter of the screen, it makes no sense to guess its zorder.

**Comment by renpytom** [comment]
Offhand, how much do you actually use the launcher's navigation section? I've found that I don't use it as much as I though I would, and I'm wondering if other people have different views of it.

**Comment by Moshibit** [comment]
For me it is more useful than the sidebar of text editors.

**Comment by renpytom** [comment]
I think of these suggestions, the one that's really appealing is filtering translation files.

The init offset priority one seems very much like a misfeature, in my opinion, as it'd be inviting people to set init priority in order to reorder the files in the launcher, which seems like a really bad idea. 

Filtering tl files seems reasonable, we should add that. 

Sorting screens by zorder value seems like it would be a lot of work for a fairly minimal benefit. (And to some extent, it also invites the same sort of misfeature as the init offset priority.)

**Comment by JSearUK** [comment]
My theme bolds and italicises TODO, NOTE and WARNING when encountered in a comment, so I've been using those in my commentary as a heads up to myself about what might still need overhauling. It might be handy if all three of those were available in the Navigate Script panel, making it more flexible and acting as a triage list for devs.

**Comment by morbil** [comment]
While I do think sorting file by init priority isn't practical, it would be useful to have a list of init blocks sorted by priority. Bonus if defines could optionally be grouped and sorted by init priority.
