### ISSUE TITLE
Warn/error for top level python statements

### ISSUE THREAD

**Issue by Numerlor** [renpy/renpy#3648]
Currently a top level python statement ($/python block) is silently not executed, causing some potential confusion for users (visible code that at a glance should execute doesn't). Warning or raising a compilation error would help prevent this

**Comment by Gouvernathor** [comment]
I'm not sure we can easily detect the difference, at compilation time, between the two following python blocks:
```rpy
python:
    a = 1

label b:
label c:

python:
    d = 5
```
If you didn't know, that label structure works, and d gets affected a value following a `jump b` or a `jump c`.
We could imagine some sort of flag variable during compilation which would be False initially, then True after the first encountered label, and which would trigger a compilation error when a python block or dollar line is encountered and that variable is False.
However, that wouldn't be patchable like we usually do, with config variables, since it would happen at compilation time.

We could maybe, theoretically, save these in a batch, and then after the init phase and the config variables are set, decide whether we throw a compilation error or not. But that would in my opinion add significant overhead and compilation time for a quite small reward (in comparison).

So except if a released game doing this (by mistake) is deemed not worth supporting, I don't think we will do that. And it's not likely we'll see it that way, considering the importance we give to backward-compatibility (= the ability for older games to run on newer versions of renpy).

**Comment by Booplicate** [comment]
> I'm not sure we can easily detect the difference

I thought renpy builds a tree of nodes, is it impossible to know if you're in a label?

I'd expand this to warn for other things like `init`, `screen`, `style`, `default`, etc inside labels. If a node doesn't make sense to be in the current context, the developer should be warned what they are doing is wrong.

**Comment by Gouvernathor** [comment]
For the latter part of your message, this was considered, and rejected mainly for the reasons I gave : retro-incompatibility and the impossibililty of adding an opt-out. In both cases however, it could be added to lint.

For the first part, well contrary to virtually every other thing ending in a colon and a newline in renpy or even python, the label statement doesn't actually have a block (hence why it doesn't require indenting). The lines following it don't "belong" to it, in the way the return line belongs to the while loop in the following example:
```rpy
while True:
    return foo
```
So it wouldn't be that simple.
However, there's the bit of code (somewhere) which raises an exception when you do this:
```rpy
label .loc1:
label entrance:
label .loc2:
    return 5
```
but is good when you remove the first label statement. But then again, you fall back to the compatibility and opt-out issue.

**Comment by Numerlor** [comment]
I hadn't considered that will continue off where they end without a return, but then this seems like more issues could be addressed if labels were simply required to have an explicit block like other statements to be consistent with them.

> So except if a released game doing this (by mistake) is deemed not worth supporting, I don't think we will do that. And it's not likely we'll see it that way, considering the importance we give to backward-compatibility (= the ability for older games to run on newer versions of renpy).

This seems like backwards thinking; backwards compat is important but behaviour that's more than likely to cause an error should at the very least be deprecated. 
Updating the SDK is already a conscious decision made by the developer and an involved process, fixing a couple of parsing errors that may help prevent bugs in their code shouldn't be a problem. There's also a major release around the corner that introduces other breaking

**Comment by renpytom** [comment]
Warnings for code unreachable from a label makes sense. We're not going to change the syntax of Ren'Py over this.

**Comment by Numerlor** [comment]
renpy going up a version presents a great opprotunity to bring in changes that break existing code bases, as it already does that purely from the 2->3 migration; expecting an indented block for labels to separate them out and disallowing random statements at the top level like what's currently allowed is not that large or a change, or one that needs a lot of manpower to fix from errors it raises. 
I'd expect most projects that are large enough to have a good reason to update to be already properly indenting their code.

While better than nothing, warning for blocks unreachable from a label is quite limited. As far as I know the code, the first label without a return (assuming there's way to exit a label with a return without also jumping elsewhere) means that anything after could be a part of it.
