### ISSUE TITLE
Improve the Lint to avoid overriding python classes and functions

### ISSUE THREAD

**Issue by malikiz** [renpy/renpy#3664]
The idea is for the linter to report an error if the developer writes something similar in the code:

```py
label my_label(type = 'simple'):
    "[type] type"
```

or

```py
init python
    def test(type = 'simple'):
        pass
```
In this case, type is the default python class, and reassigning it can cause errors like this:
```
  File "renpy/common/00matrixcolor.rpy", line 57, in __ne__
    return not (self == other)
  File "renpy/common/00matrixcolor.rpy", line 51, in __eq__
    if type(self) != type(other):
TypeError: 'unicode' object is not callable
```

Since I'm not too good at python syntax, I made a similar mistake. Related issue: https://github.com/renpy/renpy/issues/3593

**Comment by Gouvernathor** [comment]
The second thing you're proposing is likely not going to happen.
For example, given that `library` is a variable defined by renpy (it's an alias of `config`), the following are detected and flagged by lint :
```rpy
default library = 4
define library = 5
```
but this one is not
```rpy
init python:
    library = 6
```
And that's both because it's much harder and slower to do, and because we kinda give creators some slack as for the python blocks - like, if you use python instead of renpy statements, you're on your own and we won't bother you.
