### ISSUE TITLE
renpy.input block skip (Ctrl) when using Ctrl+v to paste

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3682]
While `renpy.input()` prevents the skip, I think it would be a good idea to prevent the skip action from being detected when the "control" key is pressed while pasting in the input. I noticed this after creating the poll https://github.com/renpy/renpy/pull/3658, It looks like renpy is trying to do a skip when using control+v.

**Comment by Org-gith** [comment]
One way to tackle this would be to put a variable being toggled to True just before the renpy.input is shown, and if that variable is True you simply disable the hotkey 'ctrl' for the skip, rendering it undetected, then put that variable back to False after renpy.input is done.
For example:
```
if not 'variable':
      key "K_LCTRL" action Skip()
```
I actually like that Ren'py doesn't make that kind of decision for us, personally, in that situation, I would prefer that skip doesn't get interrupted by renpy.input, but I can see why you would prefer it in your case, but the great thing IMO is that we can both make it work as we want currently, otherwise Ren'py is choosing one way over the other but it doesn't have to be that way I think.

**Comment by renpytom** [comment]
You've never been able to skip during an input, though.

**Comment by Org-gith** [comment]
By default yes, but I unlocked that possibility by doing a custom keymap and having skip() going through a function. No changes in the engine were made so that wasn't hardlocked. I think if it's not hardlocked in the engine it's better. Or maybe applied only if copypaste = True.

**Comment by renpytom** [comment]
Fixed by 675ec559e .
