### ISSUE TITLE
[7.5+] Dissolve behaving strangely

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#3690]
Using dissolve under certain conditions is not working anymore. I tested 7.4.10/7.4.11 and can report that everything is working accordingly in these previous versions. 

Example of a problematic use of dissolve:
`define dis04 = { "master" : Dissolve(0.4) }`

```
show image onlayer video zorder 100 with pixellate
pause    
show image2
hide image onlayer video zorder 100
hide image2 with dis04
$renpy.pause(delay = 0.4, hard = True)

```
Prior to 7.5, the "image2" would fade away using Dissolve(0.4), now it will be not dissolved because it's close to the hide/show which overrides the dissolve that should happen and make the image disappear instantly instead (not using the dissolve). 

For example in 7.5, if I want to have image2 dissolve properly I would need to add a pause like that in the middle now:
```
show image onlayer video zorder 100 with pixellate
pause    
show image2
hide image onlayer video zorder 100
$renpy.pause(delay = 0.1, hard = True)   # <===== added a pause here to make the dissolve work
hide image2 with dis04
$renpy.pause(delay = 0.4, hard = True)

```
Tested with define config.atl_function_always_blocks = False or define config.atl_function_always_blocks = True, but doesn't make a difference.

**Comment by Gouvernathor** [comment]
What happens if you manually add a `with None` before the hide-with line ?

**Comment by Org-gith** [comment]
```
    show warning_adult onlayer video zorder 100 with pixellate
    pause
    show warning_adult as warning_adult2
    hide warning_adult onlayer video zorder 100
    with None  ##  <=== added with none instead of pause
    hide warning_adult2 with dis14
    $renpy.pause(delay = 0.4, hard = True)
```
    
  Seems to make it work like it used to prior to 7.5

**Comment by Gouvernathor** [comment]
The reason why the `with None` created with the inline-show-with statement doesn't do its job (because that `with None` *is* created by the parser) is because of this line of code : https://github.com/renpy/renpy/blob/e20f8e8253689d642083270337c24924902b6828/renpy/exports.py#L1643-L1644
The only problem is : that line wasn't modified since 4 years ago, and the whole with_statement function it's inside of wasn't either (except for one comment six months ago). So, the problem is before.

**Comment by Gouvernathor** [comment]
Found it : this is an unintended consequence of #3650.
I think the With.execute should call `always=paired`, and the `paired` argument of with_statement be either plainly removed or left for compatibility (but it was not documented, so it's not really necessary). Since Ren'Py has worked fine regarding this feature for the last 11 years, I see no reason to change the way it works, even if that behavior was caused by a mistaken commit.
Otherwise, it could be called like `always=paired, paired=paired`, or in another way decided upon which behavior it yields for renpy.
@mal ?

**Comment by mal** [comment]
I think the fix is to simply snip this section of code, which would allow the callback to work as intended, but skip over this condition that could never previously be executed (since `paired` was never passed, and so could never be a `dict`):
https://github.com/renpy/renpy/blob/e20f8e8253689d642083270337c24924902b6828/renpy/exports.py#L1640-L1644

That said, this code was presumably written with certain functionality in mind, so only @renpytom can say if abandoning the original intent here is the way to go.
