### ISSUE TITLE
renpy.loadable backslash issues (on Windows)

### ISSUE THREAD

**Issue by loafylemon** [renpy/renpy#3705]
Windows 11
Renpy 7.5.022062601n

```renpy
s = "images\eileen happy.png"
renpy.loadable(s) # Returns False
renpy.exists(s) # Returns False

s = "images/eileen happy.png"
renpy.loadable(s) # Returns True
renpy.exists(s) # Returns True
```

This is problematic because functions such as `os.path.join`, `os.path.normpath`, and `posix.normpath`, won't work as intended because Python modules on Windows by default utilize backslashes in file paths.

**Comment by Gouvernathor** [comment]
First, backslashes are not supported in paths manipulated by renpy since version 6.2.0 (though I'm not sure why).
Second, in Python, you have to prepend a r before a path containing backslashes, otherwise the `\n` in `"game\new_eileen.png"` will turn into a newline character. So even if renpy accepted them, the string you're giving doesn't contain any backslashes.

**Comment by loafylemon** [comment]
I admit I missed escaping the backslash with `\\` in the example, it's rather late where I live. Sorry.
