### ISSUE TITLE
The play argument to a Movie can be a list.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#3710]
But it's treated as a string, potentially causing the error at: 

https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=64884

**Comment by MiiNiPaa** [comment]
Description of `play` argument in documentation for Movie sprites and Movie objects should similarly be updated indicating possibility of using list of names instead of single string.

https://www.renpy.org/doc/html/movie.html#movie-displayables-and-movie-sprites

https://www.renpy.org/doc/html/movie.html#Movie
