### ISSUE TITLE
Improve LayeredImage documentation/examples

### ISSUE THREAD

**Issue by pjpollina** [renpy/renpy#3742]
Love LayeredImages, can't get enough of em, but the docs really don't express how to properly use stuff like if_any, at, etc. Only reason I was able to eventually figure em out was looking at old forum posts from 2012 and lots of trial-and-error. I can definitely contribute some of this but I figured I'd bring attention to this so others familiar with them could also look into it.

**Comment by Gouvernathor** [comment]
I did some of it in 2c04b71cc2e92c2b4394802a3ea65ebb07b8bfbb and 3036fbd1074dad52a09dcfdadb8e840c07e7e94d.
The issue (as with many requests for how-to-use sections) is that the if_ clauses allow a lot of different uses, and a whole batch of examples wouldn't cover them all. That's why theorical and conceptual explanations are better and more complete - but we can always improve them.
