### ISSUE TITLE
Anchor not working every time Renpy 8

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#3757]
I have a problem with text style property anchor(x,y) and especially that y part. I had this code in screen and encapsulated in viewport
`text "Title" color "#ffffff" size 26 anchor(0.5, 0.5) align(0.5, 0.025)`
But anchoring of the y axis doesn't seem to work properly in Renpy 8. It works in Renpy 7 latest release.
When I  replaced anchor(x,y) with separate xanchor or yanchor it worked in both versions. I'm using the general Renpy 8 build, not nigthly.

**Comment by Booplicate** [comment]
Your code is incorrect. `align` also sets `anchor` internally. So when you set both `anchor` **and** `align`, the result is undefined.

**Comment by Gouvernathor** [comment]
That's correct, see https://www.renpy.org/dev-doc/html/atl.html#list-of-transform-properties for more details. align sets pos and anchor to the given value.

**Comment by Booplicate** [comment]
> when using xanchor and yanchor give pretty defined results

It's still undefined because RenPy doesn't guarantee that would work (correctly anyway) next time you update RenPy or even when launch the game tomorrow.

> anchor is really just pivot and I'm aligning the pivot point relative to the container it's in

What you're actually doing is telling RenPy
"Set `xanchor` to 0.5, set `yanchor` to 0.5"
"But also set `xanchor` to 0.5, set `yanchor` to 0.025" (and `xpos`/`ypos` too, but that's less important here).
Which one RenPy will do first is unknown and might change.

You need to decide which `yanchor` you want: 0.5 or 0.025, then set `xpos`/`ypos` separately.

**Comment by KatieCheerios** [comment]
So I can rewrite it to `anchor(0.5, 0.5) pos(0.5, 0.025)`  instead with align, which should be correct, but it's not intuitive and I'm not aligning it. I guess it's still gonna be "aligned" in the middle of the container etc., but it's actually confusing at first.
