### ISSUE TITLE
Suggestion: defining "conditional compiling" system

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#3760]
A system that completely obscure parts of code in the released build. Useful for example to censor Steam builds.
For example a system like:
#IF-VERSION-BLABLA-CENSORED
show cute girl dressed
#ELSE
show cute girl naked doing naughty stuff

etc etc, since Steam seems to actually decompile .rpyc files to check if there's optional uncensored texts (happened several times for my games) and maybe flagging adult only a game that in reality was completely censored, just because an OPTIONAL adult text is present.
With this system the text wouldn't even show up, so could reduce issues when submitting to Steam.

**Comment by mal** [comment]
Yes, but as noted in the commit message it has the potential to significantly impact stability (both of the game and save compatibility), especially if the condition changes outside of the build process since it impacts compilation. I'm not sure if the changelog omission is intentional, but it may be given the foot-gun potential.

**Comment by Kassy2048** [comment]
A quick test seems to indicate only variables in the `config` namespace are defined when the IF/ELIF statements are evaluated, which is pretty limited. Are there more?

**Comment by Andykl** [comment]
You can create file like 01early_code.rpy and use `python early:` block with python code. 
Because it is compile-time, nothing `init` has run yet, only RenPy proper and early code. Even config not fully inited at that point.
