### ISSUE TITLE
[BUG] First action result not affecting the next actions

### ISSUE THREAD

**Issue by Victorius-Astral** [renpy/renpy#3763]
This will show the page that was before the SetLocalVariable line, and the change brought about by the first action, doesn't count there. I believe it's not an intended behavior of actions.:
```
default current_page = 0
default pages = len(messages)

    # AUTO CHANGE PAGES
timer 8.0 repeat True action [
        SetLocalVariable("current_page", web_messages_page(current_page, pages))
        Show("web_message", dissolve, messages[current_page,]),
        ]
 ```
 Here, with current_page = 0:
  1st action - change current_page to 1
  2nd action - show message [0] in the list
  
 For now, to get it working one needs to calculate the next page in both actions.
 
```
# AUTO CHANGE PAGES
timer 8.0 repeat True action [
        Show("web_message", dissolve, messages[web_messages_page(current_page, pages)]),
        SetLocalVariable("current_page", web_messages_page(current_page, pages)),
        ]
```
 Here, with current_page = 0:
  1st action - change current_page to 1
  2nd action - show message [1] in the list

Version 7.5.1.22070801

**Comment by Gouvernathor** [comment]
This looks like normal behavior. The Show action is instantiated, and its arguments evaluated, way before the timer triggers. That happens in prediction normally, and at the latest when the screen gets shown, so 8 good seconds before the SetLocalVariable action *runs* (=/= is instantiated) and sets the current_page variable to the value you want.

You can try removing the `default current_pages` in your first example : at screen-show time, it will fail at the Show line, saying the variable is not defined. Because the actions and the arguments passed to them are evaluated at show time (at the latest), not at action-run time.

**Comment by Victorius-Astral** [comment]
My logic is derived from how programming works. When I run:
```
funct1()
funct2()
```
I expect funct2 to be able to work on data already changed by funct1

**Comment by Gouvernathor** [comment]
I don't think you understand what happens here. First you define a list of actions, then you run the actions one by one. In your case, the value of `current_page` is read at the moment the Show action is created, and then the first action runs. Your Show action isn't depending on the `current_page` value at the moment it is run, it's depending on the `current_page` value at the moment it is created.
That's just how renpy (and programming) works, because you're not dealing with functions, you're dealing with Actions which are callable objects being first instantiated, then called.

If you want an action which given the same input, sets it to a variable then calls a Show action, I suggest you [create your own action](https://www.renpy.org/dev-doc/html/screen_python.html#actions). It shouldn't be too hard, in your use-case.
