### ISSUE TITLE
[RenPy 8] [Mac Support] 32 bit issue

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#3764]
A few of my players using Mac to play the game have been experiencing issues regarding 32-bit.

A player sent us a screenshot of the warning on steam:
> Your current version of macOS cannot run 32-bit games like this one.  This game may not work.  This game supports Steam Play.  You can run it on Windows via Boot Camp or using a computer.

And when they try launching the app from local files they are given the following error:
> Could not import renpy.bootstrap. Please ensure you decompressed Ren'Py
correctly, preserving the directory structure.

The player we've gathered the most information from is running the M1 Macbook

The game was working correctly on RenPy 7.4
Feel free to contact me on Discord: OscarSix#0001 if you need a Steam key to test the game yourself

**Comment by Andykl** [comment]
If I understand correctly, RenPy 8.0 do not support any 32-bit systems. https://renpy.org/doc/html/changelog.html#platform-support-changes, so it is intended and not a bug.

**Comment by eipeii** [comment]
> If I understand correctly, RenPy 8.0 do not support any 32-bit systems. https://renpy.org/doc/html/changelog.html#platform-support-changes, so it is intended and not a bug.

Let me explain the problem fully, (before we start, it's been a long time since macos stopped 32-bit support.) Although Renpy 8 has discontinued 32-bit support, the game itself appears as 32-bit on Steam. It was opening until the new update, but after the new update it stopped opening. And I only found 1 error code which is "Could not import renpy.bootstrap. Please ensure you decompressed Ren'Py correctly, preserving the directory structure." aaand we are stuck for now.

**Comment by renpytom** [comment]
Ren'Py hasn't supported 32-bit on Mac for a very long time. Is it possible the Steam configuration is wrong?

**Comment by eipeii** [comment]
> Ren'Py hasn't supported 32-bit on Mac for a very long time. Is it possible the Steam configuration is wrong?

Maybe, I think. The developers of the game have been informed, if it's a problem on their feet, I think it will be fixed. But before the last update, the game was still opening even though it warned that the game was 32 bit. So there are 2 possibilities in my mind, either there was an error in the macos part while updating the game itself or there is a problem in the renpy macos update.

**Comment by KiloOscarSix** [comment]
This was on our end. Steam page settings were set up incorrectly. Thanks for all the assistance :)

**Comment by GamesByKinmoku** [comment]
@KiloOscarSix Can you share how you fixed this? I am having the same issue. My game works fine on Mac, but Steam thinks it's 32 bit. I've set it to 64 bit in Steam and it's not helped.
![Screenshot 2023-02-28 at 10 03 14](https://user-images.githubusercontent.com/64895702/221805466-c0882cb2-fa48-454e-98c8-0d7e0c30ce7d.png)
![Screenshot 2023-02-28 at 10 05 16](https://user-images.githubusercontent.com/64895702/221805475-c8e9e99e-b47a-4c60-a11d-8574faa635b7.png)

**Comment by KiloOscarSix** [comment]
@GamesByKinmoku 
![image](https://user-images.githubusercontent.com/26691547/221860533-0704fe52-810a-499d-a826-e8e3fbe8c882.png)
![image](https://user-images.githubusercontent.com/26691547/221860673-435c61bb-9533-49c5-bb16-36a91b7212bd.png)

**Comment by GamesByKinmoku** [comment]
@KiloOscarSix Thank you. I had my depot with all OS and architectures, so I thought I would separate like you have. Unfortunately, it still isn't working so I've contacted Steam support. I'll update the thread once I know what the solution is.

**Comment by GamesByKinmoku** [comment]
For anyone reading this in future, I had two problems:

- Demo was set up correctly, but main game wasn't. Once I set up the main game correctly, the "32-bit" error went away.
- However, I was still unable to download the game through Steam Client. Steam said this was due to using Big Sur and I should update...though my Mac is too old so I've had to live with this problem, meaning other Catalina/ Big Sur users maybe unable to play games through Steam client.
