### ISSUE TITLE
"config.skipping" is not documented

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#3773]
There are several entries for disabling or enabling skipping in Renpy:

1. **config.allow_skipping** to generally configurate if a player is allowed to skip during game / I treat this as a set-once variable, if you never want to allow it during your gameplay, as changes to config variables are not saved when changed during the game.
2. **_skipping** to set during a game, if you want to temporarily allow or disallow skipping (or read the variable if you want to know if it is allowed)

But there also is
3. **config.skipping** to check if Renpy is currently skipping - like calling the function **renpy.is_skipping()**

Could you please make a manual entry for that term? I use it in my game and I am unsure if this will disappear in the future and the game doesn't work anymore. Thank you!

**Comment by Gouvernathor** [comment]
If is_skipping works and is documented (as well as get_skipping btw), why do you need an access to config.skipping ?
It provides a reasonable security - you can access the information of whether the game is skipping or not, but you can't overwrite the information. And we can change how it's determined in the future, potentially getting rid of the variable or making it work differently.

**Comment by m-from-space** [comment]
Thanks for answering.

renpy.is_skipping() and renpy.get_skipping() are functions that return values.

config.skipping is a variable. Testing a variable and calling a function is a different process. What is renpy.is_skipping() doing by the way? Return the value of config.skipping? :)

There are different use cases for using a function or a variable (and theoretically probably also performance differences).

I'm just asking for config.skipping being part of the Renpy documentation, since it's obviously working and doing something, that's all.

**Comment by Gouvernathor** [comment]
renpy.is_skipping currently casts config.skipping to a boolean value before returning it.
Typical example : say we were to add possible values to config.skipping in addition to the two strings it can currently be : we could decide that get_skipping should not return that new value, to support older games using it and only accounting for the two current values. We could also decide that the new way of skipping should not be considered True by is_skipping, and special-case it to return False.
And that's supposing we keep using config.skipping and not nuke it - which I think we could, since it's not subject to pickle issues and it's not documented.

That's for the compatibility reasons. For the rest, "Testing a variable and calling a function is a different process." Yes, that's true, a variable is writable and a function call is read-only. That's one of the reasons why we chose to publish a wrapper function and not the variable : because creators should not write in it.

As for the performance argument, it's up to you : if you think a function call impedes on your performances too much (which honestly I doubt), you can choose to read the code, figure how config.skipping works in the current version of renpy, and use it. But we offer no guarantee about it in next versions of renpy.
