### ISSUE TITLE
Documentation: `has` could use an update

### ISSUE THREAD

**Issue by JSearUK** [renpy/renpy#3802]
https://www.renpy.org/dev-doc/html/screens.html#has-statement

This suggests that the usage of `has` is more limited than it appears to be; for example, the following code works -
```py
screen skill_tree():
    frame:
        xysize (0.5, 0.5)
        anchor (0.5, 0.5)
        pos (0.5, 0.4)
        has viewport
        draggable True
        has fixed
        fit_first True
        add Transform("gui/window_icon.png",
                       xysize=(config.screen_width, config.screen_height))
        textbutton "The 'Full' Package":
            pos (100, 100)
            action NullAction()

label start:
    scene black
    show screen skill_tree
    "Eileen ate too many cookies. Which gym package should she go for?"
```
This has `viewport` as a container. If I'm honest, I don't know if this results in the later `fixed` becoming a container for `viewport` or `frame`. I haven't tested other containers, such as `vpgrid`.

**Comment by renpytom** [comment]
I like the way the documentation is written now. 

While ``has`` does function with displayables other than the layouts (hbox/vbox/fixed), that's not really a usage I want to encourage by making it explicit in the documentation. I don't plan to actively make Ren'Py reject what you have above, but since it's confusing, I'd rather not write the documentation in a way that encourages multiple has statements.
