### ISSUE TITLE
Fadeout doesn't seem to work for partial audio

### ISSUE THREAD

**Issue by Phxntxm** [renpy/renpy#3805]
I believe this is the issue I'm encountering, at least based on the only relevant thing I can find, here: https://www.reddit.com/r/RenPy/comments/v2dnly/cant_get_sound_effects_to_fade_out/

The issue described there is pretty much exactly the same as I have, but I'll describe mine just in case. I'm trying to use a nice crossfade, but also keep sounds playing on the main channel (so that I can still do `stop music` in renpy code, and not have to memorize if it's swapped to the secondary channel).... by doing this:

```py
python early:
    renpy.music.register_channel("music2", mixer="music", loop=True)
    renpy.music.register_channel("sound2", mixer="sound")

    def crossfade(track, fadeout=3, fadein=3, channel="music", loop=None, volume=1.0):
        c2 = f"{channel}2"
        # Get the current playing music, and position
        pos = renpy.music.get_pos(channel)
        cur = renpy.music.get_playing(channel)
        # Stop it on the main channel
        renpy.music.stop(channel)
        # Move it to the secondary channel, based on the same exact position
        renpy.music.play(f"<from {pos}>{cur}", channel=c2)
        # Now stop it with the fadeout
        renpy.music.stop(c2, fadeout=fadeout)
        # And play the new track on the main channel, now that it's been opened up
        renpy.music.play(track, channel=channel, fadein=fadein, loop=loop, relative_volume=volume)
```

It works as expected, until `renpy.music.stop(c2, fadeout=fadeout)` where it just stops abruptly... no fadeout.

**Comment by renpytom** [comment]
The issue didn't seem to have anything to do with partial audio - I encountered the same issue without a full track. The problem is with a play immediately followed by a stop, without an interaction between them. Ren'Py only updates what's playing during an interaction, so this cancels what's playing, and since nothing plays, there's no fadeout. 

This fix adds a new function, renpy.music.pump, that causes changes to take effect when it is called. 

Since that's a new feature, I'm aiming this for 8.1 and 7.6, which should be out in the fall. If you don't want to wait, it should be easy to backport this change into Ren'Py 8.0.x and 7.5.x.

**Comment by Phxntxm** [comment]
Thank you for the speedy response and fix! As for the wait, it's no problem, I an just use swap between the two channels in the crossfade for now till 8.1, it's no big deal.

In the docstring for `pump` I noticed you have: `for example, an play followed by a stop`... when it should be ` a play` instead of `an play` just btw.
