### ISSUE TITLE
modal pauses still time out

### ISSUE THREAD

**Issue by midgethetree** [renpy/renpy#3824]
This was fixed in c1a7591 and then reverted in e5497b, so it still needs to be resolved. Essentially without those edits TIMEEVENTs are reaching PauseBehaviors created by renpy.pause before going through the layers, meaning their modal property is False regardless of if a modal screen is being shown. If the order in which the PauseBehavior is added to the root_widget in interact_core is changed there is still an issue if the mouse is moved, hence c1a7591 also editing PauseBehavior's event method to ignore other kinds of events.

To see this issue for yourself you can just add the following to a fresh project:

`label start:
    pause 3
    "The pause has timed out."`

Start the game and use the X button to get the confirm prompt for quitting to appear while the pause is ongoing. Wait until the duration of the pause is up and see as the dialogue appears, even when the modal confirm screen is still being shown. You can also apply the edits to interact_core from c1a7591 and repeat the same test but move your mouse after the pause should've timed out to see that the dialogue will pop up as soon as you move the mouse, meaning other events are reaching the PauseBehavior and causing this issue.

**Comment by renpytom** [comment]
I was wrong to revert a9d9e0973e3a617f9e5e49f12bead2aa85cd5300. In an old version of Ren'Py, TIMEEVENTs could be merged with other events. That's not the case, so your contribution was correct. Thanks for working to get this solved.

**Comment by Org-gith** [comment]
I tested this commit as this seems the kind of stuff that would break a point and click system for Ren'py and with this commit applied I can't use any buttons on a modal screen which has a pause (or interact with it in any way). 
Having a pause following a modal screen is also the backbone of navigation for a lot of points and click systems. I think it worked that way for this reason, so I'm not sure that reverting was the wrong call but also I have a limited understanding of this.


For example:

```
Show screen language_selection
Pause
```

(language selection has some buttons that jump you to label language_chosen)


Label language_chosen:
_continue_



New observed behavior: Can't interact with the buttons anymore.

**Comment by renpytom** [comment]
@Org-gith I'm a little confused by what you're trying to do, but it doesn't seem correct. A modal screen should keep you from interacting with other things, and I think having the modal screen block a pause is the right behavior to have. Otherwise, you'll have a game that's "running", but no way for the player to interact with it. 

What's more, this change only effects screens with a timed pause, not an untimed pause like in your example. I do think that a modal screen should disable timed pauses. So I don't understand your first example, which doesn't have a timed pause - to me, it seems like you should be using a "call screen" statement there. 

Note there is another change in this sequence, so you may need to test with the 8.0 nightly. 

I'd need some evidence that working with the combination of pause and modal is "adopted widely", as I don't see that. It probably makes sense to compat the old behavior, but I don't think that should stand in the way of fixing what seems to me like a bug.

**Comment by Org-gith** [comment]
Probably me being pepega then, I learned this way of doing things from someone that was doing years of ren'py before me, he taught this method of putting a pause after a modal screen. I assumed it was the way of doing things and I sort of developed this habit of doing code like this for instance:

During the modal choose_language being shown, I take the opportunity to tell him to precache some images in the foreground (with the change introduced in the commit, that code wouldn't be executed anymore).
```
    show screen choose_language with dis_screen
    $ renpy.start_predict("splashscreen_load")
    $renpy.pause(delay = 0.31, hard = True)
    pause
    label splashscreen2:
        $renpy.pause(delay = 0.1, hard = True)
        hide screen choose_language with dis_screen
```

then the screen itself:

screen choose_language:
    zorder 1200
    modal True
    imagemap:
        xpos 442
        ypos 439
        ground "gui/language/russian_idle.png"
        hover "gui/language/russian_hover.png"
        if readytointeract_chooselanguage:
            hotspot (0, 0, 280, 361) at hover_screen_language:
                mouse "button"
                action Jump("splashscreen2")
    imagemap:
        xpos 819
        ypos 439
        ground "gui/language/english_idle.png"
        hover "gui/language/english_hover.png"
        if readytointeract_chooselanguage:
            hotspot (0, 0, 280, 361) at hover_screen_language:
                mouse "button"
                action Language(None), Jump("splashscreen2")

___

I have also alert screen being displayed that are using modal True during gameplay, and while they prevented from interacting with other buttons (like a save screen, using an inventory screen), they were not intended to stop an image animation or an audio from playing in the foreground (basically not intended to stop the script from running) for the short moment where they appeared.

All of this could be done differently, it's just that there is quite a bit of code that relies on the modal screen not affecting timed pause, if it's considered bad behaviour I totally understand. I would definitely not say no to a compat option for the few out there like me if that's something then.

**Comment by shawna-p** [comment]
This should almost certainly be a called screen rather than a shown screen with a pause and modal. Called screens wait for an interaction automatically. For example, your code could instead be:

```renpy
call screen choose_language with dis_screen

# ...
screen choose_language():
    # ...
    hotspot (...):
        action [Language(Russian), Return()]
```

If needed, you can use a timer on the screen itself to indicate when it should become interactable:

```renpy
default is_sensitive = False
screen interactive():

    sensitive is_sensitive

    # Only needed if you show this multiple times; otherwise,
    # default to False will suffice
    on 'show' action SetVariable('is_sensitive', False)

    # Screen contents/buttons/etc

    timer 1.0 action SetVariable('is_sensitive', True)
```

**Comment by Org-gith** [comment]
That makes sense, I wasn't aware of the big difference between call screen and show screen, and that this removed the necessity of using a pause (I thought Call screen was just a Show screen that was running a Hide('itself') at the end of whatever interaction you had with it.).
For the rest of the code, I'm aware this can be done differently (like you pointed out), I just did it that way without thinking because I wasn't aware this was relying on a bug that permitted it, I thought it was okay to use it that way too (with a bunch of codes being on the script directly and not only on the screen). In any case, thanks for the explanation.

**Comment by midgethetree** [comment]
To address the alert screen case you mentioned, modal screens don't actually stop ATL, audio, or even transitions from continuing to play, even with the edits we've been discussing. I don't mind that.

Instead what these edits do is keep the renpy.pause function and equivalent pause statement from timing out while modal screens are shown. So if a renpy game shows multiple animations/effects one right after the other with timed pauses after each anim/effect to wait for them to stop before doing the next thing, a player who opens a modal screen by trying to quit near the end of an anim/effect will see that anim/effect 1 finish but won't see the next anim/effect appear while the modal screen is up. This is how I believe pauses should behave.

Hopefully that clarifies a bit what these edits are supposed to do!

**Comment by renpytom** [comment]
I think I can close this one.

**Comment by Org-gith** [comment]
(thank you for deciding to make a config)
