### ISSUE TITLE
Thai font render issue

### ISSUE THREAD

**Issue by PhakphumV** [renpy/renpy#3864]
Hello,

I found that Thai fonts are not rendered correctly when there is a combination of tone mark and upper vowel.
Here are some examples between what ren'py render and notepad with the same font (Cordia New)

![2022-08-12 20_18_27-_Untitled - Notepad](https://user-images.githubusercontent.com/35300139/184362728-99dbf26e-5f1f-4172-a79a-fe65ae93b9a6.png)
![2022-08-12 20_19_00-_Untitled - Notepad](https://user-images.githubusercontent.com/35300139/184362737-cec9fcbb-d7cf-40f8-a755-d52d536d3363.png)

There was a script to make adjustment from this link https://gitlab.com/sahabandha/renpy-thai-font-adjuster
It's compatible only with renpy-7.4.10-sdk and some limitation. I tried code modification in renpy/text/text.py with the script but it doesn't work properly as I'm still new to renpy. So any guidance would be really appreciated.

In the above Gitlab link, there is also a reference to a very detailed documentation about encoding for Thai which could help on the font rendering script. I believe it could be useful for develop a fix for this issue.

**Comment by renpytom** [comment]
Seems reasonable. I think I should be able to get this into the next major release.

**Comment by PhakphumV** [comment]
Thanks, please feel free to reach out to me if you need some test samples for different combination of Thai characters.

Here is an example from W3.org that can be used as reference.
`แผ่นดินฮั่นเสื่อมโทรมแสนสังเวช  พระปกเกศกองบู๊กู้ขึ้นใหม่
  สิบสองกษัตริย์ก่อนหน้าแลถัดไป       สององค์ไซร้โง่เขลาเบาปัญญา
    ทรงนับถือขันทีเป็นที่พึ่ง           บ้านเมืองจึงวิปริตเป็นนักหนา
  โฮจิ๋นเรียกทัพทั่วหัวเมืองมา         หมายจะฆ่ามดชั่วตัวสำคัญ
    เหมือนขับไสไล่เสือจากเคหา      รับหมาป่าเข้ามาเลยอาสัญ
  ฝ่ายอ้องอุ้นยุแยกให้แตกกัน          ใช้สาวนั้นเป็นชนวนชื่นชวนใจ
    พลันลิฉุยกุยกีกลับก่อเหตุ          ช่างอาเพศจริงหนาฟ้าร้องไห้
  ต้องรบราฆ่าฟันจนบรรลัย           ฤๅหาใครค้ำชูกู้บรรลังก์ ฯ`

**Comment by renpytom** [comment]
I just merged this into Ren'Py proper. To use it, you need to set the language style property to "thaic90", using something like: 

```renpy
style default:
    language "thaic90"
```

**Comment by pitsanu79** [comment]
I need more explanation

**Comment by Gouvernathor** [comment]
The string which ends up in the screen to be displayed must get transformed in order to be correct. To enable that transformation, the style of the [`text`](https://www.renpy.org/doc/html/screens.html#text) in the screen must have the [`language`](https://www.renpy.org/doc/html/style_properties.html#style-property-language) property set to "thaic90".
To make that the default in your game, you can use the code above so that all styles have a `language` of "thaic90", unless specified otherwise.

I assume it's not the default because the transformation takes a bit of time, so slowing down every game just for thai text which happens rarely is not very optimized, best to enable it manually for thai games.

**Comment by PhakphumV** [comment]
Thank you very much @renpytom 
Really appreciate your effort
