### ISSUE TITLE
Removal of the ability to define the default image folder

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#3875]
It appears this function used to exist with config.automatic_images and config.automatic_images_strip ; but they were removed at some point (They're in 00obsolete.rpy, lines 66 and 69).  Where they removed because a better option was implemented?  If so, can you share that?  If not, any plans to reintroduce the ability to change the default image folder?

**Comment by Gouvernathor** [comment]
All config variables were not at some point supported for the creators to use. Variables like these are generally here so that the current renpy can execute older games, but features we support in retro-compatibility mode are usually incompatible with other more recent features ([image manipulators](https://www.renpy.org/dev-doc/html/im.html) are an example).
Unless there's a very particular use case, it's unlikely for us to start supporting this.

**Comment by HorBro38** [comment]
Being able to change the  default image directory (or add additional) was all I was looking to do; and doesn't seem like it would be too crazy to have as an option.

**Comment by renpytom** [comment]
This went away with the introduction of renpy.list_files(). Once you have that, and renpy.image(), you can define images in any way you'd like.

**Comment by HorBro38** [comment]
I was able to find a work around by poking around 00images - I have a new init that adjusts the directory and tells it to do the late scan as such (and runs just after the regular scan at init time 0):

`init 10 python:
    config.images_directory = 'characters'
    config.late_images_scan = True`

Got where I needed to go, appreciate it!  Making config.images_directory something definable in gui.rpy or options.rpy may be something to look into; but that's up to you.

**Comment by renpytom** [comment]
I'm going to keep config.automatic_images undocumented. 

If you don't want to use the automatic image definition, Python is the way to go. It is way more customizeable then you can get with config variables, so I don't see any point in adding additional config variables to support this use case.
