### ISSUE TITLE
Android project customization

### ISSUE THREAD

**Issue by valery-iwanofu** [renpy/renpy#3882]
Adding new features from android API or custom android libs is possible, but it may cause compability issues. 
I wonder how to change some templates and prototype files (**templates/app-build.gradle**, PythonSDLActivity.java in particular) and still avoid issues.

An solution to modify **PythonSDLActivity.java** could be provide API to handle some events such as *onCreate*, *onDestroy*, etc.
But with gradle files it more complicated, (gradle.properties in particular). The solution in this case might be to allow user to provide some code parts wich will include later in these files by template engine.

**Comment by renpytom** [comment]
I think I don't want to touch this. 

We already have the update_always key in in android.json, which prevents those files from being regenerated, that's the escape valve for people who want customized android projects - it's then up to them, rather than Ren'Py, to figure out how to merge their changes and the changes from a new Ren'Py version.
