### ISSUE TITLE
Unable to use `lambda` inside list comprehension (using `sorted()`)

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#3887]
Hi,
Using `lambda arg: ...` inside list comprehension throws a NameError with the lambda argument not being defined.

Test Script:
```py
init python:
    class Test:
        def call(self):
            test_dict = {
                "key1": renpy.random.randint(0, 100),
                "key2": renpy.random.randint(0, 100),
                "key3": renpy.random.randint(0, 100),
            }

            return [k for k, v in sorted(reputation_dict.items(), key=lambda item: item[0], reverse=True)]

default test = Test()
```

Then simply use `test.call()` inside the script and it will throw the following:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script
    $ test.call()
  File "game/script.rpy", line 13, in <module>
    $ test.call()
  File "game/test.rpy", line 10, in call
    return [k for k, v in sorted(reputation_dict.items(), key=lambda random_arg: random_arg[0], reverse=True)]
NameError: name 'random_arg' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script
    $ test.call()
  File "D:\renpy-8-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8-sdk\renpy\python.py", line 1052, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 13, in <module>
    $ test.call()
  File "game/test.rpy", line 10, in call
    return [k for k, v in sorted(reputation_dict.items(), key=lambda random_arg: random_arg[0], reverse=True)]
NameError: name 'random_arg' is not defined

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.2.22081402
The Question 7.0
Sun Aug 21 10:07:35 2022
```

Using RenPy Version: 8.0.2.22081402 (Latest Stable)

Hope this can be fixed, saves having to write verbose dedicated functions

**Comment by KiloOscarSix** [comment]
I'm aware the error log doesn't exactly match up with the test script. I was confirming the name `item` wasn't the issue.

**Comment by Gouvernathor** [comment]
Renpy doesn't look involved anywhere in this bug. By itself your code doesn't work because we don't have the necessary values used in the code, but try it in a native python environment and see what it does. You probably just need parentheses around that lambda.
Also I don't inderstand why `sorted(reputation_dict, reverse=True)` woudn't work in your case.

**Comment by KiloOscarSix** [comment]
Change "reputation_dict" to "test_dict" to replicate. 

Lambda works correctly in native python. Lambda doesn't work inside parentheses. The function works if lambda is extracted out into a named function. 

I'll try the alternative sort later today, basically this specific use case is to return a list of keys sorted by their values. 

However I'm more concerned about the wider implications

**Comment by Gouvernathor** [comment]
You're right, that's a real bug.
The thing is, we're already using AST node replacements for comprehensions, to add lambdas inside them. This is surely a side-effect of that AST magic.

**Comment by Gouvernathor** [comment]
I got it ! That's because our renpy.python.find_loaded_variables flags `item` as a variable to be loaded from the external context, when it's not.
This is mainly because we didn't account for the use of lambda inside a comprehension expression, and that's because it's usually useless to do so.
We will probably fix this at some point, but I wouldn't say it's a high priority. Your code can be simplified to a single call of sorted(), and I don't think there's a lot of use-cases for this kind of thing.
