### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by NoiGS2015** [renpy/renpy#3894]
Hey there!

There's a bug that me and xavimat discovered with the translation function

Let's say you have this in the original rpy:
```py
label start:
  e "Hey! how are you!"
  f "Good! I was way to my work"
  e "Oh, then we can talk later"
  f "Ok, see you!"
  e "See you!"
  return
```

And then I do the translation and fill it up.
```py
# game/script.rpy:1
translate spanish start_1:
  # e "Hey! how are you!"
  e "¡Hola! ¿Cómo estás?
#Let's say everything else is translated
```

If I want to use the "id" function because I changed anything in the original code, and use the same id tag on 2 different parts of the main script, it will jump to the duplicated tag skipping all the code in between, like this:

```py
label start:
  e "Hey Francis! how are you!" id start_1 #This will be translated, but it will jump---
  f "Good! I was way to my work"
  e "Oh, then we can talk later"
  f "Ok, see you Eileen!" id start_1 #---here
  e "See you!"
  return
```

And that happen in the translation and the main language. I made the mistake accidentally pasting the wrong id tag.
Could it be added to the errors traceback screen when renpy detects it?

**Comment by Gouvernathor** [comment]
That's basically not a good use of the `id` feature, if I understand what you did correctly. You're not supposed to choose the id to attribute to a given dialogue line. You're supposed to copy the one naturally generated in the translation file (which will be a different one for each dialogue line), paste it in the main dialogue file, and then change the original and translated lines.
So, either you did a wrong copypaste, or you used it incorrectly, but to my limited understanding that's not a bug inside renpy.

That being said, adding guards and defensive measures against that kind of problem is conceivable. What you're asking for is for renpy to spot dialogue lines with the same id, and raise an error then, is that it ?
I'll try to do that in lint first, because iirc there's no exception raised from that problem and therefore no traceback, and we'll see how to possibly port that check outside of lint, into the normal boot process.

**Comment by NoiGS2015** [comment]
> That's basically not a good use of the `id` feature, if I understand what you did correctly. You're not supposed to choose the id to attribute to a given dialogue line. You're supposed to copy the one naturally generated in the translation file (which will be a different one for each dialogue line), paste it in the main dialogue file, and then change the original and translated lines. 

Yup, that's what I'm talking about, that I made was just a made up example to be more understandable

> So, either you did a wrong copypaste, or you used it incorrectly, but to my limited understanding that's not a bug inside renpy.

Yes, I messed up with the copypaste XD.

> That being said, adding guards and defensive measures against that kind of problem is conceivable. But considering such duplicates are already flagged and raise an exception when renpy tries to boot, I don't understand what you're proposing, and what information you would see added to that traceback ?

Because that's what happened to me, and renpy didn't noticed or made any notifications, It literally went from the point the id tag supposed to work and jumped where the duplicate was (Which I didn't noticed). I thought It was a weird problem of the program, but thanks to someone that noticed it, we found out about it. And as I say, that thing affects not only tha translation but the main language too. And that's why I think it should be showed in this error screen (That I don't know the name, sorry)
![Captura de pantalla 2022-08-23 092214](https://user-images.githubusercontent.com/74834511/186169175-44fb7302-4655-4de9-85bf-92cf0c863001.png)
(Obviously that's an example, but the thing is it didn't detected the duplicated id tag)

**Comment by Gouvernathor** [comment]
We changed some things in how the dialogue line identifiers are generated, to avoid some cases where a duplicate could be generated, but I'm not sure how it would change what happened to you. Please try this again in tomorrow's nightly. And before trying, change one character or two in the rpy files to make sure they are re-parsed.
