### ISSUE TITLE
Getting a 'Cannot pickle' error in Renpy 8.0

### ISSUE THREAD

**Issue by clowns234** [renpy/renpy#3905]
My code works with Renpy 7, but does not work with Renpy 8.  If I try to save the game while in Renpy 8, it crashes (see traceback.txt).  Trying to load saves made in Renpy 7 from within Renpy 8 also crashes the game.
The problem seems to be with the following:
```
label dataFill:
    python:
        fDat = fPath + 'img.dat'
        A = ['black.webp']
        with renpy.file(fDat) as f:
            e = f.read().splitlines()
        for g in e:
            g = g.decode()
            A.append(g)
```
FYI - fPath is set to 'images/S000/'
[img.txt](https://github.com/renpy/renpy/files/9428702/img.txt)
[traceback.txt](https://github.com/renpy/renpy/files/9428703/traceback.txt)

The file is 'img.dat' but in order to get github to accept it, I changed it to img.txt'.

**Comment by Gouvernathor** [comment]
Please use triple-backquotes (\`\`\`) for formatting and indent your code for readability.
The problem is that you're leaking `f`, the file object. According to [this example](https://docs.python.org/3/library/pickle.html#handling-stateful-objects) in the python doc, it seems to be expected. But as far as my tests went, I didn't see any difference between renpy 7 and renpy 8.
Anyway, the reason why this works in renpy 7 could be investigated, but the solution for you is probably to use `python hide` with a `store.A = A`, or at the very least a `del f` at the end of your python block.

**Comment by clowns234** [comment]
Thank you.   The following works.
```
label dataFill:
    python:
        fDat = fPath + 'img.dat'
        A = ['black.webp']
        with renpy.file(fDat) as f:
            e = f.read().splitlines()
        for g in e:
            g = g.decode()
            A.append(g)
	del f
```

**Comment by Andykl** [comment]
You could also use
```py
label dataFill:
    $A = ['black.webp']
    python hide:
        fDat = fPath + 'img.dat'
        with renpy.file(fDat) as f:
            e = f.read().splitlines()

        for g in e:
            g = g.decode()
            A.append(g)
```
This way you also do not leak `fDat`, `e` and `g`.
