### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by clowns234** [renpy/renpy#3952]
My goal is to create and add an *.rpa file for the new content - to avoid people from having to re-download the whole game.
I tried adding this to the options.rpy:
```
    build.archive("S28", "all")
    build.classify('game/S28/**.webp', 'S28')
    build.classify('game/S28/**.jpg', 'S28')
    build.classify('game/scripts/FS/S2800.rpy', 'S28')
    build.classify('game/scripts/S28/S2800.rpyc', 'S28')
```
Then moving the new S28.rpa file into the existing game folder but I get the following:
I'm sorry, but an uncaught exception occurred.

Before loading the script.
ValueError: unsupported pickle protocol: 5

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 427, in main
    renpy.loader.index_archives()
  File "renpy/loader.py", line 244, in index_archives
    index = handler.read_index(f)
  File "renpy/loader.py", line 129, in read_index
    index = loads(zlib.decompress(infile.read()))
ValueError: unsupported pickle protocol: 5

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
 
Tue Sep  6 18:31:43 2022

**Comment by Gouvernathor** [comment]
This doesn't work because, and correct me if I'm wrong, you generated the .rpa in renpy 8 and tried to load it in a 7.4 existing game.
I'm not sure how much dropping new rpas in existing games is supported, but mixing a _future_ rpa with a _previous_ game is probably even less so.

With that being said, It appears that [the archiver](https://github.com/renpy/renpy/blob/master/launcher/game/archiver.rpy), due to some 3-year-old code, uses the highest protocol available, and that is different between versions of python (= between renpy7 and renpy8). I'm not sure that's a good idea, it probably should use the constant protocol 2 which is compatible both ways.

**Comment by clowns234** [comment]
Thank you.

**Comment by Gouvernathor** [comment]
@renpytom maybe the archiver deserves some checking, to be sure. This could gratuitously prevent 8.0-distributed games to be launched from 7.5, in cases when it would have worked with a non-archived version of the game.
