### ISSUE TITLE
Predict `extend`

### ISSUE THREAD

**Issue by methanoliver** [renpy/renpy#3963]
Assume we have a long paragraph of say statement, which we want to interrupt with a `show` statement and continue from the point of interruption. The canonical ways of dealing with this are the `extend` character, and the `{done}` tag introduced later.

* `extend` has an inherent problem: the first say statement only lays out part of the paragraph, so upon `extend` laying out the complete paragraph, if `layout` property for this text is `tex`, as is the default, chances are high that the paragraph will be laid out differently, which will look like lines jumping around for the user. This can be worked around by setting `layout "greedy"`, which looks considerably worse.
* `{done}` has a different inherent problem: It requires one to keep the same line in the text twice, which requires it to be *edited* twice in case of changes, translated twice, and is otherwise clunky and annoying.

But say statement already makes predictions about the future when it considers the CTC: it checks if there is a following `nvl clear`. Could it possibly predict an `extend` as well and lay out the full paragraph as it will be presented by `extend`?

**Comment by hsandt** [comment]
I just tried it, unfortunately the `scry` only works when there is no conditional at all. Even a simple flag with a clear default value causes the branch prediction to fail, apparently:

```python
    mc "When I joined this team, I really believed you were{nw} "
    if mc_invoked_moral_reason:
        extend "different."
    else:
        extend "among the best."
```

gives me a misalignment issue similar to [Extend text and centered justification](https://lemmasoft.renai.us/forums/viewtopic.php?t=22523) but vertically.

Demo: one line vertically centered...

<img width="1240" height="244" alt="Image" src="https://github.com/user-attachments/assets/832d56d2-4957-48ed-b5e4-9df3065f2b33" />

extend occurs: shift up to vertically align the two lines!

<img width="1240" height="248" alt="Image" src="https://github.com/user-attachments/assets/d89dbb8b-3347-47d7-a1cd-72193de2d04c" />
<img width="1242" height="246" alt="Image" src="https://github.com/user-attachments/assets/8ed89c6f-3ea5-4d65-99cc-74cfda4312ea" />

Tried again removing the condition (always `extend "among the best."`) => text starts aligned correctly, considering two lines.

For now I have to either duplicate the whole setence, inject a string variable to change the sentence end, or use `{nw}{done}` + `{fast}` as explained in the doc (https://www.renpy.org/doc/html/text.html#text-tag-done)

However, all these methods mess up word count (as counted by tools like https://kigyo.itch.io/renpy-word-counter) due to either string injection or word duplication (and the whole reason for me to use `extend` in the first place is to make word count easier).

**Comment by Andykl** [comment]
I think this can't be solved for general case. Predicting statically known extends is okay, because it solves majority of cases of initial problem, but for dynamic extends I think you should use documented workaround or add pass-like creator defined statement that sets `extend_text` on scry object by the rules you as creator defines. Simplest would be to statically set it to known longest extend that is possible, e.g.
```
    mc "When I joined this team, I really believed you were{nw} "
    extend_layout_hint "among the best."
    if mc_invoked_moral_reason:
        extend "different."
    else:
        extend "among the best."
```
