### ISSUE TITLE
Volume is not adjusted proportionally with Preferences().

### ISSUE THREAD

**Issue by Zateinik** [renpy/renpy#4040]
Volume is not adjusted proportionally with Preferences().
It can be seen with this code:
```
init -1 python:
    def volume(v):
        _preferences.set_volume("music", v)

screen volume(): 
    vbox:
        label _("MUSIC")

        textbutton "10% volume" action Function(volume, 0.1)

        hbox:
            bar value Preference("music volume")
            label f"{int(_preferences.get_volume('music')*100.0)}%"
```

10 percent on the bar is not equal to the setting _preferences.set_volume('music', 0.1).

**Comment by Gouvernathor** [comment]
`_preferences` is not documented, and should not be accessed except from the readonly `_preferences.language`.
If you're talking about the 7.6/8.1 prerelease, the behavior is intentional, volume is now adjusted in a logarithmic fashion. You can see more details [here](https://github.com/renpy/renpy/blob/master/sphinx/source/changelog.rst).

**Comment by Andykl** [comment]
@Gouvernathor You are right and wrong. `_preferences` is private, but `preferences` is not (and is pretty the same thing). And you could use [preferences.get_volume](https://renpy.org/doc/html/preferences.html?highlight=preferences#preferences.get_volume). So it is technically a regression.

**Comment by Gouvernathor** [comment]
In that case I think there's two possibilities. Either we consider this a documentation question, and the functions access the raw value and the Preference Action/Value accesses the transformed dB value, or we patch each documented getter/setter of the mixers so that there's only one value to access.
I'm leaning towards the second option.

**Comment by Gouvernathor** [comment]
I talked too quickly ! The preferences.set/get_volume functions are actually undocumented now, and replaced with the get/set_mixer which set and get the value in a format consistent with Preference. See the difference between [the nightly doc](https://github.com/renpy/renpy/blob/master/sphinx/source/preferences.rst) and [the old doc](https://renpy.org/doc/html/preferences.html#mixer-functions).
