### ISSUE TITLE
In web builds, main menu music doesn't start properly with the loop option

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#4113]
I export the same code on PC, Mac, Android and Web.

`define config.main_menu_music = [ "<loop 117.296>/audio/music/bop_song.ogg" ]
`

This bit works as intended in all builds except Web, where it starts directly at loop point instead of starting at 0s. The loop itself works alright though.

I tried a workaround by queuing the same track like this:

`define config.main_menu_music = [ "/audio/music/bop_song.ogg", "<loop 117.296>/audio/music/bop_song.ogg" ]
`

However, after the loop of the "second" track is over, it goes back to playing the first track from the beginning, which isn't what I want.

Is there a workaround or a way to fix this the way the web builds start looped music?

**Comment by Kassy2048** [comment]
One workaround is to make sure your audio file is part of "game.zip" (see instructions in "progressive_download.txt" for that). Otherwise, the first time renpy tries to play the file, it fails to queue it from the start as the file needs to be downloaded, so it plays a silence audio file instead. When the file has been downloaded, it is queued as the continuation of a loop, so in effect, the first playback of the file is never done.

PR #4363 should fix that.

**Comment by renpytom** [comment]
@ZusYar I believe this was already done.

**Comment by Kassy2048** [comment]
Indeed, voice and music files miss are handled [the same way](https://github.com/renpy/renpy/blob/5c0f86c19e1ccb018c53f555da4bf71808f1e245/renpy/audio/audio.py#L77), but the way `renpy.webloader` handles voice and music files is different, so that might be the difference that @ZusYar sees, as using their change will actually load voice files as music files.

**Comment by renpytom** [comment]
@Kassy2048 Is there anything left to do here?

**Comment by Kassy2048** [comment]
I was only suggesting a possible reason for @ZusYar comment, but I can't reproduce any issue with missed voice file on latest nightly. So no, I don't see anything else to do without more feedback.
