### ISSUE TITLE
A couple of issues when running renpy games in windowed mode, on Windows

### ISSUE THREAD

**Issue by WingFoxie** [renpy/renpy#4155]
(This issue is about renpy games running on Windows via the game's ".exe" file.)

Bug #1. Couldn't go to a maximized window from fullscreen.
How to reproduce: 
1. Open a Renpy game, let's say that it's opened in windowed mode. 
2. Maximize the window. 
3. Press F, to enter fullscreen. And then press F again to exit fullscreen mode.

Expected behavior: 
Since I entered fullscreen mode **from a maximized window**, I should exit **to a maximized window**.
Actual behavior:
I always exit to a normal, not maximized window, no matter what.

Bug #2. Incorrectly positioned game window.
When the bug doesn't happen: 
Normally, game's window is correctly positioned in the center of the screen at launch. Can call the window "in the center", and the **upper-left corner** of the game window should be close the the monitor's actual **upper-left corner**.
When the bug happens: 
However, I can do the following steps:
1. Open a Renpy game and enter fullscreen.
2. Quit the game.
3. Open the game again. Since I quit the game in fullscreen mode, this time it will launch in fullscreen mode.
4. Press F to quit fullscreen mode.
5. Now you should see the game window positioned **incorrectly**. Now the **upper-left corner** of the window is at the **exact center** of the actual monitor.

Bug #3 Couldn't get a maximized window on launch.
I quit the game in **windowed** mode, it launched in **windowed** mode next time.
I quit the game in **fullscreen** mode, it launched in **fullscreen** mode next time.
However, when I quit the game on **maximized window**, and open the game again. I don't see the game open itself in maximized window. 
Therefore **there's no way for me to get the game to run in a maximized window on launch**. 
Consider this as a bug as well?
I can't be the only one that prefer to run renpy games in maximized window right?

Note: I don't use Linux. But maybe you want to test these things on Linux as well? 
Another note: I don't think it matters but I set my system DPI to 125%.

**Comment by xareyli** [comment]
On Arch Linux I only managed to reproduce 1and 3

**Comment by Org-gith** [comment]
Just wanted to share a pov about this... for point 1 and 3, that doesn't seem like a problem, it is a good default behavior given how options are kept simple by default for accessibility and you cannot choose precise resolutions in a default project. Maybe an option to remember last window size settings could be helpful and then a creator could do something with it if he wants...
But if returning to windowed mode load the previous settings, but not the default setting of the game, then a player could
never be able to return to native resolution of the project (the sharpest/best resolution for quality).

**Comment by WingFoxie** [comment]
You see, for points 1 and 3, all I ask is a basic feature that should be taken for granted for having it. 
It's like... cmon, this is a basic thing for windows apps. 

Except it quite isn't.
Tried a bunch of different apps, here are their behaviors.

|App|When maximize->enter fullscreen->exit fullscreen|When maximized->fullscreen->quit->launch again|When maximize->quit->launch again|
|-------|-------|-------|-------|
|Firefox|returns to maximized window|launches as maximized, not fullscreen|launches as maximized|
|VS Code|returns to maximized window|launches in windowed mode (in previously set window size)|launches as maximized|
|MS Word|can't fullscreen in the first place|can't fullscreen in the first place|launches as maximized|
|a Unity game|can't maximize in the first place|can't maximize in the first place|can't maximize in the first place|
|a Unreal game|returns to a floating window with maximized size (forget previously set window size)|it launches at full screen no matter what|it launches at full screen no matter what|
|a Nwjs game (idle game)|can't fullscreen|can't fullscreen|will launch maximized|
|another Nwjs game (RPG game)|can't fullscreen|can't fullscreen|will launch in windowed mode, reset to default window size and position, no matter what|

Seems that the actual situation is way more messy than I thought it is. 

(And another thing. You mentioned that players should be "able to return to the native/default resolution of the project (the sharpest/best resolution for quality)". I'm investigating this, will reply about this in another comment about an hour later.)

**Comment by WingFoxie** [comment]
Well, about that players should be "able to return to the native/default resolution of the project (the sharpest/best resolution for quality)". 

Currently, for a Renpy game, if you play the game in normal window mode,
then accidentally changed the window's size & location, 
after that:

|If you do this|This will happen|
|-----|-----|
|just quit->launch again|game will launch in your accidentally changed size & location, in windowed mode|
|maximize->quit->launch again|game will launch at default size & location, in windowed mode|
|go fullscreen->quit->launch again|game will launch fullscreen initially, but if you exit fullscreen, it remembers the accidentally changed window size, but forgets the location. And will incorrectly position the window according to Bug No.2.|

And if you ask me, these behaviors are more like a coincidence than intentionally implemented.
I mean, it remembers the window size while quit on fullscreen, but forgets it while quit on maximized??

....Oh and did I not mention my point 1 & 3 at all?
Because fixing those doesn't contradict the need you mentioned at all.

Just fiddle with your web browser's maximizing and fullscreen features, close and launch it again at different window states, and see if it's good to make Renpy games learn a thing or two from it.
(Then I realized even MS Edge and Firefox doesn't behave exactly the same. Sigh.)

My suggestion: 
If "reset to default" window size is that important, should implement it properly, a feature in a dev menu, accessibility menu or something. 
Don't just make it randomly forget the window size & position some time. 
And remember whether the window is maximized or not before entering fullscreen, to determine what happens when exiting fullscreen.

(Hope this clarifies thing good enough, this is actually my 3rd draft, and the first 2 drafts are longer than this.)

**Comment by renpytom** [comment]
Reset to default is already there - you get it by clicking Windowed. 

The first and third issues above make sense. I'm not sure if I'll do the second - there are limits to how much I want Ren'Py to override the position the system gives its windows, and I need to look at what SDL decides and make a decision.

**Comment by Org-gith** [comment]
Sorry insomnia here, it's exactly what I was pointing out in my initial post, nothing else really. Windowed button (or pressing F again) to exit fullscreen mode should reset default window size of ren'py, I think it's a good behaviour. I was under the impression he wanted to change it so that this button return to previous windows setting used (so basically you could lock youself in a way where you would never be able to return to native windows size).

**Comment by Booplicate** [comment]
> Windowed button (or pressing F again) to exit fullscreen mode should reset default window size

I don't believe that window mode should somehow affect window size, it's unintuitive.

**Comment by Org-gith** [comment]
It's not that important, but if you have a system with only two buttons on/off, it seems logical to me that the off button should set the basic default resolution. First of all, we're almost all in 2D, so being able to return your project to the basic resolution is really important for working, and then for users who understand 2D and the notion of dpi, it's important to be able to return to the basic resolution to have the image in its original quality. Imagine you're working on your project or playing, you distort your Ren'py window without doing it on purpose (and the Ren'py window adds black bars on the side, so it doesn't scale well), and then good luck going back to your native reso by hand if the buttons/shortcuts have been changed to apply your new setting. I get that Tom wants to keep that behavior intact, but then I'm not sure what would be the change then, and in that case, if it's just a small thing that doesn't change that, it would be probably a positive change so I'm not worried.
Ideally, I think that integrating a default reso picker like all the jap VNs do would be the right move, and then you develop the thing so that it remembers by default everything you've done to the window, and everything would work fine. But if you stay basic on the default project, which is also acceptable, this kind of functionality of keeping the user profile in memory could cause replace old annoyances with new annoyances that are not as easily adjustable. That's why Rpgmaker and I'm sure many other 2D engines, have the same basic implementation as Ren'py and focus on 2D, there is this reset behavior at each startup. Potentially adding next to the windowed mode button in the default project Ren'py, a button like "Remember the last setting" on/off, would be a good compromise though but not something applied by default imo.
As for problem number 2, it bothers me a lot because I have no way to adjust it, and when you do a resolution picker, every time you change reso the window gets lost and sometimes it can get pretty bad, because it recalculates incorrectly the place where it starts to enlarge/shrink and not on the basis of the new reso but on the very first. This is a real bug, and it doesn't only affect a reso picker if this user could trigger it.
