### ISSUE TITLE
ATL transitions persisting through interactions

### ISSUE THREAD

**Issue by morganwillcock** [renpy/renpy#4167]
It appears ATL-based transitions are persisting through interactions and do not behave in the same way as non-ATL transitions.

Given this transform:
```renpy
## This is the example from the documentation:
## https://www.renpy.org/doc/html/atl.html#atl-transitions
transform spin(duration=1.0, new_widget=None, old_widget=None):

    # Set how long this transform will take to complete.
    delay duration

    # Center it.
    xcenter 0.5
    ycenter 0.5

    # Spin the old displayable.
    old_widget
    events False
    rotate 0.0
    easeout (duration / 2) rotate 360.0

    # Spin the new displayable.
    new_widget
    events True
    easein (duration / 2) rotate 720.0
```

When specifying to show a different screen with the `With` Action the transition will repeat on every interaction inside the shown screen:

```renpy
screen screen1():
    textbutton "Show 'screen2'":
        action [With(spin), Show("screen2")]

screen screen2():
    default data = 0

    ## Every click of this button will trigger the transition.
    textbutton "Set":
        align (0.5, 0.5)
        action SetScreenVariable("data", 1)

label start:
    call screen screen1
```

Replacing the `spin` transition with `fade` will only show the transition once:

```renpy
screen screen1():
    textbutton "Show 'screen2'":
        action [With(fade), Show("screen2")]

screen screen2():
    default data = 0

    ## Clicking this button will not trigger the transition.
    textbutton "Set":
        align (0.5, 0.5)
        action SetScreenVariable("data", 1)

label start:
    call screen screen1
```

P.S. I am opening this on behalf of someone else who does not have a GitHub account. They encountered this problem when trying to show the preferences screen.

**Comment by shawna-p** [comment]
I'd also like to add to this that AlphaDissolve transforms do not reset under certain circumstances. For example, add the following to The Question (tested on the March 9 Nightly):

```renpy
transform transition_keyhole_in(multiple=2, child=None):
    contains:
        child
        align (0.5, 0.5) fit "cover"
        xysize (0, 0)
        ease 2.5 xysize (int(config.screen_width*multiple), int(config.screen_height*multiple))
    contains:
        Solid("#000")
        alpha 0.0
        pause 1.2
        easeout 1.3 alpha 1.0
define test_transition_in = AlphaDissolve(At('gui/window_icon.png', transition_keyhole_in), delay=2.5)
label start:
    scene black
    "Game start"
    scene bg lecturehall
    with test_transition_in
   "Roll back from here."
```
If you roll back and forth over the transition, it does not update, which means eventually it just instantly flips to the new scene and waits 2.5 seconds before showing the dialogue.

This can be solved by changing the AlphaDissolve to 

```renpy
image in_img = At('gui/window_icon.png', transition_keyhole_in)
define test_transition_in = AlphaDissolve("in_img", delay=2.5)
```

aka declaring the image beforehand, rather than including its definition inside the AlphaDissolve. 

Needless to say, this is very unintuitive and at the very least merits a warning that directly including ATL transforms in the AlphaDissolve definition will cause them to not update.
