### ISSUE TITLE
renpy.render breaks time (sometimes)

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4168]
When using the following code and reaching the second pause, it behaves as intended. The right animation goes black then white and stays white. However, when reloading the game (from the *second* pause, not the first, otherwise the show statements are re-executed), the right animation is just plain and unmoving black, instead of staying white.

What's more, when readding the commented-out line (which shouldn't change anything), the behavior becomes erratic. Even before a reload, the right animation just continues playing instead of stopping at white, and its blinking becomes somewhat random : you'll see it dissociate with the left one, sometimes changing too soon.
```rpy
image animated:
    xysize (500, 500)
    "#000"
    1
    "#fff"
    1
    repeat

label glitch:
    scene
    show animated at glit, right
    show animated as a2 at left
    pause
    pause

init python:
    class glit(renpy.Displayable):
        def __init__(self, child):
            super().__init__()
            self.child = renpy.displayable(child)

        def render(self, width, height, st, at):
            # renpy.render(self.child, width, height, st, at)
            return renpy.render(self.child, width, height, min(1.5, st), min(1.5, at))

        def visit(self):
            return [self.child]
```
The use case is using a cdd as a transform, which [currently works very well](https://github.com/Gouvernathor/renpy-ChromaGlitch) except when transforming animations. For these purposes I need to render the original child or transforms wrapping it several times, and then these bugs happen.

**Comment by renpytom** [comment]
This is related to an issue that we discussed recently. 

Fundamentally, transforms and ATL have the assumption that time advances linearly. When you break that, you cause problems - like the one here. 

There's also  the decision that when a transform is accessed through an image reference, like animated is being here, it will be reset when the game is reloaded. That's why the transform on the right always starts at black, rather than starting at white 50% of the time. 

So what's happening is that after a reload, the transform on the left is being reset. It sees the first time given to it as 1.5, so it takes 1.5 as the time base - that then gets subtracted from st (which is also 1.5), and so the time for that transform will always be 0 - hence the displayable stays black. 

I'm going to close this, as this is Ren'Py working as designed. I might revisit some of these behaviors as part of a larger ATL redesign, but the redesign is going to be major. (And probably it will be done in conjunction with a redesign of how state in displayables works. To give an idea of what makes this complicated - take a transform that has a hover event come in at time 2.0. What state should it be rendered in at time 1.0? It's not clear that there is a good way to eliminate the monotonic time assumption - or that we should even try.)
