### ISSUE TITLE
Persistent improvements (and fixes)

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4196]
There are several things I'd want to address with Persistent.

- [ ] Entries set to None. The fact that persistent attributes default to None is definitely a feature, but it also means the None value kinda has a special meaning when stored in persistent. If we can provide a way to know whether an attribute has been manually set to None, or not set yet, without breaking any existing behavior, I think that can be useful. I propose a new `_keys` method to return them as a list (or tuple or iterator), and the `"key" in persistent` syntax using a `__contains__` method.
- [ ] Entries starting with `__`. They have two problems : renpy's name-mangling mechanism, which is hard to find in the doc and (I think) not much known about, and the fact that the `_clear` method doesn't do its job by forgetting to delete them. I propose fixing the _clear method so it deletes exactly the entries visible in the persistent devtool, or documenting that _clear doesn't act on these attributes (but I fail to see how that would be a feature). And a general explanation of these attributes in the persistent section would not hurt.

**Comment by Gouvernathor** [comment]
Actually the problem is more complex. Entries starting with "__" will actually not start with "__" after the name-mangling takes place. They will always start with "_filename" - or actually "_m1_filename" - which means testing for a double underscore, either in _clear or in the persistent devtool, will never find a match.
After the name-mangling takes place, and for code written in .py files or accessing the `__dict__`, __-starting names are indifferenciable from internal, _-starting names.

**Comment by mal** [comment]
On the latter task, first point - no observable name mangling seems to occur when using persistent to store attributes with a leading double underscore. A value written into `persistent.__foo` is readable in the same way, and is also how it is listed in the devtools, all of which seems pretty reasonable. The second point regarding `_clear` would break existing functionality which, while undocumented, does have valid use-cases, and the value to changing that behaviour wouldn't seem to offset its loss.

On the first task, it would be helpful to have a real use-case as justification for the additional complexity within the `persistent` namespace. In terms of actual use (i.e. reading the value) then whether the `None` was explicit or not is fairly moot, and edge cases that need a way to disambiguate already have the option of setting a non-`None` default that they can choose to recognise as meaning "unset", which would seem like a reasonable solution to such a scenario. Currently I'm struggling to see the problem you're seeking to solve. :/

**Comment by Gouvernathor** [comment]
I suggest doing tests in a dummy project, because the situation is complex. Typing `persistent.__a = 5` in the console sets the "__a" key in the persistent's dict, and it will appear that way in the devtool.
But that's only because the console isn't a file. If you do `default persistent.__a = 5` in script.py, the "_m1_script__a" will be set instead, inducing the cascade of consequences I described, including them not appearing in either of our versions of the devtool. And I believe `$ persistent.__a = 5` in a label will do the same - but if it doesn't, it means the feature is _completely_ broken, so it's worse.
Anyway, I'm rolling back any change to _clear and folding back to document that __-starting fields are not affected.

**Comment by renpytom** [comment]
I do object to adding ``__contains__`` - it feels weird to ask an object if it contains a field using the ``in`` syntax. That's because in usually means a value is inside an object - but here, you're asking if the value is one of the fields in the object. And that doesn't seem right to me. 

I'd be find to add a _has() method to persistent, though I'm also skeptical that it will ever be used. 

Outside of the persistent debugger, there really shouldn't be much of a need to iterate over persistent.

**Comment by Gouvernathor** [comment]
The idea is to mirror the way a mapping works, and specifically a defaultdict or one having the `__missing__` method : `d[key]` returns the default value whether the key was set or not, but `key in d` still enables testing if the key is defined or not. The keys method was also a mirror to mappings, but I agree it's a superfluous feature and I dropped it.

The rationale is that if you want a field to be treated differently if it has been set or not set, then you have to never use the None value since it's used as the default value. If you use functions to set persistent values, you also need to ensure none of them return None by mistake. You can always use False or a sentinel object, those are valid solutions but have other drawbacks - breaking your habits and not living well with other systems using None.
This syntax to differenciate set and not set keys, without ever having to always worry if that value might be set to None.
I agree the need for this doesn't often occur, but having a very simple way to solve it without changing established features, raising exceptions or inspecting the `__dict__` manually, I think it's a good thing.

**Comment by renpytom** [comment]
The thing is, persistent is not a mapping. It's a namespace. I don't want it to have one method of a mapping, since that would imply it's a mapping. But it's not. It would be weird to have ``in`` work on persistent, but ``len`` not work. 

Really, the only case where this would be useful would be a field where None is a value, but not the default value for that field. That strikes me as both a really weird use case, and one that the default statement already naturally handles for the creator. 

> The rationale is that if you want a field to be treated differently if it has been set or not set, then you have to never use the None value since it's used as the default value. 

That's an incomplete rationale. You'd have to explain why you think treating a field differently if it has been set or not set is something that would be useful for people making games with Ren'Py. The rational has to come from the position of someone making games in Ren'Py, not from the perspective of an engine or Python developer.
