### ISSUE TITLE
Allow get character name on Callbacks

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4248]
I don't know if there is a way to do this, but if there isn't I guess I could propose it as an idea. This would be profitable if it is necessary to check inside the callback the name of the character. For example, if a character is speaking and not the narrator character.

ex: 
```
def Speakers(event, interact=True,character_name, **kwargs):
      global Fumiko_speaking

      if not interact:
            return

      if character_name == "Fumiko":
        
            if event == "show_done":
                  Fumiko_speaking = True
            elif event == "slow_done":
                  Fumiko_speaking = False
            else:
                  Fumiko_speaking = False


Character(
    "Fumiko",
    callback=Speakers
)
```

**Comment by MiiNiPaa** [comment]
You can access `store._last_say_who` or you can simply pass name at character creation:
```
init python:
    def Speakers(event, interact=True,character_name=None, **kwargs):
        if character_name == "Fumiko":
            raise Exception("Everything works fine " + character_name)
        else:
            raise Exception("Nothing works properly " + character_name)

    speakers = renpy.curry(Speakers)

    
define f = Character(
    "Fumiko",
    callback=speakers(character_name="Fumiko")
)

label start:
    "test"
    f "you should not see this"
    return

```

**Comment by Gouvernathor** [comment]
Yes, the solution would be to pass a character-specific callback to the Character, either by making a class whose instances are callable, or by using [functools.partial](https://docs.python.org/3/library/functools.html#functools.partial) in a comparable way.
Keep in mind that neither _last_say_who nor renpy.curry are documented.

**Comment by renpytom** [comment]
It probably makes sense to document renpy.partial and renpy.curry. 

I'm sympathetic to the idea of somehow making information about the speaking character available during dialogue, but there are at least some issues with this. The big one that I see is that right now, there isn't a great way to refer to the character. There is:

* The Character object. But there are a bunch of cases where new Character objects can be created,  and object identity can cause problems after a save/load cycle. 
* _last_say_who. This text containing a Python expression, which doesn't feel right. 
* The image tag and voice tag don't really feel like they're meant for this. 

What I'm sort of thinking could work would be to have a `callback_tag` parameter to Character, that would be passed to the character callback, if set.

I'm also thinking it might make sense to have a new parameter to Character, `tag`, that if present sets the `image_tag`, `voice_tag`, and `callback_tag` to the same value. 

What does everyone think?

**Comment by Gouvernathor** [comment]
I think that would help in cases when the character callbacks would get **one string** as a differenciating factor between different behaviors. Which feels too specific : there are character callbacks that are the same for any character (any they're applied to, anyway), and there are character callbacks needing several informations (speed of the talking bleeps and bleep sound to use), or one not in the form of a string (speed of bleep, again).
I get the grouping with the other two tags makes sense arguments-wise and can simplify things a bit, but while image tags are strings per definition and voice tags are interpolated as part of filenames, callback parameters have no particular reason to be strings. And it optimizes cases when characters having the same callback specifiers will also have the same image and voice tags, which again seems oddly specific.

We could then turn `callback_tag` into `callback_args` or something, but I think we should rather normalize making parametered callbacks, be it with functools, renpy.curry or a custom class. An example in the doc would be enough, in the like of what @MiiNiPaa wrote. It would enable more creativity for creators, not be any harder to understand in my opinion, and cost us no supplementary implementation or support.
#3989 can be used as a base to document renpy.curry but as stated there I don't think there's a reason for creators to prefer that to functools.

**Comment by mal** [comment]
While I understand why `renpy.curry` exists internally, I'm sceptical about it being a good idea to promote it as a partial factory. For anyone not familiar it needs head-scratching that feels like it would be much better put towards `functools.partial` which, as noted already, doesn't seem to have any draw back over use of `renpy.partial`. It's also more readable as it's very clear a partial is being created, compared to a curried function with an arbitrary name. Without a strong distinguishing factor in favour of the currently undocumented Ren'Py functions, I think I'd also favour documentation/examples of how to achieve this type of thing with `functools` over expanding the public API in that area.

---

I don't think I like `callback_tag` because it establishes a precedence for passing callback values through as parameters, and since it could be anything, the first thing people will be tempted to do in a pinch is consciously misuse it to push multiple arguments through in a tuple or other data structure, which doesn't feel good. It also opens the door for similar requests in other callback areas. Ultimately I think use of `partial` is the better, more generic solution. It's a little more involved but also sets creators up better for similar scenarios elsewhere.

The bar for this _could_ be lowered with something such as the function below, but it really feels like the sort of thing at creators should either customise for themselves, or find examples tailored to their scenario.

```py
def NamedCallbackCharacter(name, *args, callback=None, **kwargs):
    if callback:
        callback = functools.partial(callback, speaker=name)

    return Character(name, *args, callback=callback, **kwargs)
```

---

Without `callback_tag`, I think the need for `tag` is substantially diminished, but also have no strong objection to it.

**Comment by Neyunse** [comment]
> It probably makes sense to document renpy.partial and renpy.curry.
> 
> I'm sympathetic to the idea of somehow making information about the speaking character available during dialogue, but there are at least some issues with this. The big one that I see is that right now, there isn't a great way to refer to the character. There is:
> 
>     * The Character object. But there are a bunch of cases where new Character objects can be created,  and object identity can cause problems after a save/load cycle.
> 
>     * _last_say_who. This text containing a Python expression, which doesn't feel right.
> 
>     * The image tag and voice tag don't really feel like they're meant for this.
> 
> 
> What I'm sort of thinking could work would be to have a `callback_tag` parameter to Character, that would be passed to the character callback, if set.
> 
> I'm also thinking it might make sense to have a new parameter to Character, `tag`, that if present sets the `image_tag`, `voice_tag`, and `callback_tag` to the same value.
> 
> What does everyone think?

Well, I don't object.
