### ISSUE TITLE
yuv420 webms are not filtered

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#4263]
Seems like Ren'Py decodes webm files without filtering them, resulting in pixelation (very noticeable with yuv422 and yuv420).

WebM:
![image](https://user-images.githubusercontent.com/46109734/213585148-92d3def6-6271-4312-886a-76a5c1d81a41.png)
PNG:
![image](https://user-images.githubusercontent.com/46109734/213585580-d7107f48-1aa6-4eae-aa4a-9c4e813659ae.png)

The only solution is to use yuv444 instead, but Ren'Py takes a lot more time to decode it, which results in a noticeable delay.

<details>
<summary>Test File</summary>
The browser player handles this well..

[anim_yuv_4m.webm](https://user-images.githubusercontent.com/46109734/213585235-02c343a0-c9d4-4a5b-9cc7-2e2e775946e4.webm)
</details>
<details>
<summary>Test File Game Screenshot:</summary>

![screenshot0004](https://user-images.githubusercontent.com/46109734/213586676-90ccf662-ae05-4e59-a0b7-143fc35e89ad.png)
</details>

P.S. Maybe there are any ways to implement a WebM prediction system like with images?

**Comment by renpytom** [comment]
Can you download ffmpeg, and see how ffplay does it?  Ren'Py's decoder should be mostly just ffplay.

**Comment by via-my** [comment]
Not sure if I did it correct but I dragged and dropped the webm file on the ffmpeg/bin/ffplay.exe.
For me it looks good.

<details>
  <summary>Screenshot from ffplay</summary>

![image](https://user-images.githubusercontent.com/46109734/213588891-8553ce0a-65f1-4f80-9963-7d58ac1ffa18.png)
</details>

**Comment by renpytom** [comment]
I think I just fixed this. I'm not great at seeing the differences here, so if you could download the March 12 nightly and check that this is fixed, I'd appreciate it.

**Comment by suphamster** [comment]
Btw, why not use SWS_BICUBIC then since according most of tests it's better than SWS_BILINEAR?

**Comment by renpytom** [comment]
The reason for SWS_BILINEAR is that it should be faster for videos that have 2x scaling.

**Comment by suphamster** [comment]
> The reason for SWS_BILINEAR is that it should be faster for videos that have 2x scaling.
It's about 10-15% slower but we now in 2023 year where already in Chrome browser implemented realtime super resolution upscaling using NV RTX GPU and we still using filters from maybe previous century here. Ideally will be good if user can choose upscale model in advanced settings (Shift+G) for example.
Btw I'm not expert but maybe we get not identical colors because used rgba instead yuv here [https://github.com/renpy/renpy/commit/44e23a9665843794bd050166539256910400e777](url) in get_pixel_format(rgba_surface).

**Comment by via-my** [comment]
I think nothing has changed.
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/46109734/224572287-943661f3-1b5b-426f-8775-212d9e0e12f2.png)
</details>

**Comment by suphamster** [comment]
New commit https://github.com/renpy/renpy/commit/a516bda70070e753b460c0638572f1aa66b4f4fd seems fixed pixelation. Colors still brighter than should be but I think I can live with that. Also thanks for adding bicubic filter (though not tested yet).

**Comment by via-my** [comment]
https://github.com/renpy/renpy/commit/a516bda70070e753b460c0638572f1aa66b4f4fd fixed pixelation, but significantly reduced the fps on big files to about 10.

**Comment by renpytom** [comment]
Okay, more work on this. Fundamentally, I don't think the problem is going to be solved without  a better way of converting from YUV to RGB than the swscale library can provide efficiently. I tried various ways of converting through yuv444, and the cure was worse than the disease - on my computer, decoding a 1280x720 frame went from 350ms to over 5000ms. 

There are some new options here, SWS_FULL_CHR_H_INP | SWS_FULL_CHR_H_INT, which do seem to improve things a little, turning the blocks from 4x2 to 2x2, if I'm looking at things right. (And I'm not sure I am after looking at this all night.) 

I've also gone ahead and changed the movie colorspace to itu709, which should increase the range of colors we can show. 

I've switched to SWS_POINT, as it's slightly faster when we're not scaling, and we're not scaling here.

At this point, I see it's not perfect, but I'm running out of ideas of things to change. I don't have a yuv library I can easily swap in. So at this point, unless there's some major quality loss (due to the color space thing), this is what we're going to release 8.1 with, unless we have actionable ideas.

**Comment by suphamster** [comment]
So for now we went back to pixelation problem (actually it seems quite rare anyway coz there shoud met conditions when red picture edges mets some other picture with different color) but at least colors now are almost perfect (similar as in browser or video player).
Btw since scaling was mentioned here I'm curious now where in RenPy code is handled video scaling method (bilinear as far I understand) then when user stretches game window from FullHD to 2k for example (or just go to full screen mode)?

**Comment by via-my** [comment]
It's nice that the colors are now perfect, but... now they don't match the color of sRGB images.
In my project I use like 200x300 WebM animations and place them on the scene images to make game more optimized. It was perfectly matching each other, but now WebMs look a little bit brighter and I can't find any solution to match them back. 

Before:
![2](https://user-images.githubusercontent.com/46109734/225485667-71122f98-074b-4197-91fc-d14e5d293ab6.png)

Rec. 709:
![1](https://user-images.githubusercontent.com/46109734/225485679-f5f5292f-3d0b-44e1-9762-4cd08cbc03b6.png)

Do we really need to switch to Rec. 709? It's the standard encoding color space for HDTV, but Ren'Py is about images, not Television.

**Comment by renpytom** [comment]
Hm... I'm trying something different, which is basically to use the full-range Rec. 601, so that what we produce should match what a jpeg is converted to.

**Comment by suphamster** [comment]
I just made a commit that tries to make the YUV->RGB conversion of movies match the way JPEGs are converted from YUV->RGB. So Rec. 601, but with the full colorspace rather than the limited TV colorspace.

Can you explain plz what we get after all changes before and after? Because l've compared results with attached in 1st post video and for me all is just the same (pixelated edges and colors outside RenPy don't match with tools like video players and browser), Rec. 709 commit gave almost perfectly matched colors and (sadly not added) SWS_ACCURATE_RND flag removes pixelation and even with sws_bicubic gives me 60 fps on heavy test videos. If jpegs convertions not mathes to videos maybe we should fix it but not video convertion. I'm speeking not from developer but player point of view since there are really sometimes you see when video colors don't much previous images (though sometimes this is could be game developers rendering issues).
![test3](https://user-images.githubusercontent.com/17669188/225938987-74d71f68-fa88-46d9-94c1-458249022c04.png)

**Comment by renpytom** [comment]
I was getting 5ms/frame for a 1280x720 video with SWS_ACCURATE_RND enabled on a YUV420 video. So it looked like it was too slow for actual use.
