### ISSUE TITLE
different width 'IDEOGRAPHIC SPACE' (U+3000)

### ISSUE THREAD

**Issue by Zateinik** [renpy/renpy#4275]
```
# normal width
"「……は？\u3000これが、一晩？」"

# width is smaller than it should be
"「……は？　これが、一晩？」"
```
The code below also does not change anything
```
def replace_text(s):
    s = s.replace("　", '\u3000') # idiographic space
    return s

config.replace_text = replace_text
```

**Comment by Zateinik** [comment]
if you just put a wide Japanese space '　' in the text, then its width will be equal to the usual space ' ', but if you enter the UTF code '\u3000' instead of the text, then the width will be as it should be

**Comment by Gouvernathor** [comment]
I may be wrong but I think that's because we collapse adjascent space(s) of a dialogue line into one normal space. This system probably applies to the large spaces you put in the script, and the unicode decoding apparently takes place afterwards so that space is left alone.
This has been here for a long time but I'm not sure it's really relevant, maybe we should remove it somehow.

**Comment by Gouvernathor** [comment]
This is the culprit line https://github.com/renpy/renpy/blob/3e0a84ee8c2b1016f310ff9696a21f91a58bb7fd/renpy/lexer.py#L895-L896
That, and the equivalent for triple-quoted strings is just further down.
As documented [here](https://nightly.renpy.org/doc/text.html#escape-characters), it replaces any contiguous sequence of whitespace character(s) with a single standard space.

I don't understand the rationale for this, so I'd be in favor of dropping it. Compating it would be tough, since it's at the parser level : we may make a `config.version`-dependant behavior (which it deserves, being a documented behavior), but having a dedicated config variable to toggle it seems like tough work ahead.

**Comment by Gouvernathor** [comment]
Anyway @Zateinik unless we change it, the documented solution is to backslash-protect each non-standard space.
So, `"「……は？\　これが、一晩？」"` (notice the backslash before the large space). That, or the unicode version with \u3000.

**Comment by Zateinik** [comment]
Unfortunately the backslash before a large space does not work.
Simple test:
```
label start:
    '|　|\　|\u3000|'
```
![test](https://user-images.githubusercontent.com/18444678/215838528-e312b55f-579b-4a68-9554-10d6a76c92c6.png)

**Comment by Gouvernathor** [comment]
You're right, I misread the code - though I think we should make that work. Until then, \u.
Maybe you can use some python code to convert your .rpy files from "\u3000" to "\\u3000", using str.replace or something like that, if you want to do it in bulk. Shift+Ctrl+H can also do that for you in most editors, replacing "　" with "\u3000" in that case.

**Comment by Zateinik** [comment]
Thank you, replacing one text with another is not a problem for me.
