### ISSUE TITLE
Cannot override color and what_color on say dialogue windows

### ISSUE THREAD

**Issue by StefanGagne** [renpy/renpy#4319]
I'm trying to add a color-blind friendly and high contrast mode to my game which overrides the defined Color and What_Color on each character. I've been able to override the color on nameboxes, but not on the dialogue itself.

I set up a preference called "interface" to let players toggle between color and mono...

In screens.rpy, this works for nameboxes:

```
            window:
                id "namebox"
                style "namebox"
                text who:
                  if (renpy.get_style_preference("interface") == "mono"):
                    style "say_label"
                    color "#ffffff"
                  else:
                    id "who"
```

However, the same concept applied to "text what" results in a non-Text element being returned and renpy crashing:

```
        text what:
          if (renpy.get_style_preference("interface") == "mono"):
            style "say_dialogue"
            color "#ffffff"
          else:
            id "what"
```

People on the discord recommended I file this as a bug.

**Comment by Gouvernathor** [comment]
First, it's probably worth noting that renpy has a builtin accessibility option for high contrast. It's accessed by pressing A in the game.

Now, [this section](https://nightly.renpy.org/doc/screen_special.html#say) describes the "what"-id'd element as mandatory inside the say screen, for normal function of the say statement. So, a bug when you don't declare one is normal behavior, and this would be a wontfix/work-as-intended in my view.

From there I think there are two things you can do. One, fix what you were doing and strip the `id "what"` from the screen, but at the same time add a second text with `id "what"` and `at Transform(alpha=.0)`, so that it's there for the engine to access it but people don't see it. You could even manage not to break too much things in the say behavior.
The better way would probably be not to do that, and to take advantage of the say_arguments_callback, assuming it's called for each dialogue line, or to use a wrapper function to declare characters. For example:
```rpy
init python:
    def chara_wrapper(cha, *args, **kwargs):
        if (accessibility trigger condition):
            kwargs["what_color"] = "#fff"
        return cha(*args, **kwargs)

    import functools

define e = functools.partial(chara_wrapper, Character("Eileen", ...))
```

**Comment by shawna-p** [comment]
@Gouvernathor I think the issue that I see is less Ren'Py requiring `id "what"` to function, and more that style properties directly applied in the screen do nothing when the who/what ids are present. For example, I would expect the following to override the provided `color` argument to my character's name:

```renpy
text who id "who":
    if persistent.no_colored_names:
        color "#fff"
```

As the engine currently is, this does absolutely nothing and does not modify the colour of the name. There's an obvious argument for having the `id "who"` override the default name text styles, if provided, but I think directly applied properties in screens should take precedence over the provided `who_` styles.

**Comment by Gouvernathor** [comment]
That's a feature. Things you pass to Character (or as say arguments) are overrides over the normal behavior, and the screen is the baseline over which these overrides apply.
That's how it's meant to work, for example the `screen` or `who_style` arguments to Character don't make any sense if the screen's contents were to have higher priority.

**Comment by shawna-p** [comment]
I think there's a misunderstanding, I am proposing the current priority order be:
style properties applied directly to the element on the screen > who_args to the Character > the say_label style

Currently the priority is who_args to the Character > the say_label style and style properties applied directly to the element on the screen do nothing at all.

**Comment by JSearUK** [comment]
I'm with Fen: local overrides should trump passed-in overrides, just as inline styling overrides the end result of hierarchical styling. The developer is saying, "Ah, ty, you've followed Health & Safety guidelines and brought the correct products, tools and signage for this spill on the floor here. Now, ignore that, and go outside, because I'm currently running a fire drill."

**Comment by Gouvernathor** [comment]
> who_args to the Character > the say_label style and style properties applied directly to the element on the screen do nothing at all

That's not what I'm seeing. From the default gui, adding `color "#0f0"` to the `text who` line sets the color to green regardless of what you set it to in the say_label style, so that means the hierarchy is `Character(who_*) > style props in the screen > say_label style`, as it's meant to. The screen sets the baseline, overriding styles using style properties, and the Character args override the baseline.

I understand what you're proposing.
The in-screen style properties overriding what the style provides is how the screens work in renpy, so regardless of design and purpose considerations, it would require breaking many things in order to put something (what the Character says) in between.
How would it make sense that a creator would set specific customizations for a series of different characters, if they're all thrown out when setting a property in the say screen ? A general rule is that the specifics override the general. Ignoring customizations and applying a blanket uniform layout is a very uncommon thing to do - even in this example, it only makes sense because it's conditional.
Having Character set overrides over the say screen is a long-standing feature, relied upon by lots of existing games and used by many creators. I don't see a point in breaking it.

@JSearUK "local overrides should trump passed-in overrides" how are things set on the say screen, applying to all dialogue (by default), more local than things set on a per-character basis ? What sense would there be in having a per-character customization if it's overridden by all-dialogues properties ?

**Comment by JSearUK** [comment]
@Gouvernathor People *generally* shouldn't be locally overriding in that screen, for exactly the reasons you've offered; it nullifies a large amount of effort and setup elsewhere. Nevertheless, if someone does want to do precisely that, whatever their reasons - in this case, a plausibly useful one, offering more flexibility than the Accessibility screen offers - it should work in the same way that it works everywhere else.

**Comment by renpytom** [comment]
I've added a new screen language property, `prefer_screen_to_id`, that controls whether the properties in the screen should be preferred to those coming in through the id. That would make the first example:

```renpy
            window:
                id "namebox"
                style "namebox"
                text who:
                  id "who"
                  prefer_screen_to_id True
                  if renpy.get_style_preference("interface") == "mono":
                    style "say_label"
                    color "#ffffff"
```

**Comment by mal** [comment]
Why not just define `Character`s without the overrides? 😕

**Comment by renpytom** [comment]
> Why not just define `Character`s without the overrides? 

Since the start of Ren'Py:

```renpy
define e = Character("Eileen", color="#c8ffc8")
```

Has been a thing. I don't think that it makes a lot of sense to say, "but don't do that if you want accessibility".

**Comment by renpytom** [comment]
I'm going to close this, as I believe the new property resolves the underlying concern.
