### ISSUE TITLE
ctc_timedpause=Null() does not work with fixed CTCs and custom ctc screen

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#4365]
Same exact issue as #3774, but with ctc="fixed" and using the following screen:
```
screen ctc(arg=None):
    if preferences.clicktocontinue and not renpy.is_skipping() and not main_menu:
        add "ctc" xpos int(1490*(gui.dialogue_width/1070)) ypos 0.9
    else:
        add Null()
```

My characters are defined with `ctc="ctc", ctc_pause="ctc", ctc_timedpause=Null(), ctc_position="fixed"`.

`(ctc="ctc", ctc_pause=None, ctc_timedpause=None, ctc_position="fixed"` also does not work)

Currently, the CTC icon flickers in for 0.3 seconds before disappearing again, which is very unpleasant to look at. The desired behavior is that the icon is only shown when the player actually needs to click ({w} or end of line).

**Comment by renpytom** [comment]
I'm unable to reproduce the problem, at least with a corrected ctc screen. Specifically, a screne like:

```renpy
screen ctc(arg):
        add arg
```

Works correctly. I'll note that by using ``add "ctc"``, you're always using the CTC indicator, and never the Null displayable.

If that's not the problem, please put together a minimal replication and reopen this issue - I'm somewhat guessing as to what your problem is. (It doesn't seem related to #3774, as far as I can tell.)

**Comment by kigyo** [comment]
Oh, I see. Thank you for the correction!

In that case, maybe a different example in the [documentation](https://www.renpy.org/doc/html/screen_special.html?#ctc-click-to-continue) would be better? Because the current one does not make use of `arg `in the screen:
```
screen ctc(arg=None):

    zorder 100

    text _("Click to Continue"):
        size 12
        xalign 0.98
        yalign 0.98
```
