### ISSUE TITLE
Sound clips and images are slow to load with the web build

### ISSUE THREAD

**Issue by AndreaBrg** [renpy/renpy#4383]
Hi everyone, I'm trying to deploy my project on a web server, but unfortunately, whenever I play the images, and especially the sounds take a while to fully load.
The images appear blocky for around half a second, and the sounds play only if I replay the scene in which it should trigger.

Does anyone know the causes of this unexpected behavior? I am using Ren'Py 7.5.3

**Comment by renpytom** [comment]
You need to make sure the game can predict the images. Chances are, you also need a faster internet connection or web server.

**Comment by AndreaBrg** [comment]
@renpytom Thanks for the reply. What do you mean by `You need to make sure the game can predict the images`?

**Comment by Kassy2048** [comment]
For audio clips, they should play without having to replay the scene with the upcoming version of Ren'Py since PR #4363 has been merged. You can check it by using a nightly build [here](https://nightly.renpy.org/current-8/index.html).

Also, remember that images have to be downloaded before they are shown, so make sure their byte size is not too big to reduce the time it takes to download them (using higher compression ratio and/or reducing their resolution). Screen prediction is supposed to download them in advance, but it might requires some hints depending on how you show them (see [here](https://www.renpy.org/doc/html/screen_optimization.html#prediction)).

**Comment by AndreaBrg** [comment]
@Kassy2048 it seems like the nightly build did the work. Thanks for the tip.
