### ISSUE TITLE
How does screen variable scoping work?

### ISSUE THREAD

**Issue by graterleg1990** [renpy/renpy#4389]
Hi Guys,

I have been having this type of issue for quite some time now.
Whenever I use a variable as underlined in the 1st attached image it sometimes works and sometimes doesn't. 
The variable themselves are declared globally, can anyone let me know why it doesn't work sometimes? 
I tried setting the variable "b_Debris_Scan_Done" from the screen and also from script.rpy but and the state of the variable is correct when i check it in the console but the screen just doesn't update.
Am I doing something wrong here?
Also I tried changing the code to eval() 2nd image, it works in that case. 
![image](https://user-images.githubusercontent.com/122201140/220902209-939b3e09-096b-426e-88e1-082b06d7a720.png)
![image](https://user-images.githubusercontent.com/122201140/220902042-9dde5ac8-7d88-48f3-a60f-ef7e9e719177.png)

**Comment by Gouvernathor** [comment]
#4385 could help you, could you look into that and see if it solves your problem ?
If not, can you desceibe what exactly happens when you say it "doesn't work" : does it throw an error, or does the if behave like you didn't expect it to ?

**Comment by graterleg1990** [comment]
> #4385 could help you, could you look into that and see if it solves your problem ? If not, can you desceibe what exactly happens when you say it "doesn't work" : does it throw an error, or does the if behave like you didn't expect it to ?

Hi, There is no error thrown, but the buttons within the condition are not visible, in the below snippet if I replace eval("b_ActiveDebris") with  b_ActiveDebris the button no longer is visible, renpy doesn't see the updated variable value. however **b_Debris_2_Pulled** works without being eval(), I hope you're getting my point, it's just so confusing and unpredictable. When does it work and when it doesn't I cannot tell anymore.
![image](https://user-images.githubusercontent.com/122201140/221180006-488d9033-656c-4093-87b1-983c26f627f0.png)

**Comment by Kthunda** [comment]
From what I understood while coding :

When you show a screen, renpy wait for an interaction.
It'll not update the value of global variables in the screen until this interaction.

 That's why eval() works and not calling the variable itself. The game has updated the value of the global variable, but the screen hasn't.
 
 If you want it to work by calling variables themselves, you'll have to add renpy.restart_interaction after your SetVariable function.
 
 This is my thoughts about how the game works, so I'm not sure this is the truth, but considering my testing, it is^^

**Comment by mal** [comment]
You're using the `define` statement to initialise `b_Debris_Scan_Done` (rather than `default`), which means it's treated as a constant value by the prediction system, so the value is being cached and reused even after you've changed it. This is intended and [documented](https://www.renpy.org/doc/html/python.html#define-statement).

> Variables that are defined using the define statement are treated as constant, are not saved or loaded, and should not be changed.

I'd suggest updating your code to use the `default` keyword for values you expect to change and see if that solves the problem. i.e.
```rpy
default b_Debris_Scan_Done = False
```

**Comment by graterleg1990** [comment]
> 

Hmmmm.I have been using define for a very very long time. trust me when I say "renpy saves and the loads the changes done to define variables"
Also as I already pointed out `define b_Debris_2_Pulled = False` still works, don't you think it's an inconsistency?  It should either work every time or not, but that's not what's happening in my scripts

**Comment by MiiNiPaa** [comment]
Welcome to the world of undefined behavior. 
The way of Python is to not prevent you from doing something you are not supposed to do, but if you do that, no guarantees, you are on your own.

Some parts of RenPy will treat `define`d variables as constant and will cache their value, if this helps optimisations, other won't, because there is no need to. As long as you will adhere to the "do not change those variables", the behavior will be consistent. If not: read above.

Same with saving: if reference itself is changed, that varaible will be picked by RenPy saving mechanism, otherwise, if only an object it refers to was changed, it wouldn't. At least this is how it works now. In the future this might change and then you are on your own again, because you are not supposed to change those objects in the first place.

**Comment by Gouvernathor** [comment]
Exactly. Undefined/undocumented behavior can and will be inconsistent. But we don't care about that, because it's undocumented. If you want to go that way, you're on your own.
In this instance, the caching of defined constants saves time and improves performance for everyone who follow the rules, so making your screen work would hammer that optimization down for everyone else.

**Comment by graterleg1990** [comment]
> Exactly. Undefined/undocumented behavior can and will be inconsistent. But we don't care about that, because it's undocumented. If you want to go that way, you're on your own. In this instance, the caching of defined constants saves time and improves performance for everyone who follow the rules, so making your screen work would hammer that optimization down for everyone else.

Yea, either way define and default are very ambiguous, especially if you are working with multiple languages. As a c# and c++ developer to me defines sounds like "declare the variable" and default sounds like "declare a constant" it might be just me.
Would it hurt to update the doc's , **"The define statement sets a single variable to a value at init time, usually used for data which do not change after defined"**, I know it's there in the last line but who reads doc's last line?
