### ISSUE TITLE
Drag method set_child() doesn't update its child

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#4432]
Related forum entry here: https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=66246

When using set_child() on a Drag as part of a _dragged or _dropped events/functions, nothing happens. Also the function doesn't accept a single string as a "simple displayable".

The code seems fishy:

```
def set_child(self, d):
        """
        :doc: drag_drop method
        Changes the child of this drag to `d`.
        """

        d.per_interact()
        self.child = renpy.easy.displayable(d)
        renpy.display.render.invalidate(self)
```

1. per_interact() is called at an argument (is that correct?)
2. if the argument is a string like "eileen", it's crashing of course
**3. the child is not changed inside the game**

**Comment by ticlock** [comment]
In addition to the above:
The render method use `self.style.child` if `child` property was provided with drag. Method set_child() sets `self.child`.

As a result, the displayable can't be changed with `set_child()` method if `child` property was provided with drag.

**Example:**
The following won't change the displayable of the drag when dropped:
```
def detective_dragged(drags, drop):
    ...
    if drop: 
        drags[0].snap(drop.x,drop.y)
        d = renpy.displayable("ivy_dropped.png")
        drags[0].set_child(d)
```
```
drag:
    child "ivy.png"
    dragged detective_dragged
```
However, for example, using `add` statement instead of `child` property will change the displayable of the drag when dropped:
```
drag:
    add "ivy.png"
    dragged detective_dragged
```

**Comment by renpytom** [comment]
Fixed, both the method and the documentation.

**Comment by m-from-space** [comment]
Thanks for fixing it that fast!

Two things though:

1. You made a small typo in the documentation on line 96 (`ad "ivy.png"` instead of `add "ivy.png"`)
2. What do you mean by `show the use of add rather than child, as the style property is for specialized use`? What specialized use? And how is "child" a style property?
