### ISSUE TITLE
Side image sometimes stay visible when no one speaking

### ISSUE THREAD

**Issue by valery-iwanofu** [renpy/renpy#4438]
[Video demonstrating the bug](https://user-images.githubusercontent.com/82092794/224922612-50a21697-97c5-441c-90a0-3eb98f16d4ef.webm)
This bug is rarely appears and i assumed that it was prediction problem.
I think these lines of code could be an issue.:
https://github.com/renpy/renpy/blob/bb2b1bc23a56e484c961fd60a3adc304ca6aef0d/renpy/character.py#L1403-L1405

Some modification like this could be solve the problem:
```python
        attrs = ...
        ...
        renpy.store._side_image_attributes = attrs
        ...
        finally:
            if attrs is renpy.store._side_image_attributes:
                renpy.store._side_image_attributes = old_side_image_attributes
                self.restore_say_attributes(True, old_attr_state, True)
```

But I haven't dug very deep, so I don't know for sure what the problem is.

**Comment by Gouvernathor** [comment]
I don't think the proposed solution would be very safe - considering the at-all existence of the present one. The function called in the `try` clause is `self.do_predict`, which calls `self.predict_function`, which is set by the constructor to be just any callable.

The only such callable to be passed in the base code is `renpy.exports.predict_show_display_say`, but the fact that it's passed this way implies just any pickled Character instance could have a reference to just any function writing just about anything in the global _side_image_attributes variable.
Maybe I'm being paranoid though, after all the `predict_function` parameter is not documented. But the fact that I don't understand why it's built that way makes me careful.

In any case, I think the problem is probably more deep and this would only monkeypatch it.
A more consistent reproducing context would probably help.

**Comment by valery-iwanofu** [comment]
I tried to reproduce the bug in a "stable manner" and maybe i succeeded. My first guess about the prediction was wrong or maybe it's another bug or maybe it's a correct behaviour. 
The code to reproduce described situation:
```renpy
image bg ext_beach_day = '#d8d8d8'
image bg ext_boathouse_day = '#4d4d4d'

image side dv_ava = Solid('#e60000', xsize=200, ysize=200)
image side un_ava = Solid('#810081', xsize=200, ysize=200)

define dv = Character(_('Alice'), image='dv_ava')
define un = Character(_('Lena'), image='un_ava')

label start:
    $ renpy.watch('_side_image_attributes')
    scene bg ext_beach_day with dissolve
    menu:
        dv 'Hi'
        'Hello':
            dv '123' nointeract # this line of code cause the problem
            un 'Hello'
            jump label1
        '...':
            dv '...'
            un '...'
            jump label2

label label1:
    scene bg ext_beach_day with dissolve
    dv 'Hello.'
    scene bg ext_boathouse_day with dissolve
    pause 1
    scene bg ext_beach_day with dissolve
    pause 1

    return

label label2:
    play music 'audio/a_promise_from_distant_days.ogg'
    scene bg ext_boathouse_day with dissolve
    un 'Line 1.'
    scene bg ext_beach_day with dissolve
    dv 'Line 6.'
    dv 'Line 7.'
    return
```
Sorry for the extra code, but I'm not sure if the bug will reproduce without it.

[Demo with reproduce](https://user-images.githubusercontent.com/82092794/225199520-8f4fe94c-de89-4cc2-a8d5-52eabfff5674.webm)

**Comment by renpytom** [comment]
With the replication, it was possible to track this down. Thanks for putting it together.
