### ISSUE TITLE
xysize property doesn't work on ATL images using contains

### ISSUE THREAD

**Issue by DipeshAggarwal** [renpy/renpy#4467]
Ren'Py version: 8.0.3

When an image is composited using ATL `contain` property, the `xysize` property will have no impact but the depracated `maxsize` property will work.

Code to test out the bug.

```python
image test_image:
    contains:
        "path to image"

# Doesn't work, even adding fit "contains" doesn't work
screen test_1():
    add "test_image" xysize (100, 100)

# Works
screen test_2():
    add "test_image" maxsize (100, 100)

# This also does not work
screen test_3():
    frame:
        xysize (200, 200)
        padding (0, 0, 0, 0)
        background None
        
        add "test_image" maxsize (200, 200)
```

**Comment by DipeshAggarwal** [comment]
Okay. Thanls. Closing this then.

**Comment by Gouvernathor** [comment]
I'm still somewhat surprised that maxsize works and not the other.
Is it because `maxsize` worked by zooming the whole Fixed after the children have been rendered, while `xysize` triggers at the start of the rendering process and then gets ignored by the children (which have fixed size because they're images) ?
