### ISSUE TITLE
`camera` statement doesn't seem to find variables

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#4532]
```
label _eyes(duration, closing, wait):
    if wait:
        window hide

    camera master:
        ease_quad duration blur (10.0 if closing else 0.0)

    if renpy.showing("black"):
        show black:
            ease_quad duration alpha (1.0 if closing else 0.0)
    else:
        show black:
            alpha (0.0 if closing else 1.0)
            ease_quad duration alpha (1.0 if closing else 0.0)

    if wait:
        pause duration
        window auto
    return

label open_eyes(duration=1.0, wait=False):
    call _eyes(duration, False, wait)
    return

label close_eyes(duration=1.0, wait=False):
    call _eyes(duration, True, wait)
    return

label main_menu:
    return

define config.gl2 = True
define config.developer = True

label start:
    scene
    "..."
    call close_eyes()
    "..."
```
doesn't work. commentating the `camera` statement makes it work.

tested on 8.1.23040901+nightly

**Comment by renpytom** [comment]
Not a bug, or not really.

The issue here is that camera master is evaluated on every frame. At least right now, you can't do an animation like this in the camera, and expect it to work - it will repeat every interaction. What's more, the master transform is evaluated during each frame, and it keeps getting evaluated after _eyes returns. Hence the crash. 

You can get rid of the crash by putting "camera master" at the end of _eyes, to remove the camera transform you just added. That will prevent it from being invoked after _eyes returns.
