### ISSUE TITLE
While using Skip the sprites won't move

### ISSUE THREAD

**Issue by kodukass** [renpy/renpy#4533]
When i go through the game normally then the move actions work fine, but if I use Skip then the move action doesn't work, leaving the character hanging in weird places/not putting them in their right position. Could this be fixed some how?

Here's a video of the bug: 

https://user-images.githubusercontent.com/99496596/232038743-4037fde2-0495-4547-acd7-a6f94b785ede.mp4

Here's the resporitory: https://github.com/kodukass/movingFailingWhileSkipping.git

The main problems of the code (but they could be because of other things in the project so I have the full thing in the repository):
`//--------file: part1.rpy---------------//

//----this one is always broken--------//
#robin slides in front of jack
show r_vhappy at robin with move:
    xalign 0.3
    linear 0.2 xpos 0.2
hide r idle

u "Hi! You finaly woke up!"
show j uncomf
hide r_vhappy
show r happy_speak at robinmove1
u "...Oh!"
#robin backs up a bit
show r happy_speak :
    xalign -0.0005
    linear 0.2 xpos 0.2
u "Sorry!"

//------------file: part2.rpy----------------//

show j idle at left with dissolve //--this one is fine--//
show r idle at robin with dissolve //--this one is broken--//`

**Comment by mal** [comment]
```
loputoo test2/game/conf.rpy:15:     $ robin = Position(xpos=0.74, ypos=1.1, xanchor=1.0, yanchor=1.0)
```

You're making use of the deprecated `Position` in your code, rather than the newer `Transform` which should be much more reliable in this regard. The good news is that looking at the `Position` usage you have in `conf.rpy`, you can probably just swap out `Position` for `Transform` and not even change any of the arguments. I'd suggest giving that a go and then seeing if you still have a problem.

**Comment by kodukass** [comment]
I did and it worked! Thank you so much!!!! :D
