### ISSUE TITLE
`fadeout` fade music faster on 7.6.0 Prelease than 7.5.3

### ISSUE THREAD

**Issue by brainos233** [renpy/renpy#4580]
```renpy
stop music fadeout 20
```
On 7.5.3, this will slowly fade out the currently playing music, but on 7.6.0 pre, I notice the volume will obviously fade in few seconds.

The same thing also happened in:

```renpy
play music "music_name" fadeout 20
```

Is this relating to using decibels in 7.6.0?

**Comment by Gouvernathor** [comment]
Yes it is, the decreasing gurve of the volume is much straighter now and should be linear to your ears, where it used to start very slow (for fadeouts) or come in quickly and take some time to settle (for fadeins).

**Comment by Org-gith** [comment]
I think the change is good and makes sense, it's really something that didn't seem right. 
Hmm, still, I wonder if it's possible to get a configuration for this because, for example, I had found a set of "correct" values to solve this problem with the previous faulty fadeout/fadein. The project took three years to get to this point and a lot of testing on the audio side to make sure everything was fine, almost every sound/music had custom fadeout and fadein, so replacing all the fadeout/fadein used is going to take a lot of time to make sure they work well with the new method. 
I just wonder if it would be easy enough to have a config for that, I'm a little taken aback because that makes it a top priority and something you have to fix as soon as you move to 7.6 without having the option to use the old method for a little while longer and decide when to switch to it, and the config would allow testing the before and after, nicely. 
Otherwise, it's not very important anyway since switching to this new method should be better on the long run but if it's easy enough, could be a cool thing.

**Comment by renpytom** [comment]
I added config.linear_fades to enable the old mode, mostly for people like @Org-gith, who have games that depend on the old behavior. (I think the old behavior is strictly inferior to the new one in the actual behavior.)
