### ISSUE TITLE
Dismissing the choice menu

### ISSUE THREAD

**Issue by ZusYar** [renpy/renpy#4619]
So here's a question. 
I can't find a way to close the choice screen without choosing an item, like, emulating the 'choice not taken' situation.
It seems to always return "2" (from ui.interact maybe?) and execute the 2nd menu block nevertheless

any workaround or is it a potential bug?

```
screen sch(items):
    vbox:
        for i in items:
            textbutton i.caption action i.action
    key 'game_menu' action Return(None)
    
default test_value = 0

label start:

    "[test_value]"
    
    menu(screen='sch'):
        "option 1":
           $ test_value = 1
        "option 2":
           $ test_value = 2
        "option 3":
           $ test_value = 3
        "option 4":
           $ test_value = 4
        "option 5":
           $ test_value = 5

    "[test_value]" # always prints out 2, and i'd like the flag unaffected
    return
```

**Comment by Kassy2048** [comment]
I don't know if this is a bug, but one solution is to add a hidden choice as the last choice, and use it when user aborts:
```rpy
screen sch(items):
    vbox:
        for i in items[:-1]:
            textbutton i.caption action i.action
    key 'game_menu' action items[-1].action
    
default test_value = 0

label test_menu:

    "[test_value]"
    
    menu(screen='sch'):
        "option 1":
           $ test_value = 1
        "option 2":
           $ test_value = 2
        "option 3":
           $ test_value = 3
        "option 4":
           $ test_value = 4
        "option 5":
           $ test_value = 5
        "default":
           # Last choice is when user aborts
           $ None

    "[test_value]"
    return
```

**Comment by Gouvernathor** [comment]
`menu` is a statement that takes several blocks, and calls a screen to ask the player what block to take. If you return something different (= use an action that was not passed through the `items` parameter), how could it work properly ?
The menu statement has some rigidity for good reasons. Finding and fighting every way the creator can mess it up is not very tenable as a programming practice on our end since it would slow things down for everyone at execution time.
If anything, the only thing to do on our end about this would be to lock the process down even more and make your `Return(None)` raise an exception when used in the menu, if that's cheap enough computation-wise.

The solution, I think, would be to add the supplementary option like @Kassy2048 did on the script side, while [passing an argument](https://www.renpy.org/doc/html/menus.html#menu-arguments) to that option to tell the screen to skip it. Inside the screen's for loop, when that parameter is found, you don't show the textbutton and put your `key` instead, with the same action.
Or you can have the convention of passing that fallback always-first or always-last, and have your for loop on `items[:-1]` or `items[1:]`.
And the "do nothing" action in renpy is `pass`, not `$ None` (it's cheaper, and it works in Python too).

**Comment by renpytom** [comment]
You can also Jump out of the choice menu, using the Jump action.

**Comment by MiiNiPaa** [comment]
While internally menu uses value of None to indicate no selected choice (because all of them were unavaliable, for example), `Return(None)` doesn't work, because, as defined in documentation, it returns non-None value. If you attempt to return None, it returns True instead, which is then converted to 1 and 2nd block is executed (as they are 0-indexed).
