### ISSUE TITLE
Keyboard Focus issue with buttons that overlap slightly

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#4620]
Buttons that overlap even slightly (typical if you're using drop shadows, etc) causes the focus system to skip them when using keyboard navigation (usually every other button).  I've seen this myself when a slight -5 spacing from buttons that look like this:

<img width="400" alt="Screenshot_2023-05-10_at_4 00 16_PM" src="https://github.com/renpy/renpy/assets/109490566/aeae2aee-8183-49bf-b20c-10cd8c9d0462">

Attempting to use the keyboard here causes it to skip every other button despite visually there being no apparent reason why.  If the focus was based off center of buttons this would be a non issue, but I'm not sure what unintended consequences this would have.

**Comment by renpytom** [comment]
I'll say this is a low-priority issue, since it's something that can be avoided with the design of the buttons. Just looking at those, it seems like there is plenty of space between each button - it's not clear why you have a spacing -5 in there in the first place. 

Centroids wouldn't work, but it might make sense to have focus insets from each side (such that a 5px inset would treat (100, 100, 100, 100) as if it was (105, 105, 90, 90) for focus purposes.

**Comment by HorBro38** [comment]
Sorry, that was just a quick example I threw together.  The issue was initially brought up due to a more severe overlap caused by a "hand full of cards" effect:

![image](https://github.com/renpy/renpy/assets/109490566/1d096525-02c0-4a09-b368-0f15c834abd3)

**Comment by renpytom** [comment]
I don't think Ren'Py is going to be able to resolve that level of overlap automatically, though insets still seem worth doing.

**Comment by HorBro38** [comment]
> I don't think Ren'Py is going to be able to resolve that level of overlap automatically, though insets still seem worth doing.

Oh, I agree.  More of a feature request than anything, but being able to modify the 'focus area' for focus would be very helpful.

**Comment by KiloOscarSix** [comment]
An alternative idea was brought up in the renpy channel:
Allow devs to define the order in which their objects should be selected, i.e: `focus_order (0, 0)`
Then if a user presses the right key, it will look for `(1, 0)`

You'd need to throw an exception if 2 objects share the same "focus_order"

I'm also not sold on the name, "focus_order", Seronis has suggest `focus_pos` or `fpos`

**Comment by Booplicate** [comment]
Imo something like this could be done easier in CDD where you can process keyboard (and other) events yourself.

**Comment by ncthbrt** [comment]
> I don't think Ren'Py is going to be able to resolve that level of overlap automatically, though insets still seem worth doing.

I wish I understood the algorithm behind how this all worked. Because my intuition says that despite the overlap, if you place an Axis Aligned Bounding Box around these cards, it'd in theory still be possible to have a well behaved total ordering as they don't completely overlap. However this is a comment made in ignorance of the renpy implementation and constraints

**Comment by ncthbrt** [comment]
We ended up intercepting the focus keys and computing the centroids for one screen and applying an index for the other screens. It worked but was hard to find information about this approach
