### ISSUE TITLE
How can I make the renpy.pause(3, hard) function skippable by adding a skip button?

### ISSUE THREAD

**Issue by xyzsarkanyagyu** [renpy/renpy#4652]
Or anything else to achieve a similar result.

**Comment by Gouvernathor** [comment]
Hard pauses are something we barely support, because of user-unfriendliness.

What I would think of, is to do `call screen hardpauser(3)`, where hardpauser is a modal screen containing 1) a "skip" button or imagebutton (however you want to style it) with the Return action, and 2) a timer with the duration passed by parameter to the screen and also with action Return.

**Comment by xyzsarkanyagyu** [comment]
Thank you, this works and is a good alternative.
I'll leave this here in case someone is looking for a solution.

screen hardpauser(duration):
    modal True

    # Define the "skip" button.
    textbutton _("Skip") action Return()

    # Define the timer.
    timer duration action Return()

    default time_left = duration

    text "[time_left]" size 30  align .05, .0078
    
    if time_left <= 0:
        timer 1 action Return() # Whatever action you want to happen when timer runs out!
    else:
        timer 1 repeat True action SetScreenVariable("time_left", time_left-1)
    
    textbutton " ":
        action SetScreenVariable('time_left', time_left-1)
