### ISSUE TITLE
[8.1.x] When updating to version 8.1.x, the date of the save file will be reset.

### ISSUE THREAD

**Issue by stunnings** [renpy/renpy#4736]
When running the game after updating Ren'Py to version 8.1.x, the save files' dates will be reset to the time of the initial execution of the game with 8.1.x.

To easily reproduce this, you can create a new game using the previous version of Ren'Py, save it, then update Ren'Py and run the newly created game again.

**Comment by Gouvernathor** [comment]
That's because of the save security added in version 8.1, where when the game is updated and allocated a security token, that token is added to all the existing saves.
I don't know if this transition could be mitigating by "faking" the date of last modification somehow. It depends on how it's stored and computed.
In any case it's only going to occur once in the lifetime of any game : you're going to upgrade from pre-8.1 to post-8.1 only one time.

**Comment by renpytom** [comment]
This is pretty clearly an issue, and something I'll address soon.
