### ISSUE TITLE
[Bug] 'No DC' in top-left corner of applications caused by RenPy

### ISSUE THREAD

**Issue by SanderBouwhuis** [renpy/renpy#4756]
When you view a VN with Renpy, Photoshop and some other programs will show 'No DC' in the top left corner. This is because Renpy overrides an Nvidia setting in a global profile (i.e., for EVERY application in the system!)

This can be fixed manually by deleting this file:
"C:\ProgramData\NVIDIA Corporation\Drs\nvdrssel.bin"

Please fix this! This bug has been in Renpy for yeaaaaaaars now.

![No DC bug](https://github.com/renpy/renpy/assets/10495173/9c33a0d3-2550-4b5e-ada7-6bd4913cebf1)

**Comment by renpytom** [comment]
This is a bug in the nvidia drivers. Please contact them and ask them to fix their software.

**Comment by SanderBouwhuis** [comment]
Renpy is literally the ONLY application I know who creates this problem. So every other application is 'lucky'? All other applications either have a workaround or don't have this bug. A DuckDuckGo search shows this problem has existed for MANY years now in Renpy.

Closing this issue without a fix is really incredibly unfriendly and unhelpful. Are you saying NONE of the Renpy developers can debug and fix this problem?!?

**Comment by renpytom** [comment]
We don't have the ability to fix the Nvidia drivers.

**Comment by jakishiro** [comment]
I think it's nvidia driver problem like tom said.
I just want to say that one thing that we can do to improve slightly this situation, even if we can't totally fix, would be to turn thread to disabled like we do when starting ren'py, but then not try to set it back to the original value.
Basically almost 99% of the things benefits from thread being disabled, this is almost the default for everything in Auto, the enabled option is barely used by some very specific applications and when it's used it doesn't do much.
However thread enabled turned to On does create a lot of issues if it's turned on and not set to auto, and this is what we set it to when ren'py try to turn it back to the original value after leaving. I know it's a problem from Nvidia, but maybe we should just let it to disabled to avoid complications (since we can't put it auto, but we will set it to On which creates lot of issues).
Not sure if makes sense. :s

**Comment by Kassy2048** [comment]
@SanderBouwhuis Did you check you have installed the latest version of the Nvidia driver? I remember having this "NO DC" in the past for weeks, but it disappeared after a driver update. My current version if 531.41 and the problem does not occur anymore (latest version is 536.23).

@renpytom The default restore value should probably be `OGL_THREAD_CONTROL_DEFAULT` instead of `OGL_THREAD_CONTROL_ENABLE` ([here](https://github.com/renpy/renpy-build/blob/ffb0081633dd14be9c93c1384483801417376227/nvlib/nvdrs.c#L93) and [here](https://github.com/renpy/renpy-build/blob/ffb0081633dd14be9c93c1384483801417376227/nvlib/nvdrs.c#L138)) because the global setting switches from the default "Auto" (before Ren'Py starts) to "Enabled" (after Ren'Py closes), and you don't want to enable threaded optimizations by default.
Also, I have the feeling the changes will probably only be applied when the application restarts anyway, no matter if you change the default profile or create a specific profile for Ren'Py. I found no way to confirm that though.

**Comment by Squall-Leonhart** [comment]
This is a bug in your RenPy, you alter the state of the threaded optimization setting and then never restore it.

Fix the issue on your end, like nvidia has already told you to.
