### ISSUE TITLE
Web export: Preferences > Display > Fullscreen behavior is erratic

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4760]
I know that Web is still in Beta but I'm posting this for tracking purpose:

In a web export embedded on a website, the window/fullscreen is erractic. Tested on Chrome on Linux Ubuntu 22.04 with Unity desktop.

- click on Preferences > Display > Fullscreen: game becomes bigger, but frame is still the same size, so game view is cropped

![Renpy 8 1 1 export web fullscreen erratic](https://github.com/renpy/renpy/assets/1067772/565fe122-2d32-4f6e-a655-a99771bbb145)

or

![Renpy 8 1 1 export web fullscreen erratic 2](https://github.com/renpy/renpy/assets/1067772/137423ba-c03c-4177-abd3-96b796e55a06)

- click again on the embedded window: this time, game refreshes and becomes truly fullscreen
- click on Preferences > Display > Window: game reverts to frame, at correct resolution
- ... but if you repeat the operation, game view may be offset relative to frame. This is mostly visible if you zoom out on the page (in fact, if you zoom out at any time, frame content may offset, although it may be a different issue)
- 
![Renpy 8 1 1 export web fullscreen erratic 3](https://github.com/renpy/renpy/assets/1067772/9052d95b-ab96-40fd-a170-ad317c05d125)

Note that adding a fullscreen button directly on the HTML template (what itch.io does, using an overlay) is better: it toggles fullscreen reliably in both directions.

**Comment by Kassy2048** [comment]
There seems to be 3 different display modes in Web: Window, Fullscreen and none of them (which is the default). That's probably the issue here.

About the fullscreen behavior, that's because [emscripten is too strict](https://github.com/emscripten-core/emscripten/blob/b8d09db82e9efa6af586091c9e943bb8d7896b61/src/library_html5.js#L1501) about when it can request fullscreen mode. In theory, fullscreen mode can be requested if the user [has recently interacted with the page](https://developer.mozilla.org/en-US/docs/Web/Security/User_activation#transient_activation). But emscripten only do that when the user is currently interacting with the page (i.e., when handling an input event), which is not the case anymore when Ren'Py requests fullscreen mode because of the way input events are handled in SDL2.
We can replace the `doRequestFullscreen()` function with our own so that it first tries to request fullscreen mode and only defers the call to the next input event if the request fails (it works, I've tried). Fixing that upstream would probably be better though, but I'm not brave enough to compile emscripten 😅

**Comment by renpytom** [comment]
@Kassy2048 , are you planning to PR the patch approach. I'm not a huge fan of compiling emscripten myself, either.

**Comment by Kassy2048** [comment]
@renpytom Yes, I plan to work on it this week-end.

**Comment by Kassy2048** [comment]
@renpytom This should be fixed now, so the issue can be closed.
