### ISSUE TITLE
Warning : write error : db is undefined

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#4793]
via Patreon:

> I do not know if this is where I can indicate a problem. I published a game on the internet a renpy game, With firefox I obient this type of message. Warning : write error : db is undefined The game works, but these messages can be disturbing for children. Renpy's version is dated June 2023. Firefox 114.0.2 (64-bit).
> Have you ever encountered this problem?
> I tested on chrome, edge, no error message. I specify that I am French and the game and for a class of CP / CE1. Children learn to read and write.

**Comment by Kassy2048** [comment]
There's also a FF setting named "dom.indexedDB.privateBrowsing.enabled" that can be set to `true` to enable IndexedDB in private mode. The DBs are deleted when the in-private session ends, and they are isolated from the non in-private DBs. FF 115 will set that setting to `true` by default instead of the current `false`.

**Comment by Hastury** [comment]
Hello,
Thanks for the tip, in fact by setting dom.indexedDB.privateBrowsing.enabled to True, the problem disappears.

Thanks for your help, have a nice day
