### ISSUE TITLE
"current.json"/updates folder not included in macOS builds which causes web updater to fail

### ISSUE THREAD

**Issue by blackcatstudiosdevelopment** [renpy/renpy#4803]
Issue: The `current.json` file, and indeed the entire `updates` folder, is missing from packaged macOS builds. This means that the web updater function cannot compare the current version with the server version and thus fails to update.

Desc/Backstory: Players recently began complaining that they could not update their games (manually or automatically) on macOS, however Windows players report being able to update just fine using the built in web updater, and after testing I can confirm this. I have scoured the packaged files and the only thing that seems to be tripping the updater is the fact that `current.json` is not being included in the macOS builds, but IS being included in Windows and Linux builds. My main distribution method for our small development team currently hinges on this feature as a way to quickly and efficiently distribute bug fixes as needed.

Expected Behavior: The `updates` folder and `current.json` files are included in macOS builds and therefore the game itself can be updated.

Actual Behavior: The `updates` folder and `current.json` file are both missing in macOS builds.

Notes: Just in case there was any weirdness between building on a Windows platform vs building on macOS itself I used the exact same version of Ren'Py (8.1.1) on both of my machines and had the same result, indicating that the build machine's platform doesn't matter.

**Comment by renpytom** [comment]
This doesn't work, and I don't plan to support this - the transform into a mac app doesn't lend itself to being updated, especially since the main reason for the transform would be to sign the app, which would prevent updates. 

One way you can work around this would be to make an all package: 

```renpy
init python:
    build.package("all", "zip", "window linux mac renpy all", "All Platforms")
```

That'll make a package that can be updated, that runs on mac (but that won't be a standalone app - it'll be closer to the way Ren'Py itself is distributed).
