### ISSUE TITLE
Variable names that include ñ result in compiled files that throw errors on Android

### ISSUE THREAD

**Issue by IcefangCerule** [renpy/renpy#4822]
Previously, we'd had sound files called out as (for example) `voice "audio\Mathew gruñido 1.ogg"` that worked just fine. But, after setting up definitions as `define Mathew_gruñido_1 = "audio\Mathew\Mathew gruñido 1.ogg"`, Android builds now throw invalid syntax exceptions everywhere that `voice Mathew_gruñido_1`, or any voice line where ñ is part of the variable name, is used.

Documentation doesn't appear to indicate if a character set needs to be defined or called out to support this.

**Comment by KiloOscarSix** [comment]
python is an English language and will throw weird exceptions if using unrecognised characters

**Comment by KiloOscarSix** [comment]
> Officially, variable names in Python can be any length and can consist of uppercase and lowercase letters (A-Z, a-z), digits (0-9), and the underscore character (_). An additional restriction is that, although a variable name can contain digits, the first character of a variable name cannot be a digit.

**Comment by renpytom** [comment]
Do you have the message that Android is producing?

**Comment by IcefangCerule** [comment]
![image](https://github.com/renpy/renpy/assets/129025931/4c52ff4d-22aa-42f8-855f-82420429cd4e)

**Comment by mal** [comment]
From your screenshot you're using Ren'Py 7.4.x which is based on Python 2. Python 2 (as mentioned by Kilo) only supports identifiers (i.e. variable names) that consist of `a-z`, `A-Z`, `0-9`, and `_`. It is this that's producing the syntax error you're encountering - Python 2 deems your variable name invalid.

However, using Ren'Py 8.x which is based on Python 3, behaves as I believe you expect. This is because Python 3 [permits unicode to be used within identifiers](https://docs.python.org/3/tutorial/interpreter.html?highlight=identifiers#source-code-encoding) (though it still advises against it for portable code) and so you don't get any syntax errors and it just works.

Is it possible that at some point in development you switched from using Ren'Py 8 down to Ren'Py 7, and that is why you've started to see this error?

Locally I was able to verify that 7.6.1 produces the same exception on a Linux box, and that 8.1.1 on the same box works as expected, such that this seems unlikely to be an Android specific quirk.

**Comment by renpytom** [comment]
I'll note that non-ASCII filenames aren't actually supported by the  zip format that Ren'Py uses to distribute games, and that Android uses for APKs.  (Zip is old enough it doesn't specify an encoding for the filenames - we use UTF-8, but that's just the most likely choice, not something that's guaranteed to be correct.) 

That being said, this should work on Python 3, and as for Python 2 - mighty be a good time to switch. :)
