### ISSUE TITLE
Lint error: "unable to evaluate filename 'sfx_variable'" when storing sound file path in sfx_variable

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4831]
# Repro

Setup SFX in those files:

```rpy
# resources.rpy
init -1:
    ## SFX assets
    define audio.sfx.blade_clash1 = "audio/sfx/sfx_blade_clash1.opus"
    define audio.sfx.blade_clash2 = "audio/sfx/sfx_blade_clash2.opus"

# script.rpy
label start:
    # dummy assignment to demonstrate, should be random or passed by label call
    $ variant_number = 1
    if variant_number == 1:
        $ sfx_variant = audio.sfx.blade_clash1
    else:
        $ sfx_variant = audio.sfx.blade_clash2
    play sound sfx_variant
```

Then lint the project.

Error:
> "unable to evaluate filename 'sfx_variant'"

Note that the error is lint only, running the game uses the variable fine.

**Comment by mal** [comment]
This is an expected limitation of lint. `sfx_variant` only exists in python code, which for various reasons lint isn't able to sanely evaluate, and so as far as lint is aware that variable won't be available at the time it is used, and so issues the warning.

The work around for this is to use the `default` statement which lint can make sense of to initialise the variable with a value that lint will accept, i.e. `default sfx_variant = 'audio/sfx/sfx_blade_clash1.opus'`. Since you are always setting `sfx_variant` in your label, the initial value should never end up being used (except for during lint) and so you'll get the same behaviour in your game but lint will be able to understand and validate that variable.

**Comment by hsandt** [comment]
Thanks, it worked!

Should I close it? @Gouvernathor flagged it as unintended behavior, but the technical limitation seems difficult to circumvent. Maybe this could be documented better, or the error message improved. But without knowing, it will become a bit long such as "cannot evaluate, if it's a Python variable please add `default` statement...". Or we could let users find this issue, now that it exists.

I'll let you choose how to handle this.
