### ISSUE TITLE
Close without confirmation when closing while asking confirmation for closing

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4853]
If you click the little cross once, it asks for confirmation (if you're not on the main menu). If you click the red cross during that time, it should close directly and not wait for you to confirm.
It is useful when trying to close while the console is open (you need to close the console and click the confirm screen otherwise).

On windows you can currently bypass this by triple-clicking the red cross in which case the OS force-closes it. But that's not very safe when in fullscreen mode and using Alt-F4 - take this habit and you will close random stuff when doing it from the main menu by accident.

**Comment by hsandt** [comment]
Wow, I just discovered the triple-click to force close and bypass close prompt and only found this thread talking about it! And I can't find any information about triple-clicking working in general on Windows (I don't have another app with close confirmation to test, I guess I could try to write one in Godot)... is it actually implemented on Renpy side?

Unlike what renpytom says, I can't force close with double-click, only triple-click.

So... is Renpy checking triple-click by design? Or is it supposed to force close on double click but somewhat it doesn't work on Windows 11, Renpy 8.5.3?
