### ISSUE TITLE
Screen resizing constantly on Android

### ISSUE THREAD

**Issue by tkshnwesper** [renpy/renpy#4895]
Watch video for demonstration:

https://github.com/renpy/renpy/assets/7362366/ac7adefb-374c-4462-992a-c671669411fd

Happening on Pixel 2 API 30.

**Comment by renpytom** [comment]
Does The Question work? I want to make sure it isn't something game-specific.

**Comment by tkshnwesper** [comment]
> Does The Question work? I want to make sure it isn't something game-specific.

It happens with The Question too.

https://github.com/renpy/renpy/assets/7362366/43e739dd-7274-4186-99c6-f3e630012c0a

**Comment by renpytom** [comment]
Is this the emulator, or on a real device? Since I dug my pixel 2 XL out of storage, and it's working fine on the real thing.

**Comment by tkshnwesper** [comment]
> Is this the emulator, or on a real device? Since I dug my pixel 2 XL out of storage, and it's working fine on the real thing.

It's on the emulator.

**Comment by loafylemon** [comment]
I encountered a similar problem where indirectly calling `renpy.check_permission` and `renpy.request_permission` from within the screen scope led to this unintended outcome.

Here's the (shortened) code that triggered this:

```renpy
init python:
    class AskPermission(Action, NoRollback):
        def __init__(self, name):
            self.name = name

        def __call__(self):
            if not renpy.android:
                return True

            return (renpy.check_permission(self.name) or renpy.request_permission(self.name))

screen navigation(title=None):
    textbutton _("Mods") action If(AskPermission("android.permission.WRITE_EXTERNAL_STORAGE"), ShowMenu("mods"), Notify("Please grant storage permissions to enable modding functionality."))
```

I think the problem on my side stemmed from my attempt to request a permission that is no longer available on API 30 and above. Since the request was implemented within the screen scope, the OS just kept trying to inrerpet it and attempted to show the dialog window, hence the flickering.

**Comment by renpytom** [comment]
I've been unable to reproduce this with The Question on the emulator. At this point, it's probably a local problem, rather than something in Ren'Py.
