### ISSUE TITLE
DragGroup - add method does not trigger redraw

### ISSUE THREAD

**Issue by ticlock** [renpy/renpy#4939]
I believe **add** method of the DragGroup should trigger **redraw**, since it is included in the documentation.
For example, adding a new drag to the DragGroup via function:
```
    def add_square(name, pos):

        drag_group = renpy.get_displayable(screen='dragtest', id='dgroup')

        new_drag = Drag(d=Solid("#bbb", xysize=(100,100)), drag_name = name, xpos = pos[0], ypos = pos[1])
        
        drag_group.add(new_drag)
```
new drag does not appear immediately, it takes a random time to appear. Adding **redraw** method solves the problem:
```
        drag_group.add(new_drag)
        renpy.redraw(drag_group,0)
```
The problem was pointed out in the [post](https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=67111#p562531)

**Comment by mal** [comment]
That isn't standard behaviour for other displayables with an `add` method, typically because it's used during displayable construction and triggering multiple redraws wouldn't make sense, and I'd suggest the same holds true here.

If a creator is manipulating the contents of an on-screen displayable, then manually needing to call redraw once all operations are done seems reasonable. In such a scenario there may be multiple calls to `add` being made, but you'd only want to redraw after they were all done, not spam it with each call.

**Comment by renpytom** [comment]
I think @mal is right here, though it probably makes sense to update the documentation to mention this.

**Comment by renpytom** [comment]
I changed my mind on this, and decided that it makes sense to call renpy.display.render.invalidate on add. Invalidate is a very small function, that consists of some boolean checks and a call to id, and so it seems fine to call it each time a displayable is added to another.
