### ISSUE TITLE
Font crashes with the new text rendering

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#4952]
I tested the renpy-8.2.0.23090204+nightly and the Hyperlegible.ttf font crashes the game with this log:

```
renpy.text.hbfont.FreetypeError: 140: b'too many function definitions'
Exception ignored in: 'renpy.text.hbfont.HBFont.get_glyph'
Traceback (most recent call last):
  File "C:\Users\---\Downloads\renpy-8.2.0.23090204+nightly-sdk\renpy\text\text.py", line 361, in bounds
    return fo.bounds(glyphs, bounds)
renpy.text.hbfont.FreetypeError: 140: b'too many function definitions'
```

you can download the font [here](https://mega.nz/file/VE5TBKCQ#93KDGQ7foNyIOwXSCPYo8Y-IVLmQxwSSV-23EdkVDpU)

And this is my opinion, but the new rendering makes most fonts look weird and clunky. Maybe this shouldn't be the default because it will affect many games and some devs probably won't know what happened.

**Comment by renpytom** [comment]
Do you have some screenshots of the changes to fonts? What I've been seeing are fonts that are different from how they rendered before, but closer to how a browser would render the font.

**Comment by renpytom** [comment]
That is probably a broken font file, but the return to autohinting works around the issue. Ren'Py should also produce sharp results, now for more languages, starting in the 2023-09-10 nightly.

**Comment by Org-gith** [comment]
It's the kind of stuff where there is no definitive right answer as far as the default, but as long as we can pick between the two it should be good.
Really depends on the font, but I believe a font that is made with good standards should benefit from using bytecode. 
For example, here is a good-quality font rendered in 8.1 and 8.2 (when bytecode was the default):

![81](https://github.com/renpy/renpy/assets/78823063/33e051b6-2a4f-42bb-b7e4-87469540816d)
![82](https://github.com/renpy/renpy/assets/78823063/c7fce72b-2187-432d-a25f-bf9b67c151a4)

The second one is well-balanced (8.2), but the first one is too sharp. Also, the spacing is not good in the first one.
The problem is that the internet is loaded with poor quality fonts that were made 20 years ago and realistically a lot of the creators could end up using one of those. There is also a trend with over-sharpness being perceived as more pretty even though it's wrecking the eyes (not specific to fonts) and creating artifacts on an image/font but that's another subject and a subjective one.

Is it conceivable to have a config that turns one the bytecode to be the default (and the auto hint would be the one by default but we could turn it around with the config), or do we have to always manually configure each individual font?

**Comment by Org-gith** [comment]
Definitely, I have older projects where I wouldn't want that on because they are using old fonts and this definitely can make text overflows of GUI and some older fonts look nice and unique but only work well with the older approach. It's easier to fall into the pitfall of the new approach than the old approach that would give a good enough result across more fonts.

**Comment by renpytom** [comment]
I think a config that lets you specify the font hinting on a font-by-font basis is the way to go, so I'll at that shortly. 

Also, please check out this morning's build, which should have better hinting using the autohinter, which has returned to being the default.

**Comment by Org-gith** [comment]
Did you try to double-click on the font on Windows to see how it should look, sometimes font have different versions (1.0, 1.1 etc.) and changes its look slightly over time. If BCI (which looks horrendous here) and the new autohinter have it like that, it's strange that they would be making the same mistake on a very different basis but I don't know.

**Comment by rdurfee** [comment]
The "fi" merge is called a ligature, and all modern and professional fonts should do it, along with other letter combinations involving f, t, l, i, j. Some fonts may even merge other letter combinations in a decorative style.

**Comment by rdurfee** [comment]
I'm not sure I follow. If the ligatures are included in the font, then they should be displayed. It's not Ren'Py merging the characters, it's the font, and Ren'Py's text engine is now respecting this.

The ligatures are necessary because in many typefaces, the hook of the f will come close to the dot of the i or even touch it, and the ligature fixes this. If the designer doesn't want ligatures, they don't supply them in the font.

Take a look at a book or magazine and you'll see them all over. Microsoft Word, Pages, and publishing apps also display ligatures in your text.

**Comment by bober-gith** [comment]
With this website it gives the ligature on the dejavu font: https://fontmeme.com/fonts/dejavu-sans-font/#previewtool
I think bytecoded and the new autohinter are more accurate, this seems the most logical conclusion.
But I understand the frustration, since it means the front doesn't behave the same the way you envisioned it when you started to use it, it's a tough call and I don't know what it's the right understand but the new autohinter seems to respect the font better. Maybe a way to toggle autohinter legacy and having the new autohinter be the default? I have no idea if this possible or too heavy but this could solve your problem.

**Comment by mal** [comment]
You're entitled to your opinion, but perhaps that a sign that you should find a font you prefer instead?
Either way, how avoid this is already in the [nightly documentation](https://nightly.renpy.org/current-8/doc/incompatible.html#incompatible-7-7-0).

**Comment by bober-gith** [comment]
https://github.com/renpy/renpy/commit/1e518437ddf110c3633134f24d55d3ff615fec36
You are right, just realized as well that it was already made and pre-shotted before all of this happened, three days ago. The thing was already solved. 🛌 (not like it will benefit me but good for everyone regardless of who is "right" or "wrong".)
