### ISSUE TITLE
In Renpy 8.1.3 Web, full-screen in vertical orientation, and then change to landscape orientation causes bugs

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#4987]
Steps taken on a Samsung Android device:
1. I open the game on the phone with vertical orientation.
2. I enter full screen mode.
3. I rotate the phone to switch to horizontal orientation.
4. The screen gets bugged.

**Comment by Kassy2048** [comment]
Which browser is it?

**Comment by SergioAlonsoJr** [comment]
Google Chrome and Samsung Internet.

Em sex., 22 de set. de 2023 às 23:25, Kassy ***@***.***>
escreveu:

**Comment by renpytom** [comment]
This has been fixed by 6d4a104b8d7e38a26895b7f274429fbce62ad9db , and renpy/renpy-build@6a77c6fd4d3a8df0e98fbc1606fe0f13672e21ab. 

(Basically, trying to use the SDL/emscripten method of going fullscreen didn't work well. But the web port always handled resize well, so simply calling requestFullscreen on the html element and letting the resizing happen seems to have solved this. )
