### ISSUE TITLE
Renpy 8.1.3 Web: Full-screen mode is broken on iPhone 14 Pro Max

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#4988]
The screen is moved outside the visible area and the game becomes unplayable.

Would it be possible to detect that the web version is running on an iPhone device, so I can hide the fulls screen button?

The Full screen features works well on PC web and Android Web.

I'd like to offer the necessary iPhone or iPad hardware to anyone who has experience with Renpy and its web version. I believe the limiting factor might be the lack of hardware to test the solution locally.

**Comment by Kassy2048** [comment]
You can use such a method to detect if the game uses a Web browser on iPhone/iPad:
```rpy
init python:
    def is_iOSWeb():
        if renpy.emscripten:
            import emscripten
            userAgent = emscripten.run_script_string('window.navigator.userAgent')
            return 'iPhone' in userAgent or 'iPad' in userAgent
        return False
```

The use it to hide the Fullscreen option:
```rpy
                        if not is_iOSWeb():
                            textbutton _("Fullscreen") action Preference("display", "fullscreen")
```

But it would be better to fix the issue. I own no Apple device to work on it though🤷‍♀️

**Comment by SergioAlonsoJr** [comment]
@Kassy2048, would it be possible that I give you an iPhone SE (or equivalent dollars amount, so you can buy it yourself) so you can resolve the issue for the community?

**Comment by Kassy2048** [comment]
> @Kassy2048, would it be possible that I give you an iPhone SE (or equivalent dollars amount, so you can buy it yourself) so you can resolve the issue for the community?

Thanks but I'd rather not go this way as I'm not even sure this can fixed. It's probably an emscripten issue, so not RenPy's fault, but we can workaround it maybe (also the case for #4987).

I've managed to get a free license for [browserstack](https://browserstack.com) (they offer them for open source projects like RenPy). I'll try to reproduce this issue there and see what can be done.

**Comment by SergioAlonsoJr** [comment]
@Kassy2048, if the problem is related to emscripten, who would be capable of fixing the problem on the root?

**Comment by SergioAlonsoJr** [comment]
I'd like to offer the necessary iPhone or iPad hardware to anyone who has experience with Renpy and its web version. I believe the limiting factor might be the lack of hardware to test the solution locally.

**Comment by Kassy2048** [comment]
> @Kassy2048, if the problem is related to emscripten, who would be capable of fixing the problem on the root?

The [emscripten project](https://github.com/emscripten-core/emscripten), but unless you come with a solution, they'll probably don't investigate the issue because of lack of resources.

Unfortunately, it seems like [fullscreen mode is not available on iPhone](https://caniuse.com/fullscreen) officially, so there is not much we can do apart from complaining to Apple. My only hope is that youtube website is still able to show video in fullscreen on iPhone so maybe Google found a way, but that requires studying YT code.

**Comment by SergioAlonsoJr** [comment]
@Kassy2048, this code works on iPhone, but it doesn't work on my iPad 9

```
init python:
    def is_iOSWeb():
        if renpy.emscripten:
            import emscripten
            userAgent = emscripten.run_script_string('window.navigator.userAgent')
            return 'iPhone' in userAgent or 'iPad' in userAgent
        return False
```

On my iPad, the User Agent is
"Mozilla/5.0 (Macintosh;iIntel Mac OS X 10_15_7) AppleWebKit/607.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15"

But it did give me an idea: Safari is mostly used on iPhones and iPads, so I can get a good enough approximation with the 'Safari'

**Comment by Kassy2048** [comment]
@SergioAlonsoJr Looks like iPad pretend to be a Mac when viewing website in desktop mode (which is the default mode on iPad now). You can try something like that instead (base on [this solution](https://stackoverflow.com/a/58065241)):
```rpy
init python:
    def is_iOSWeb():
        if renpy.emscripten:
            import emscripten
            res = emscripten.run_script_int('/iPad|iPhone|iPod/.test(navigator.userAgent) || (navigator.userAgent.indexOf("Mac") != -1 && navigator.maxTouchPoints > 1)')
            return True if res else False
        return False
```

You can test the detection works using [this fiddle](https://jsfiddle.net/7k8tu0pz/4/) (it should show "iOS detected" in the bottom right text pane).

About fullscreen mode on iPhone, it seems only allowed for video elements, so we cannot support it. We should probably make the fullscreen option a no-op that shows an error message if fullscreen is not supported by the browser, instead of removing it from the menu in this case as games created before we hide this option will still show it.

It is possible to enter fullscreen mode on iPad though using the "webkit" prefix of the API functions (test fiddle [here](https://jsfiddle.net/vc3zd0km/1/)). Yet Ren'Py games fail to enter fullscreen mode on iPad, so there is something to fix here at least.

**Comment by renpytom** [comment]
I've disabled fullscreen mode on Safari, as it appears to be buggy there. I recommend lobby your government to force apple to allow alternate browsers on iOS.

**Comment by renpytom** [comment]
And it turns out that the rewrite of web fullscreen support to solve #4987 also fixes this. 

I still recommend @Gouvernathor drops a dumptruck of manure at the nearest apple store, but more out of general browser freedom principles.
