### ISSUE TITLE
ClearProgress() action

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5000]
One use case is to reset the CG/scene galleries or dialogue read progress. Other use is to reset all game variables of the RPG elements without the tedious work (and potential errors) of manually do it. Equivalent of the "delete persistent" of the launcher.
The function `persistent._clear(progress=True)` is used to achieve this. However, at least in my experience, doing it mid-game or in a menu leads to many crashes. I came up with this:

```python
    def clear_progress():
        if main_menu:
            renpy.run(ShowMenu("main_menu"))
        persistent._clear(progress=True)
        renpy.reload_script()
```

With `renpy.reload_script()` every possible problem is resolved. Never had a problem with that. However, that function doesn't work on android.

My question is: is there a better way to implement what I'm doing in order to work on android without having to reload the game? Can this be implemented in Ren'Py as default?

**Comment by MiiNiPaa** [comment]
I beieve crashes happens because your game accesses persistent data, but does not handle the situation when that data can be `None`. In the meantime, to solve problem without restart you can try to reassign all defaulted fields manually (or make the game handle `None`s properly).

I think, another argument to the `_clear` method, `regenerate_defaults`, could solve this problem.

**Comment by Gouvernathor** [comment]
I think regenerating the persistent defaults should even be the default behavior of _clear, unless it causes compat problems.

Maybe this could be solved by returning to the main menu. I know utter_restart and reload_script aren't supported on android, but there's still something happening when you end a playthrough, and I think defaults are re-triggered at that point. But I'm not sure if it also applies to persistent, because it's a kinda special case.

**Comment by renpytom** [comment]
I've made re-running default persistent.var statements part of persistent._clear. It probably doesn't need to be its own action.
