### ISSUE TITLE
Optionally storing custom text tag states for retroactive viewing via _history_list

### ISSUE THREAD

**Issue by feltcute** [renpy/renpy#5006]
I am involved in a project that is trying to make use of custom text tags to cleanly present text tags of game variables that are highly mutable per each interval of dialogue.

Using [text interpolation] requires directly referring to variables that can otherwise be rather lengthy to tell a writer to type (e.g. `player.inventory.money`), and other times uses code inside the text tag functions to conveniently determine and format its final value when it was called.

It is possible to alias using `money = player.inventory.money`, but I'd rather keep it out of global space if it could be helped, especially for things built to be as little characters as possible for shorthand referral. It is also more sensitive to when and where a variable for the shorthand is declared, whereas using custom text tags was found to be far more flexible in the treatment of declaring variables.

The only shortcoming to custom text tags is that it always reflects the latest result in history. Consider the following scenario:
1) '300' is the text tag, making use of custom text tags to make it bold and and colored gold out of the box as well. 
2) Represented as the short and concise `{money}`, fetching the value of `player.inventory.money`
```
"You have **300** coins? That's too little." (it was 40 at the time)
...
"You have **300** coins?! That's a lot!" (it was 900 at the time)
...
"You now only have **300** coins left!" (present time)
```

This behavior is preferable by default for things like the player's name often times, but less-so when it is an intentionally mutable value.

I'd like to optionally store the custom text tag state for the functional sake of when displayed via _history_list in the history screen so that it always reflects what its value was at the time, rather than what its latest value currently is.

**Comment by renpytom** [comment]
This isn't what custom text tags are for. 

If you'd like this, you can figure something out with https://www.renpy.org/doc/html/config.html#var-config.history_callbacks, but if you want interpolation, use interpolation and not text tags, as that's the supported way of doing this.

**Comment by Gouvernathor** [comment]
I'm surprised that the custom text tags doc doesn't mandate the functions to be pure (= returning the same value for the same input and without side-effect). It most definitely should.
The text tag way is not a good idea to compute dynamic values depending on the state of the game because it can be called at any time during prediction, which can yield index or attribute errors in typical cases if the data is not always correctly set. I also once tried to have a text tag trigger a sound effect : it was a terrible idea.

**Comment by feltcute** [comment]
I was in serious pursuit of trying to gauge feasibility of figuring something out with history_callbacks, though that would be moot if the functionality is restricted.

There _is_ some weird technicalities to custom text tags in that you can technically refer to variables in global inside a text tag function without having to actually use global. It is hard to tell where intentional uses for text tags begin and end.

I appreciated text tags being outside of global variable space, and ran into no problems with them other than the issue with history, but if they aren't meant for this use case and are to be further enforced to require constant values, I can try to make do with interpolation.

**Comment by Gouvernathor** [comment]
In python, the scope a function accesses is defined by the location it's placed in. You write the function, so there is no way for us to restrict what it accesses.
Also, it's normal for a function to access global constants, which _are_ in the global store.
The distinction is simple, since every creator-defined value in Ren'Py is created either by the default statement, for variables, or define for constants (you did that in you project, _right_ ?) (there are also label parameter and dynamic variables but let's not go into details). Things declared using define can be accessed but not set (they should never be set anyway, since they are constants), things declared with default should not be accessed nor set. Simple as that.

All that is, if my view of custom text tags is valid and if we do disown dynamic text tags - but given the implementation, I don't think it's safe to do otherwise.

**Comment by feltcute** [comment]
The project is not consistent on using default and define. I am working it towards that as convenient for others.

I have a regex ready to go to adjust the relevant text tags to instead be interpolated variables, yeah.

With how you described defaults interactions with custom text tags, I'd like to make a case for dynamic text tags with the following, which works as expected currently in both practice and in the history screen:
```python
    def StoredColorTag(tag, argument, contents):
        global textColor
        if argument:
            textColorTag = argument
            textColor = argument
        else:
            textColorTag = textColor
        return [(renpy.TEXT_TAG, "color={}".format(textColorTag))] + contents + [(renpy.TEXT_TAG, "/color")]
    config.custom_text_tags["storedColor"] = StoredColorTag
```

Writers are capable of optionally setting a color for `{storedColor}` as they would for `{color=#ffffff}`, or, they can directly use `{storedColor}` to use the last value it was set to. There are 6 other variants of it, so writers can use up to 7 colors for a scene without having to constantly re-declare the color. 

This is liked and desired behavior, and would break if mutable values could not be accessed nor set in a custom text tag.

**Comment by renpytom** [comment]
I'm thinking the right solution to this is to create a new namespace that's used in interpolation, in the same way the character namespace is used for character.s Perhaps adding support for calling a function during interpolation as well. 

We are not going to add support for dynamic text tags, and I think that #5007 is worth adding to the documentation.

**Comment by feltcute** [comment]
> I'm thinking the right solution to this is to create a new namespace that's used in interpolation, in the same way the character namespace is used for character.s Perhaps adding support for calling a function during interpolation as well.
> 
> We are not going to add support for dynamic text tags, and I think that #5007 is worth adding to the documentation.

Those two features sound workable to me, particularly if any restrictions as outlined by Gouvernathor applied to text tags coincided in the same update with those two features for interpolation.

Will close the issue with #5007 merged.
