### ISSUE TITLE
Android app hangs indefinitely at launch after an install or update

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#5010]
Several google play reviews mention an issue in which the game stays in the loading screen and never actually launches. The loading bar never fills up and remains empty.

In the few times I was able to reproduce the issue, the workaround I found was deleting Google Play application's cache. When the game launches again, it actually installs additional app packages (my app is a bit less then 300 MBs) and then the load bar fills up and the game does load properly.

My latest update was rejected by Google Play's system with the following reason:

```
Issue found: Violation of Broken Functionality policy
Your app contains content that isn’t compliant with the Broken Functionality policy.
- App installs, but doesn't load
```

I wasn't able to get the app freeze this time, but I'm adding the logcat in case it provides some information: 
[https://drive.google.com/file/d/1HQGth0aCo1ROd1yAzYyRgA-gIgK2GMMr/view?usp=drive_link](https://drive.google.com/file/d/1HQGth0aCo1ROd1yAzYyRgA-gIgK2GMMr/view?usp=drive_link)

**Comment by MK-dev-official** [comment]
I got the same issue.

**Comment by renpytom** [comment]
I'd need a copy of the logcat for a freeze, if you have one. It sounds like Google Play isn't delivering the fast-follow data when requested.

**Comment by marchare555** [comment]
I wasn't able to reproduce the exact same issue, but I found that if my phone isn't connected to wi-fi, I get a prompt that asks whether I want to download 200+ Mo of data. If I select "wait for wi-fi", the loading screen remains stuck like the initial issue I described. I did not get that prompt before and I wonder if a bug was preventing the prompt from showing and picking "waiting for wifi" by default, resulting in that stuck screen.

https://drive.google.com/file/d/11cqhdxA8HZPLcc8LF1IfSevd9wFjvyXO/view?usp=drive_link

I retrieved the logcat for that:
https://drive.google.com/file/d/1YquZSzhy_bHaycTLUMedJOkT4v7NQoDB/view?usp=drive_link

Hope that helps.

**Comment by Christmas9128** [comment]
Hello!

I have the same problem with Google Play.

I've built a game with renpy 8.0.3 for Android and published it on the Google Play. Previously it was approved by Google but now it's refused because it "violated broken functionality policy - App installs, but doesn't load". Attached to the refusal was a screenshot of the Renpy downloading screen with bar (image 1).  I tested the game download on different Android devices and everything was OK on every device (image 2). I always use the same Renpy version (8.0.3) in every upload on Google Play but now the game is refused.
![6-2589000034548](https://github.com/renpy/renpy/assets/146843490/6553e3a5-0169-4dd1-bae8-40ba912d31ec)
![dsdsd](https://github.com/renpy/renpy/assets/146843490/676ad4dd-9f52-4c4f-86cf-94a07d9ab4d0)

**Comment by 90PercentDenny** [comment]
exact same issue. i tried uploading a build built with renpy 8.0.3, 7.6.3 and 8.1.3. each time it's been rejected with the notice: "Your app contains content that isn’t compliant with the Broken Functionality policy. App loads, but not responsive". the game does however work for me and every other device i've tested on.

at first i thought it was just loading very slowly for them so i tried turning all .png into .webp. more than halved the file size but the game still won't load for them, so i guess that's not the issue. i was able to upload a working build dec, 16 2022. any help/insight on where to go from here would be massively appreciated.

**Comment by renpytom** [comment]
Perhaps there should be a splashscreen that better explains what's going on? Not sure what I can do if google play can't download the fast-follow information.

**Comment by renpytom** [comment]
Also, can people with problems post their android.json? I have an idea.

**Comment by 90PercentDenny** [comment]
here it is!

[android.json](https://github.com/renpy/renpy/files/13303402/android.json)

**Comment by renpytom** [comment]
Could you try enabling the google play store, and resubmitting?

**Comment by 90PercentDenny** [comment]
tried a few things:
* configuring the game with the choice "google play"
* configuring the game with "both, in one app"
* updated the splash screen to say "loading: if this page is unresponsive, try restarting the app".
each time the app was rejected for the same reason: "app loads but not responsive". i'm curious, in android.json are

"google_play_key": null,
"google_play_salt": null,

of any significance? should it be null?

**Comment by renpytom** [comment]
Okay, thank. Is there a support contact at google? A logcat from when the problem is happening would be really good here.

**Comment by 90PercentDenny** [comment]
contacted them for it but they've not given us the logcat. we kept fiddling with the game build though and after making sure our android.json/.android.json looked like this:

```json
{
    "expansion": false,
    "google_play_key": null,
    "google_play_salt": null,
    "heap_size": "3",
    "icon_name": "Purrfect Apawcalypse: Love at Furst Bite",
    "include_pil": false,
    "include_sqlite": false,
    "layout": null,
    "name": "Purrfect Apawcalypse: Love at First Bite",
    "numeric_version": "398",
    "orientation": "sensorLandscape",
    "package": "com.ninetypercentstudios.purrfectapawcalypse1",
    "permissions": [
        "VIBRATE",
        "INTERNET"
    ],
    "source": false,
    "store": "play",
    "update_always": true,
    "update_icons": true,
    "update_keystores": false,
    "version": "3.98"
}
```
* also cleaning out the android temp files
* also configuring the game with the choice "google play"
* also building on a new moon

the game has now been approved!

**Comment by 90PercentDenny** [comment]
welp, the game getting accepted might've been a fluke; we're trying to update a different game in the series and are having the same issue. we're using Ren'Py 8.1.4.23111304+nightly, plus we modified rapt\project\renpyandroid\src\main\java\org\renpy\android\PythonSDLActivity.java to print on screen any exceptions or anything that would normally be logged from that file:

![image](https://github.com/renpy/renpy/assets/150304097/5b3b71fa-3f5f-49b4-982f-cc3657775a67)

we're able to replicate this sequence of log messages if we download the game until it's playable, turn off the wifi/data, and then launch the game. it seems, based on the screenshot from google play, that they should have wifi though. (as a note, we also have play as you download off)

![image](https://github.com/renpy/renpy/assets/150304097/a97f4f39-4859-473c-9d23-773755cf7720)

any ideas about what would prevent the download from starting, or anything else we could try and log to get more info? thanks.

**Comment by renpytom** [comment]
I don't have a great idea what's wrong here. If you release it to the testing track, can it be downloaded to devices normally?

**Comment by 90PercentDenny** [comment]
yes, works on several devices normally, there were maybe two cases where folks were stuck on the loading screen, had to close the app and reopen, after which it would load as normal.

**Comment by CognizantApple** [comment]
@marchare555 @MK-dev-official @Christmas9128 
Sorry for the @ but I must know, did any of y'all find a solution for this one? Denny and I are still stuck 😵

**Comment by MK-dev-official** [comment]
Only thing I did was to deploy the app on a website using a docker image and then creating a pwa for Android using pwabuilder and abandoning this issue... Looks ugly but it works.

**Comment by npckc** [comment]
Hello, I have been having the same as mentioned here with an update to a game that has been released on Google Play already. I have contacted Google Play for an appeal and more information, but the appeal was rejected with extra information provided. I tried with two separate builds built at separate times that both worked on my own devices on Google Play's internal app testing track, but both were rejected for the same reason.

**Comment by renpytom** [comment]
It looks like it's their test process that's working, as we've never seen this failure on an external device. You need to be contacting them for help, not me. 

Ask them for the logcat information. I wish I could help, but if the problem is on their end, I'm limited in what I can do. (There is the new downloader coming in 8.2, but I'd rather this works.)

**Comment by npckc** [comment]
I posted the comment here because I am not sure this is the case - users on the store have also posted reviews about the game downloading but not ever loading, so I feel there may be an issue with the way Renpy aabs are delivered through Play Store on some devices that does not exist on others. I have been in contact with Google, but I have also heard from other Renpy devs who have had the same issue reported on their apps blocking their updates on Google Play and it seems to be a Renpy app specific thing.

**Comment by renpytom** [comment]
Oh, I'm familiar with it - I just have no idea what I can change to make it work better.

**Comment by bober-gith** [comment]
https://support.google.com/googleplay/android-developer/thread/243956815/broken-functionality-policy-because-vpn-or-proxy-is-used-to-test-the-app?hl=en&sjid=8020761042291499082-EU

It seems they are testing the apps using some very strange setup that doesn't represent reality, what kind of unrealistic scenario could lead to the app not loading?

**Comment by renpytom** [comment]
I'm thinking I may rewrite the fast-follow implementation so it uses the NDK version, rather than the Java version.

**Comment by npckc** [comment]
I have received a reply from Google staff about my specific app and am sharing it here in case it is helpful. (Sorry if it isn't!) The response has been translated from the original but I think all the terms are correct.

"Before you added our test accounts to the whitelist, we also had issues where the install stopped multiple times when we tried to boot the app on our test accounts. There is the possibility that our production environment not being approved may be a factor. Please confirm that there is no issue with your app's publishing settings, referring to here: https://developer.android.com/studio/publish"

The provided link does not seem to provide much more information about how publishing settings should be changed, but I'm wondering if there is something specific since Google staff seem to have no issue loading the app if their test accounts are whitelisted in the alpha track, but in the release track where there is no ability to add accounts to whitelist, they are not able to load the app.

**Comment by renpytom** [comment]
Can you show google: 

```
12-20 11:08:43.730 I/PlayCore(10462): UID: [10000]  PID: [10462] AssetPackServiceImpl : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.assetmoduleservice.AssetModuleService})
12-20 11:08:43.731 I/PlayCore(10462): UID: [10000]  PID: [10462] AssetPackServiceImpl : linkToDeath
12-20 11:08:43.733 I/Finsky  ( 4023): [36] kxi.c(9): getSessionStates for package: com.npckc.tavern
12-20 11:08:43.735 W/Finsky  ( 4023): [36] kxb.a(91): The app is not owned, package: com.npckc.tavern
12-20 11:08:43.737 I/Finsky  ( 4023): [36] kxi.j(9): startDownload() for package: com.npckc.tavern
12-20 11:08:43.739 W/Finsky  ( 4023): [36] kxb.a(91): The app is not owned, package: com.npckc.tavern
12-20 11:08:43.740 I/Finsky  ( 4023): [36] kxi.j(9): startDownload() for package: com.npckc.tavern
12-20 11:08:43.740 W/Finsky  ( 4023): [36] kxb.a(91): The app is not owned, package: com.npckc.tavern
12-20 11:08:43.741 I/Finsky  ( 4023): [36] kxi.j(9): startDownload() for package: com.npckc.tavern
12-20 11:08:43.741 W/Finsky  ( 4023): [36] kxb.a(91): The app is not owned, package: com.npckc.tavern
12-20 11:08:43.741 I/Finsky  ( 4023): [35] kxi.j(9): startDownload() for package: com.npckc.tavern
12-20 11:08:43.742 W/Finsky  ( 4023): [35] kxb.a(91): The app is not owned, package: com.npckc.tavern
12-20 11:08:43.743 I/PlayCore(10462): UID: [10000]  PID: [10462] AssetPackServiceImpl : Unbind from service.
12-20 11:08:43.744 I/PlayCore(10462): UID: [10000]  PID: [10462] AssetPackServiceImpl : onError(-13)
12-20 11:08:43.744 I/PlayCore(10462): UID: [10000]  PID: [10462] AssetPackServiceImpl : onError(-13)
12-20 11:08:43.744 I/PlayCore(10462): UID: [10000]  PID: [10462] AssetPackServiceImpl : onError(-13)
12-20 11:08:43.745 I/PlayCore(10462): UID: [10000]  PID: [10462] AssetPackServiceImpl : onError(-13)
12-20 11:08:43.745 I/PlayCore(10462): UID: [10000]  PID: [10462] AssetPackServiceImpl : onError(-13)
12-20 11:08:43.745 I/PlayCore(10462): UID: [10000]  PID: [10462] AssetPackManager : Could not sync active asset packs. com.google.android.play.core.assetpacks.AssetPackException: Asset Pack Download Error(-13): The app is not owned by any user on this device. An app is "owned" if it has been acquired from Play. (https://developer.android.com/reference/com/google/android/play/core/assetpacks/model/AssetPackErrorCode.html#APP_NOT_OWNED)
```

According to: 

https://developer.android.com/reference/com/google/android/play/core/assetpacks/model/AssetPackErrorCode.html#APP_NOT_OWNED

"An app is "owned" if it has been installed via the Play Store." 

I don't see how this could be Ren'Py's fault, as Ren'Py doesn't control if something is installed through the Play store or not.

**Comment by mal** [comment]
Couple of potentially [related](https://github.com/google/play-unity-plugins/issues/190) [issues](https://github.com/google/play-unity-plugins/issues/225). No identified solution but linking so they're easy to re-check for updates if this drags on.

**Comment by npckc** [comment]
Unfortunately Google staff response was simply that when the app version for testing is not available on the Play Store (my comment: I think this would be all app versions since apps are generally only tested before they're available?), the apps are installed manually from the Developer Console, and they asked that any further inquiries be sent through policy support appeals, which has been a bust as well.

I feel like there must have been some kind of Google internal change that has caused this issue but unfortunately sharing the Github issues mentioned above by mal and pointing out that the error of not owning the app is an issue of Google Play's testing conditions has not made any difference, and the appeals I've made have all failed.

Since this is not really a Ren'Py issue but a Google Play issue, I don't know if it's appropriate to continue posting here, but it seems other people have managed to get past this by making sure the game itself has a small playable portion before the fast-follow data is installed or just not using fast-follow and switching everything to install-time instead, so that the Google robots that are checking the apps will not automatically fail the app for not loading.

**Comment by renpytom** [comment]
Do you have a twitter account? I'm in contact with them on twitter, and they seem interested in helping there, but want to loop you in, I'd like to create a group DM with all of us to keep this going.

**Comment by npckc** [comment]
Twitter account is @npckc - I'd be happy to help there if there's anything at all I can do.

**Comment by KakaMigu** [comment]
Well, I tried something, and it really worked! Google Play approved my app!
All I did was reduce the RAM allocation to 2GB. I don't understand why, but it really worked!

**Comment by MK-dev-official** [comment]
How did you reduce the ram?

**Comment by KakaMigu** [comment]
Before you build to app, go to "configure" under "Generate Key", at step 5 it tells you to chose how much RAM do you want to allocate to Gradle, I put 2 GB.
I used to put 4GB, but Google Play rejected the app.
After I changed it to 2GB, Google Play approved the app.
![Capture](https://github.com/renpy/renpy/assets/155226100/d67606b3-71e5-47f8-bba8-d006f340b77f)

**Comment by renpytom** [comment]
This isn't likely the issue - that setting only does anything at your end, when building, not at Google's end. It isn't reflected at all in the built game. 

That being said, it might be possible Google has finally fixed their test process. That would be nice...

**Comment by AjebFLY** [comment]
I'm having the same issue on my end. The weirdest part is that they approved and published the new release without any issue, but when I uploaded a new version an hour after it got approved which only corrected one single grammar mistake and nothing else, I received the message "App Status: Rejected
Your app has been rejected and wasn't published due to the policy issue(s) listed below. If you submitted an update, the previous version of your app is still available on Google Play." 
Since then, everything I've tried (even reducing the number or size of files) has not worked, and I keep getting the rejected for broken functionality email. Fortunately for me the update went through the first time but I don't know what could have happened between these two updates (1 hour after approval) for the testers at Google Play to apparently be faced with the game crashing. It works perfectly on my end and the first update as well so it unfortunately seems to be a Google problem more than a Ren'Py one...

**Comment by renpytom** [comment]
So, the second thing looks like you're submitting a google play build to Amazon, which wouldn't work. You need to make an APK build for Amazon. 

As for google, I suggest working with Google to get more information. I've found their X/Twitter account,@googleplaybiz, seems to be responsive. If you want to add @renpytom to the dms, I can keep an eye and answer some questions.

**Comment by AjebFLY** [comment]
Thanks for your answer, my Amazon build went through with the apk!

As for Google... Honestly couldn't tell what was the problem. After 13 attempts, including 2 rejected appeals, all sending me the same picture of the downloading screen bar stuck at the beginning, it finally got accepted by Google Play. The only thing I changed from the previous unsuccessful attempt was adding a "downloading assets" label in English on the "android-downloading.png" picture, which only had it in French. My guess was that the tester was faced with the screen and couldn't tap anything, and not understanding French, declared it as bugged, hence why I added the sentence, but it's probably unrelated as I explained what that screen was for in my 2 appeals. So I guess the solution to this problem for anyone is just "keep trying until they randomly accept your update" as it's not a Ren'Py issue

**Comment by nomnomnami** [comment]
dropping by to report this has been an issue for my apps as well. most of them get through google's testing after a few tries, and those games appear to work for most users--but one of my smaller games (.aab filesize under 70mb in case it matters) hasn't been able to make it past the "downloading assets" screen and was continuously rejected for broken functionality.

i kept resubmitting thinking it was just a google play issue, but once it finally got through, i tested it on my phone it happened to me too! i left that build up for a few days, but it seems like the game is fully broken for anyone who tries to download it. i took the page down from the play store while i try to build a working version... no luck so far, even when i tried building with a previous version of ren'py.

@renpytom would it help if i add your email as an internal tester? if there's crash reports or something i can send, let me know where to look haha

**Comment by renpytom** [comment]
Sure. I'd be happy to test it, though my  guess is it's a problem on google's end. I can't make them take it seriously.

**Comment by nomnomnami** [comment]
okay i emailed you the testing link earlier but when i tested the same version (1.5.2) just now it suddenly downloaded normally... so nevermind i guess, you're probably right that it's google play's fault after all lol

**Comment by RobertoZaffa** [comment]
Hi everyone,
I'm asking for help here because it's the topic that comes closest to my problem.
I created a game with Renpy and would like to use it on Android phones.
I followed the steps to generate an APK file, installed it on my phone and everything works.
I would now like to publish it on Google Play, but after uploading the .AAB file I have this warning:
"This item may not have a label readable by screen readers".
On my phone, downloading and installing "Signed, universal APK" from Google play is OK but when I run the app it remains blocked with the words "downloading assets..."
I tried to repeat all the steps with a new basic VN just created by Renpy and the error is the same

Versions used:
- Renpy 8.2.1.24030407
- jdk-21.0.2+13

I'll appreciate any suggestion  to solve the problem.
Thanks.
![image](https://github.com/renpy/renpy/assets/76481108/a87eb678-ce6f-4c1f-ac14-e62539b3b06c)
![image](https://github.com/renpy/renpy/assets/76481108/15a197fe-2b33-461f-ae0d-6af6e5a05d6e)

**Comment by stunnings** [comment]
I'm stuck with the same issue. Perhaps adding some interactive buttons (e.g., quit game, etc.) to the screen that appears while downloading the initial assets might help. This could prevent Google Play testers from concluding that the "game has frozen."

**Comment by RubenGarcia** [comment]
Tested on 8.2.1, issue persists.

**Comment by RubenGarcia** [comment]
Tested on renpy-8.2.2.24060703+nightly, app works correctly.
Can anybody else confirm if it works for them too?

**Comment by blackcatstudiosdevelopment** [comment]
I'm still having an issue with 8.2.4.24071501+nightly.

Also, any advice on how to get the logs from Google? So far they've ignore or rejected my request for logs every time I've appealed the rejection.

**Comment by renpytom** [comment]
You might want to try the 8.3 nightlies, but I don't know how to fix problems with google. Making a stink on social media might get you someone who can help.

**Comment by RobertoZaffa** [comment]
I solved my problem with Ren'Py 8.2.3.24061501+nightly. Maybe the cause of your problem is different.

**Comment by blackcatstudiosdevelopment** [comment]
Dumb question while I'm waiting for my inevitable rejection email:
I'm now using 8.3.0.24072105+nightly and I deleted the entire rapt folder and started the Android build fresh. I was looking into the app-build.gradle and noticed there's a whole string of 'no compress' items. I have declared some of these items to be classified in archives. Does the 'no compress' conflict with the archives when building? If so, can I add an `if not renpy.android:` line to handle the error in options.rpy?

```
    build.classify('**~', None)
    build.classify('**.bak', None)
    build.classify('**/.**', None)
    build.classify('**/#**', None)
    build.classify('**/thumbs.db', None)
    build.classify('**/**.txt', None)
    build.classify('**/**.csv', None)
    build.classify('**/**.tab', None)
    build.classify('app stores/**', None)
    build.classify('game/audio/voice/*', None)
    build.classify('game/tl/**', None)
    build.classify('game/**.rpy', None)
    build.classify('game/**.py', None)
    build.classify('game/**.pem', None)

    ## To archive files, classify them as 'archive'.

    build.classify('game/**.png', 'archive')
    build.classify('game/**.webp', 'archive')
    build.classify('game/**.webm', 'archive')
    build.classify('game/**.rpyc', 'archive')
```

**Comment by blackcatstudiosdevelopment** [comment]
My issue is resolved but at what point I do not know. The 'resolution' was that the submission tester wasn't using the most recent submission for testing -_-

**Comment by burning-petals** [comment]
Hi everyone, I've been having the same issue with Google rejecting my game for not loading. It works on actual devices. This problem started when I went from Renpy 7 to Renpy 8 (always the latest versions and nightly). I tried to build the same game (no changes in the script) again with the Renpy 7.7.3 and the game was successfully accepted by Google Play. Could this be an issue of Renpy 8 only, or is it truly a Google thing? Or maybe I was just lucky this time.

I really need it to work before November 1st, otherwise my game will be deleted from the Play Store, since Renpy 7 does not target required API 34 and I can't update my game.

Is there a solution for this issue?

**Comment by blackcatstudiosdevelopment** [comment]
My previous success seems to have been a fluke. I have, however, modified the Fast-Follow setting from 'fast-follow' to 'install-time' in the various .gradle files. Fingers crossed to see if that makes a difference.

**Comment by blackcatstudiosdevelopment** [comment]
Changing to 'install-time' in all the ff# .gradle files seems to have done the trick!

**Comment by burning-petals** [comment]
> Changing to 'install-time' in all the ff# .gradle files seems to have done the trick!

Thanks for the update! I will try the same thing and let everyone know if it works for me as well.

**Comment by renpytom** [comment]
Note that this limits you to 1 gb of data.

**Comment by renpytom** [comment]
Correction - it's 4gb now. I'll change it.

**Comment by renpytom** [comment]
@blackcatstudiosdevelopment 

Did you install the install-time aab on your device? I've been unable to get it working, and what you have seems to be against how Google documents install-time packs to work.

**Comment by blackcatstudiosdevelopment** [comment]
> @blackcatstudiosdevelopment
> 
> Did you install the install-time aab on your device? I've been unable to get it working, and what you have seems to be against how Google documents install-time packs to work.

I’m not entirely certain. My app was rejected for ‘adult content’ quite spontaneously. I assumed that the ‘install-time’ finally solved the issue but at this point I can’t be sure. Quite frankly, I’m done with Google Play at this point. Between the lack of information that they’re ‘allowed’ to provide and now a rejection for adult content that was previously not an issue I’m just done with the whole situation.

Sideloading still works and my end-users are fine with that. I’m tired of fighting a losing battle.
