### ISSUE TITLE
Renpy 8.1.3 web: on iOS, the keyboard doesn't hide automatically after you input the name on Safari.

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#5016]
I'm testing Renpy Web version on iOS, and the keyboard doesn't show or hide automatically when you input the name on Safari.

**Comment by renpytom** [comment]
Does the textbox gain focus? Does the keyboard show when the textbox is shown?

**Comment by SergioAlonsoJr** [comment]
On iOS:
1) I have to manually tap on the input text box to show the keyboard
2) I have to **manually** close the keyboard after inputting the name.

On Android:
1) I have to manually tap on the input text box to show the keyboard
2) The keyboard closes **automatically** after inputting the name.

**Comment by Kassy2048** [comment]
Removing the focus makes the keyboard go away on iOS (see https://github.com/renpy/renpy-build/pull/95).

About the keyboard appearance, it works for me on Android.  On iOS, the text input gets the focus, but the keyboard does not show up. It seems the keyboard will only show up on iOS if we change the focus from a click event handler, which is not possible because RenPy's decision to show the prompt happens after the click event has been processed.
