### ISSUE TITLE
Renpy 8.1.4.23092301+nightly:  On Web, iPad 9 is not being considered a touch device

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#5022]
I made a version of the `quick_menu screen` for touch devices using this code:

```
screen quick_menu():
    variant "touch"
```

It works on iPhone 14 Pro Max and several Android devices on **WEB**, but on iPad 9, the non-touch version of the screen is being loaded.

**Comment by Kassy2048** [comment]
That's because iPad is not detected as a mobile device when Safari uses desktop mode and the "touch" variant [depends on the "mobile" variant](https://github.com/renpy/renpy/blob/0f51948f8005d3a9fa1986a23fb58821280cdc98/renpy/main.py#L272) to prevent bad detection. It should work in mobile mode though (instructions to switch the mode are [here](https://appletoolbox.com/how-to-request-desktop-websites-in-safari-on-iphone-and-ipad/#:~:text=iPhone%20or%20iPad%3A-,Open%20the%20Safari%20app%20on%20your%20iPhone%20or%20iPad.,-Navigate%20to%20the) if you want to try).

I'll make a PR to change the detection logic based on [this](https://github.com/renpy/renpy/issues/4988#issuecomment-1741861613) later on.
