### ISSUE TITLE
Remove Atom from list of editors

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#5077]
Following the EoL of the Atom product last year (and it's numerous bugs that eat projects) I believe it's time to remove it from the list of editors in the launcher.

**Comment by bober-gith** [comment]
I understand, but would it be possible to still use it somehow (even if not put forward officially)? Never ran into bugs, I like the responsiveness/no fuss of it, and tried Visual Code Studio but muscle memory makes me go so much slower on it, just not the same.

**Comment by HorBro38** [comment]
> I understand, but would it be possible to still use it somehow (even if not put forward officially)? Never ran into bugs, I like the responsiveness/no fuss of it, and tried Visual Code Studio but muscle memory makes me go so much slower on it, just not the same.

There is nothing that would prevent you from setting Atom as your default code editor and setting Ren'py to use the system default.

As a side note; we've had numerous (probably 10+ at this point) of Atom eating entire projects so I would be very careful using it.

**Comment by bober-gith** [comment]
If it's possible then it's not really a problem, I just hope it's working just as well with ren'py...

Always a good idea to do a backup everyday, then there is the backup of ren'py, this is already safe enough. Outside of that, I really think most of it probably comes from Windows problems or crashing in the middle of saving a file, it's probably a good idea to put forward Visual Code Studio, maybe it's more robust on backing up files but I think the moment ren'py users will switch massively to visual code studio you will also hear about horror stories of losing a project because of _insert reasons_.

**Comment by Gouvernathor** [comment]
There is precedent with the deprecation of jEdit. If it actively causes issues with users then all the more reasons to stop proposing it for download soon.
