### ISSUE TITLE
Problem with come back to web game on iPhone (Safari)

### ISSUE THREAD

**Issue by Quadina** [renpy/renpy#5118]
I have game generated by "Ren'py Launcher" and have problem with starting it on iPhone (any version) on Safari. After clicking a link to hosted site with generated game, everything works good. After change app on iPhone and come back to Safari blank screen appear and game wont start, even after refresh page.  Thanks to bugsnag I discovered error in console which appear in this moment:
```
./plugin-inline-script-content/inline-script-content.js:149:35
Argument 1 ('shader') to WebGL2RenderingContext.shaderSource must be an instance of WebGLShader
```

Tested:
- Test on other iPhones
- Test on other game code - even demo from SDK
- On Android this error never appear
- Sometime, when I fast switch between apps (and probably Safari didn't do anything with page)  game works

Any idea how to fix that?

**Comment by renpytom** [comment]
I've made several relevant changes since this was filed, and a test shows I can't repeat this on my iPad. Specifically, I'm now restarting the GL context in more cases. 

Can you try any nightly (not nightly build) fix from 2024-01-01 or later, and see if this fixes it for you? 

Nightlies are from https://nightly.renpy.org.

**Comment by Quadina** [comment]
I test in on two iPhones (old 5 and 14) with nightly from 2024-01-01 and problem don't appear new. So, in my opinion fix is done :)

**Comment by renpytom** [comment]
Okay, I'll close this.
