### ISSUE TITLE
Enhanced custom text tags.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#513]
The idea would be to look for text tags (probably beginning with a sigil). When we find one, we find the matching closing tag. We then pass the list of tokens between opening and closing to a function that returns a new list of tokens, which are parsed instead of the original list of tokens.

**Comment by shivanshs9** [comment]
I was wondering if it's possible for the user to write his' own custom text tags... There was a script in the Ren'Py cookbook, but it's not compatible with Ren'Py 6.18... So, maybe, a feature to add your own custom tags, like macros in Kirikiri, will be better...
P.S: By the way, I am happy with the current features of Ren'Py and fully appreciate your hard work in bringing out the true beauty of Ren'Py engine, so don't burden yourself too much!

**Comment by javimat** [comment]
@shivanshs9 : There are already user-defined text tags with some functionality: http://renpy.org/doc/html/text.html#user-defined-text-tags Have you tried that?

**Comment by shivanshs9** [comment]
Well, yeah... Actually, I have tried that... I was looking to apply a long indentation or a long line without using images... 
An example for a long line effect, "There was s{long_line=5}o laughing madly!" or something like that to create a obscure effect... I know there's billion of other ways to achieve this same effect, but I just like the 'macros' feature in Kirikiri, and that's why I suggested to use custom text tags without having to do anything with styles...
It's just an optional feature, but can also help people in future to be able to use their own tags...
