### ISSUE TITLE
Autoreload on i3wm causes game to shrink

### ISSUE THREAD

**Issue by thelordofcorruption** [renpy/renpy#5212]
As title suggests if the game is not set as full screen in-game and the scripts get reloaded (when in autoreload mode), it causes the game after the script reload to get smaller then the game window.
To fix this I have to constantly put the window in full screen and tiled mode again (using i3's window key binds not using in-game options) to make the game occupy the entire game window properly.
To clarify this happens regardless if the window was initially set before the script reload using i3's keybinds as full screen or tiled. New projects generated from Ren'py launcher have the same bug.

I am on Ren'py 8.1.3 (this has happened in previous versions so don't think it's a regression) and I use Arch Linux as my distro and i3 as my window manager.

https://github.com/renpy/renpy/assets/111158601/3a2baf52-d936-408c-a0c1-475892ace888

**Comment by renpytom** [comment]
Do you have any reason to think this is an issue with Ren'Py?

**Comment by thelordofcorruption** [comment]
> Do you have any reason to think this is an issue with Ren'Py?

I tried another game and I am not noticing these issues. Also when full screen mode is selected in-game, after the script reload the game does not shrink at all (but of course window remains in full screen which is not what I want, since I want it to work windowed).

**Comment by renpytom** [comment]
We tracked this down on Discord. 

Ren'Py stores the game's size in the preferences. When the game is in windowed mode, and it restarts (either due to a reload, or due to the game being shut down and restarted), it will shrink that size to match the aspect ratio of the game itself, to eliminate the letterbox/pillarbox bars. 

Your window manager (or compositor, I'm not clear) doesn't seem to be able to handle the window being resized through SDL. I don't think this is an issue with  Ren'Py, but hopefully this will help narrow down the cause.
