### ISSUE TITLE
ATL contained in a button doesn't receive hover/idle events

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#5215]
```rpy
image indicator:
    on idle:
        "#f00"
    on hover:
        "#0f0"

screen test_5132():
    button:
        xysize (500, 500)
        background "#c60"
        add "indicator"
```
The button should be green when hovered and red otherwise, but instead it's orange.
But the ATL events doc section clearly says these ATL events are "Triggered when **button containing this transform**, or a button contained by this transform, enters the named state."

**Comment by renpytom** [comment]
I don't see an obvious problem with: 

```renpy
image indicator:
    on idle:
        "#f00"
    on hover:
        "#0f0"

screen test():
    button:
        xysize (500, 500)
        background "#c60"
        add "indicator"
        action NullAction()

label start:

    scene bg washington
    call screen test

    "..."

    return
```

When I added the action NullAction(), it just worked.

**Comment by DipeshAggarwal** [comment]
I think this is because buttons are insensitive if there is no action specified.

**Comment by shawna-p** [comment]
In 8.1, if you added another child to the button such as `text "Test"`, then the hover/idle events would no longer work, but it appears to be fixed in the latest nightly.

To follow up on this though, if you use "indicator" as the button background, it does not receive events and shows nothing. While I recognize that there are idle_background and hover_background properties and such, it also means that you can't use ATL to transition between the states, such as adjusting the background alpha, or to restart an animation on a state change. This connects to what I want in #5132 as you can achieve this behaviour with a displayable inside the button but not as a button property such as foreground or background.

**Comment by renpytom** [comment]
At least for now, events aren't passed to the button background, but the state is shared when changing button backgrounds.

**Comment by SkyLeite** [comment]
@renpytom Is the behavior of events not being passed to button backgrounds an intentional design decision or a limitation? If the latter, would you welcome PRs addressing it?
