### ISSUE TITLE
Allow f-string like formatting to be opted into on a per-file basis.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#5236]
Since there may be libraries and  games-in-development that use the older formatting.

Basic plan:

- [ ] Add rpy fstring {True/False} as syntax.
- [ ] In the Python compiler, for files that have rpy fstring, All strings with [ in them will be compiled into a child of string that has a .fstring field, which defaults to the file.
- [ ] Check for the .fstring field, use that to detemine the formatting to use.

**Comment by mal** [comment]
My fear is that this risks getting super murky and/or confusing (both in implementation and use) especially once we get into nested interpolation. Given the relatively small incompatibility surface, perhaps a launcher-based lint-like tool to report potential issues when upgrading from version X to current would be a better option that could be further extended in future?

**Comment by renpytom** [comment]
A problem is I don't see a great way to catch potential issues, given that: 

```
"[test[a]]"
```

Is valid in both old and new versions.  I've implemented a fallback mode to try both, which at least lets people migrate one file at a time.

**Comment by Gouvernathor** [comment]
I'm ok with the feature (as an opt-in though), but I'm doubtful about the implementation. creating a custom object for each interpolable string will bloat the memory of some games (whereas we're interning strings to save memory... kinda works against the current).
I think we should try another direction entirely (no idea how), or possibly only do that if the opt-in is opted in. In that case, creators know that they're in a transition process and that whatever memory issue they may have will calm down when then finish upgrading their game.

I think it should be an opt-in (and a compat of course) because it's unlikely that many cases like that are going to occur in your typical game.

**Comment by renpytom** [comment]
I think the fallback based-approach is probably the best way - so the  game can run during the transition. We can then see if we have to produce tools to help people. (Probably during the prerelease.)
