### ISSUE TITLE
With HDR enabled in Windows, in Renpy game in Fullscreen mode, when switching to another app, it appears too dark

### ISSUE THREAD

**Issue by rakleed** [renpy/renpy#5258]
With HDR enabled in Windows 11, in a Renpy game in Fullscreen mode, when switching to another application, it appears too dark. Although the game on Renpy is displayed correctly when switching to it. But even after that, close the game on Renpy, the image will still remain darkened until you turn HDR off and on in Windows settings. There is no such problem with games on other engines. I was unable to record a video of the demonstration.

**Comment by renpytom** [comment]
Ren'Py doesn't do anything to support HDR, so this isn't likely to be a Ren'Py issue but an issue with another portion of your setup.

**Comment by rakleed** [comment]
I have tried many different games and the problem is only with games using the Renpy engine.

**Comment by renpytom** [comment]
I'm sorry, but Ren'Py doesn't currently do anything with HDR settings. I don't know who to contact, but there isn't anything I can do.

**Comment by MatthewAMEL** [comment]
I have had this same problem for years. If I have HDR enabled on the display, when I run anything RenPy in fullscreen mode, it knocks Windows out of HDR.

I have to switch RenPy to window mode, and then disable and reenable HDR in windows. 

Only happens with RenPy. No other engines generate this behavior.

**Comment by renpytom** [comment]
@MatthewAMEL Please file an issue with Microsoft, as Ren'Py doesn't do anything with HDR settings.

**Comment by meepmeepimajeep** [comment]
I've also been experiencing this. With HDR enabled in Windows, launching a Ren'Py game in fullscreen causes an issue where, after closing the game, the desktop remains darkened even though Windows still shows HDR as enabled.

The issue can only be fixed by disabling and re-enabling HDR in Windows settings.

This only happens with Ren'Py games. Other games and applications using different engines do not cause this behavior.

The issue may be related to the way Ren'Py handles fullscreen, the renderer, SDL, or something else in the graphics stack, but Ren'Py is consistently part of the reproduction steps.
