### ISSUE TITLE
Adding an action to open the save directory

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5259]
Similarly to `OpenDirectory()`, adding an action that opens the save directory (`%APPDATA\Roaming\RenPy\<config.save_directory>`) would be beneficial not only for developer tooling, but also for players to troubleshoot any problem.
Adding it to the launcher might be a good idea too. A good place could be in preferences > actions

**Comment by renpytom** [comment]
```renpy
OpenDirectory(config.savedir)
```

Seems like it would work. I don't think there needs to be a dedicated action.

**Comment by Gouvernathor** [comment]
That's because you're using `config.save_directory`, on which [the documentation](https://nightly.renpy.org/doc/config.html#var-config.save_directory) says "To locate the save directory, read [config.savedir](https://nightly.renpy.org/doc/config.html#var-config.savedir) instead of this variable."

On my end (on Windows) the `config.savedir` variable always returns the full (non-normalized...) path to the appdata save directory, as seems to be its job.
