### ISSUE TITLE
Suggestion: GetTooltip() should be able to return tooltips from insensitive objects

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5269]
So I feel like this is unexpected behavior. Buttons won't create any tooltip if they are insensitive. This bugs me, because a user should still know what a button does, even though they cannot press it at the time.

Can `GetTooltip()` get a keyword argument, so it will return tooltips from insensitive objects if wanted? That would be great. :)

**Comment by Gouvernathor** [comment]
The reason insensitive objects don't have tooltips (in the current state of things) is because the tooltip activates on focusable things, and insensitive things can't be focused. getTooltip() (without parameters) returns the tooltip of the currently focused thing, so...

Though the use case for tooltipping an insensitive button, to tell the player precisely why it's insensitive, could be a good thing to support because I think it's relatively common. Maybe treat the button like a mousearea of sorts.

**Comment by renpytom** [comment]
Fundamentally: No it shouldn't. 

At the end of the day, either something is focusable or it's not, and treating non-focusable things as focusable doesn't seem like a good idea.
