### ISSUE TITLE
Live2D **properties not working

### ISSUE THREAD

**Issue by ParadoxalDeviant** [renpy/renpy#5302]
Hoy  o/

I'm working on a CG that is a live2d animation and I want it to be slightly to the right when displayed. No biggie, just have to use some transform with a `xoffset`, `xalign` or `xpos` in it. But there's a better way to always apply an offset to my animated image:
`Live2D()` constructor inherit from `renpy.display.displayable.Displayable` and therefore can take displayable's parameters (**properties), such as `xoffset`, `xalign` or `xpos`! It works when I do `image test = Image('images/test.png', xoffset=640)`, so I must be able to do the same with Live2D:
`image test_anim = Live2D('anims/test_anim', xoffset=640)`

But it does not work..

`renpy.get_registered_image('test_anim').style.properties` tells me that `xoffset=640` is indeed registered, but for some reason not apply to the displayable.

So yeah there's other solutions to do what I want but I wonder why this one does not work... And if it should, then that looks like an issue  :/

**Comment by Gouvernathor** [comment]
You reference a lot of undocumented code, but yes, `**properties` is supposed to enable arbitrary style properties being passed, since it's specified in the [Language Basics](https://www.renpy.org/doc/html/language_basics.html#Sample) page as I'm sure everyone is aware.
Thanks for starting the debughing process though.
