### ISSUE TITLE
Parsing error if image is a screen argument

### ISSUE THREAD

**Issue by WindChimesGames** [renpy/renpy#5366]
I discovered an issue that arises if a screen has **image** as a screen argument. It's reproducible in a fresh Ren'Py project and adding the following: 
```
screen test_screen(image=None):
    add Solid("#FFF")
```

The error: 

```
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/screens.rpy", line 1614: expected 'name' not found.
    screen test_screen(image=None):
                       ^

Ren'Py Version: Ren'Py 8.2.0.24012702
Fri Feb 16 23:02:50 2024
```

**Comment by Gouvernathor** [comment]
`image` is a statement name, so that's expected.

**Comment by shawna-p** [comment]
I disagree that it's expected; `image` is not in https://www.renpy.org/doc/html/reserved.html#reserved-names and `image` can be used perfectly fine as an argument to a Python function or as a variable name. It's a reasonable name for an argument to a screen in the same way as you can pass in arguments named `pos` or `xysize`. It should be possible to take the context of "this is a keyword argument" into account to pick it out from a regular `image eileen = "eileen.png"`.

**Comment by Gouvernathor** [comment]
In Python, you can have `somobj.__dict__["def"] = 1`, yet you can't have `somobj.def = 1`, because `def` is a statement.
Reserved names in our doc are, I think, actual valid variable names which we already use. I don't think `transform` is one of them for example, or `scene` or `hide`, yet they are renpy statement names so, in that way, reserved.
We can't ban image as a variable name in all python because that would require way too much computations, but I would consider it a bad idea.

Having property names as variables is fine and good and supported. It's like the kwargs of the `print` function, it's expected in python that you can name a variable that way. Same for the `_` in python pattern-matching, it's at the very best a "soft keyword".

Maybe we could choose to allow it in screen signatures, but it may cause grammar ambiguity at screen call time or other random place you would need to pass those keywords, so I think it should stay unsupported.

**Comment by shawna-p** [comment]
In such a case, is it at least possible to include a better error message indicating it can't be used for a screen or label argument?

**Comment by renpytom** [comment]
I relaxed what Ren'Py considers to be a keyword a bit. In the past, there were more Ren'Py keywords, but having seen how the language has been evolving, it's pretty clear that statement names don't really need to be keywords throughout Ren'Py.
