### ISSUE TITLE
Words or entire sections of text sometimes shift when using extend

### ISSUE THREAD

**Issue by Jaybe-Games** [renpy/renpy#5371]
The problem is definitely related to the ctc feature. The word does not fit into the row with the ctc image and is moved to the next row. If the extend text is then displayed, the word moves to the first line because the ctc image is now somewhere else. it would be better if the ctc image could always ignore the text width so that readability is not negatively affected.

With ctc: 

https://github.com/renpy/renpy/assets/148782203/068f2da4-c866-4df3-8a2a-73336b2f87c9

Without ctc:

https://github.com/renpy/renpy/assets/148782203/ea78ed36-349a-4e8b-aab3-f755a1da5554

**Comment by renpytom** [comment]
Actually, no, it's not. But there isn't a very good way of fixing this, short of laying out all text with the CTC enabled. I suggest using the default CTC screen, rather than nestled CTC, as it doesn't have this problem.

**Comment by Gouvernathor** [comment]
I think that's an expected behavior. A workaround could be to put a space at the end of the pre-extend line that will enable a line break before the nestled CTC, as well as making sure not to use the "subtitle" [layout](https://www.renpy.org/doc/html/style_properties.html#style-property-layout) style property which could mess with that.

**Comment by renpytom** [comment]
I don't think this is likely to every be fixed - the combination of extend and nestled CTC is just incompatible. As I don't see a way to reconcile these two features, I'm closing the issue.
