### ISSUE TITLE
disable antialiasing and change size of image based font (bmfont)

### ISSUE THREAD

**Issue by greenboxer1** [renpy/renpy#5420]
I'm going to make a pixel novel. so I need a pixel font. The window size is 256x384, when using a regular font with "antialias = False" and a small size, the font is rendered rasterly (not pixelated). So I decided to use a font based on images. The font turned out to be pixelated, but the problem is that it is blurry 
![pythonw_8ZPXwuUdqj](https://github.com/renpy/renpy/assets/61281427/495c4b5d-ff54-42bd-893b-64c7dea1ac6c)
(there is no aliasing in the picture with the font)
![Photoshop_W4UwYpa0W3](https://github.com/renpy/renpy/assets/61281427/f688b6d9-bd20-4aa2-91d4-0421810dc520)
 Also I cannot change its size either up or down, even if I change it by a factor of two.

**Comment by renpytom** [comment]
Pixel fonts are displayed as images, so many font settings (like antialias) are false. You can put renpy in nearest neighbor mode (config.nearest_neighbor) for the equivalent for an image. 

You can't change the size in Ren'Py, but you could scale the font in a bmfont editor. 

In general, Ren'Py isn't well-tuned for obsolete sizes like the one you've chosen, so it's your responsibility to take care of that tuning. 

I don't see an actual issue here.

**Comment by greenboxer1** [comment]
For those who have the same problem, here is a solution that works even with ordinary raster fonts:
```
define config.nearest_neighbor = True
define config.use_drawable_resolution = False
style default:
    antialias False
```
![mspaint_gbQmZseSS4](https://github.com/renpy/renpy/assets/61281427/e52dc36d-c258-4a18-bd09-4dbfb066cf4e)
