### ISSUE TITLE
Move saves and searchpath outside of ANDROID_PUBLIC

### ISSUE THREAD

**Issue by Galo223344** [renpy/renpy#5432]
Ever since Android 13 Google has been locking down the /android/data/ folder more and now you _must_ use a computer to access this folder. This is not ideal for:
1. Accessing your save files
2. Installing DLC/Expansions/Mods
This is because most people that play on mobile phones don't have access to a computer. What I suggest is changing it to something like `/storage/emulated/renpy/[gamename]` or  `/storage/emulated/games/renpy/[gamename]`

Pros:
1. Save files won't get deleted when you uninstall the app
2. Save files can persist between demo and full versions of a game
3. Multi-persistant can finally be implemented in Android
4. Save files can be backed up or restored
5. Expansions or mods can be loaded

Cons:
1. Renpy will require the access storage permission (I think)
2. Save files won't get deleted when you uninstall the app (Which can be a con if they are big and the user doesn't want to actually keep them)

**Comment by qTich** [comment]
Let me start with the fact that for your game you can do this by patching `PythonSDLActivity.java`.

I will continue by saying that, in my opinion, what you highlighted as advantages is not them.
1-2. I doubt that many people will want to leave garbage behind after uninstalling an app.
Again, if you update the game by installing a new apk, then there should be no problems, because the package is updated without deleting user content.
3. This may be useful, but enough changes have been made that it is possible to have a small installation package, and download additional content from the server into it.
4. Again, you can do this for yourself through the patch.
5. This is already in the game, via download. The directory can also be added to `predefined_searchpath`, which again can be useful when patching.

Additionally, the change will force all games to require recording permission even though they may not want to, which could discourage players.

**Comment by renpytom** [comment]
I think @qTich has this right here - we don't need to do our own thing on Android. And permission dialogues are a no-go. So this isn't going anywhere.

**Comment by Mjng** [comment]
Well for me it is a must. While I only test game in Android I can not continue this caused by android 14 restrictions. Maybe an import or export function can be an in between solution to this

**Comment by renpytom** [comment]
Ren'Py Sync is that import/export solution.

**Comment by Mjng** [comment]
Well, but the sad issue is that the Sync folder is inside the Files or Saves folder which makes it useless unless somehow this folder is made public

**Comment by Mjng** [comment]
On my Android tablet with 14 i am not able to copy the saves folder anymore. I guess Google closed up all workarounds in the latest security updates.
