### ISSUE TITLE
Write screenshots to a system-specific folder if we can't write the base directory.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#548]

**Comment by apoleon** [comment]
Hello,

this is an issue for Linux/BSD distributions because RenPy will always be installed into a read-only system directory under either /usr/share, /usr/share/games or /usr/local.

Is there a recommended way to work around this issue by patching the sources to always save screenshots in the user's home directory e.g. ~/.renpy/screenshots for now?
