### ISSUE TITLE
Surfacing depreciated syntax to developers

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#5532]
We see the image manipulators come up quite a bit in the discord (usually from newer users copying code that is 10+ years old), and was thinking maybe surfacing the fact that they are depreciated to them would be useful.  A few of us had some possible ideas:

- Flagging these in lint (by default), with an option in the launcher to disable.

- Alternatively, a different config option that throws an error/warning.  Obviously quite more intrusive, but more easily seen - possibly implemented similar to `config.check_conflicting_properties`?

This could be used for other depreciated code than just image manipulators; but that's the one that comes up a lot.

**Comment by KiloOscarSix** [comment]
I suspect a more intrusive method, like throwing an error, will have to be used to see a meaningful change. 
I don't see new players checking lint before asking for help with copied code.

**Comment by Gouvernathor** [comment]
These are already flagged by the renpy extension in VSCode.
The im elements are still in use internally, in particular Image which is available in the general store is an alias for something in the im module. So we can't just make some of them raise errors at execution.
What we would need are accesses to the im object (module) that's exposed in the main store, _except_ in files used by renpy, _except_ im.Data which has no equivalent.
And since the transform blur is ugly (see #4442), many people are using im.Blur as well and I think it's a valid use.

About check_conflicting_properties : the reason it raises an error is because conflicting properties had always been something that the doc warned against, whereas the im module was documented as a feature for a long time.
We don't usually have a policy of forcing people to using Ren'Py as documented : if Ren'Py is open-source, you may do what you want with it. What we do is that we do not _support_ (i.e accept as issues considered as bugs) undocumented uses of things.
I'd sort-of advocate refusing to help people who keep using the im module (other than the two acceptable uses above), which can be seen as mean but raising exceptions on people can be worse.

And as far as lint is concerned, it wouldn't be easy to add such a check without trampling the performance of all the im objects (which, again, are used internally). But if possible, that should be done.

**Comment by renpytom** [comment]
We could certainly make the obsolete ones raise errors, while leaving im.Image alone.
