### ISSUE TITLE
Detached layer `Window()` inherits 'say screen' window style

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5625]
While trying out the detached layers example from the docs I was very confused as to why the `tv` image was unexpectedly mirroring the letterbox-like size and styling of the `say` Window, and how to restore its expected proportions. Setting `width` and `height` did nothing of course, and playing with `xsize` and `ysize` revealed the `say` window background once I removed the `background='#000'` argument. In the end I fixed it by setting `style="default"` as I figured it was being controlled by the `window` style. I noticed this on Ren'Py 8.2.3 but the behavior seems to go back further.

This seems like unintended behavior, but if it can't be changed, could the documentation at least be updated to include `style="default"` in the arguments to `image tv = Window(...)`?

**Comment by mal** [comment]
It's due to this style definition in the default project template:

https://github.com/renpy/renpy/blob/a1eeda4074c430c907dd59e78be11b35b03dba8a/gui/game/screens.rpy#L133-L139

You can change the first line (in your project's `game/screens.rpy`) to `style say_window:` if you want it to apply only to the say window rather than _all_ windows, that way you don't need the `style="default"` override.

**Comment by paranormalized-encryptid** [comment]
Yeah I know, but I just feel like adding `style="default"` to the example in the docs would be useful (and presumably the easiest way) to ensure that the example works out of the box.
