### ISSUE TITLE
CDD canvas, how to access pixels?

### ISSUE THREAD

**Issue by ZusYar** [renpy/renpy#5644]
The docs in Render.canvas() method mention this
`Canvas objects also have a get_surface() method that returns the pygame Surface underlying the canvas.`

pygame Surface has many things, for example, get_at / set_at.
Question is, it's not very clear how to use get_at. Sample code
```py

        def render(self, width, height, st, at):
            new_render = renpy.Render(width, height)

            child_render = renpy.render(self.background, width, height, st, at)
            child_width, child_height = map(int, child_render.get_size())

            canvas = child_render.canvas()
            bitmap = canvas.get_surface()

            bitmap.lock()
            for x in range(child_width):
                for y in range(child_height):
                    color = bitmap.get_at((x, y))
 
                    # Now here no color manipulations work, because it's always (0, 0, 0, 0)

                    bitmap.set_at((x, y), color)
            bitmap.unlock()

            new_render.blit(bitmap, (0, 0))
            return new_render

```

Intiguing thing is that if i manually set pixels via set_at, i can access it with get_at, no problems.
Mybe there is a more detailed usage note somewhere?

**Comment by renpytom** [comment]
Canvas is its own thing - it doesn't access rendered displayables, just the surface containing the canvas. There's a new function in Ren'Py 8.3, renpy.render_to_surface, that can do this, but because it has to send data from the GPU to the CPU, it'll be slow. 

Fundamentally, though, retrieving the actual value of a pixel like this is a bad idea, and you should avoid doing it.
