### ISSUE TITLE
An action similar to `ShowMenu`

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#5702]
I have an in-game phone with multiple screens including a music player screen, but when I close them, the music from the player stops playing. I actively use `ShowMenu` to easily hide all the game related screens for performance reasons and I also modify labels in `common/00gamemenu.rpy` to disable `config.game_menu_music` when needed.

It would be awesome to have an action similar to `ShowMenu` that temporarily hides other screens, doesn't stop game audio and doesn't play `config.game_menu_music`.

**Comment by mal** [comment]
If the phone is "in-game" then you really ought to be using `Show` (potentially with a modal screen) rather than `ShowMenu`. Altering game state (i.e. currently playing music) in a separate context is a bad idea as it often breaks the rollback/roll-forward feature even if you do manage work around the intentional sandboxing of contexts to make it "stick".
