### ISSUE TITLE
Question about calling JavaScript functions in Web-version

### ISSUE THREAD

**Issue by MelomanSharp** [renpy/renpy#5761]
As far as I understand from the documentation, Javascript functions defined in index.html can be called from ren'py code  in the web version via the emscripten module. But it seems that either I misunderstand something, or I'm not defining functions or their calls correctly. For example:

index.html:

```
<head>
<script>
    function writesomething(){
    console.log('Something');
     }
  </script>
</head>
```

script.rpy:

```

init python:
 if renpy.emscripten:
        import emscripten

  def Writesomething():
        renpy.pause(0.1)  
        emscripten.run_script('writesomething()')
        
label start:
    $ Writesomething() 
```

But of course, if I call Writesomething() now, the browser console writes that 'writesomething() not defined at eval'. Maybe I could pass the body of writesomething() directly as a parameter to emscripten.run_script, but I have other functions that depend on third-party javascript files plugged into index.html, so that's not an option for me.

How to do this properly?

**Comment by renpytom** [comment]
I'm unable to repeat this, which makes me think the problem is more in how index.html is being edited than in Ren'Py being able to call the function. Can you describe how you're making the edits to index.html, and perhaps post the edited file?

**Comment by Kassy2048** [comment]
If you can't call `writesomething()` from the browser console, then you made a mistake while modifying the HTML code indeed.

Changing the generated "index.html" is cumbersome though, because it is minified. An alternative way is to put all your JS code in a dedicated file and load it in an `init python` block:
```js
/* myscript.js */

function writesomething() {
    console.log('Something');
}
```

```rpy
# script.rpy

init python:
    if renpy.emscripten:
        import emscripten
        emscripten.run_script('{' +
            'let s = document.createElement("script");' +
            's.src = "myscript.js";' +
            'document.head.appendChild(s);' +
            '}'
        )

    def Writesomething():
        renpy.pause(0.1)
        emscripten.run_script('writesomething()')

label start:
    $ Writesomething()
```

The main caveat is that the script will be loaded asynchronously, so you have no guarantee your JS function will be ready when you call it from python (you can listen for the "load" event to be sure, but that makes the code more complex then).
