### ISSUE TITLE
Steam Connection Error For RenPy Release 8.3.2

### ISSUE THREAD

**Issue by avantgde** [renpy/renpy#5791]
Launching a Steam connection seems to fail on release 8.3.2 & 8.3.1, and not on older versions like 8.3.0 or 8.2.3, which I tested.
The error is produced in log,txt as:
Failed to initialize steam: AttributeError("function 'SteamAPI_ISteamClient_GetISteamAppList' not found")

**Comment by danac78** [comment]
@avantgde Two things to try. Update to the latest nightly fix or delete steam_api64.dll (in lib\py3-windows-x86-64 of the Renpy SDK). Restart Steam, go to Preferences, Install Libraries, and download the Steam Support again.I did that and it initialized it rather than give that error.

Would it be possible to add a function like "Update Steam Library" so it can download and install a new version of the DLL rather than having us manually do it? :)

**Comment by renpytom** [comment]
I've been unable to repeat this, though there were some issues a while about that could have caused updates to fail. Does it work if you reinstall Steam, as @danac78 indicated. 

@danac78 In the latest versions of Ren'Py, this is done by default through the DLC system when Ren'Py updates.

**Comment by avantgde** [comment]
Updating to the nightly fix fixed it for me.

**Comment by danac78** [comment]
@renpytom Ok. I will assume something just didn't download correctly in this instance.:)
