### ISSUE TITLE
[Documentation]: Add Version Annotations for Features and Changes to Them

### ISSUE THREAD

**Issue by juniorthejunior** [renpy/renpy#5792]
Currently, we do not have any indicators in the documentation, in a feature's section, about when that feature was added to Ren'Py or had its behavior changed. This would be a nice, quickly-accessible bit of information for all creators for a variety of reasons: from reduced chances of confusion for creators who are on older SDKs and prone to following incompatible instructions, to advanced ones keeping easier track of the compatibility of their extensions (CDDs, frameworks, tools, etc.) with Ren'Py, as well as other general benefits.

It would be great if we could adopt a similar approach to that of the official Python documentation, where simple annotations such as “_Added in version 3.3_” and “_Changed in version 3.3:_ (description of the change)” in a feature's section let developers keep track of things quickly and efficiently.

The changelogs exist, but sifting through them is generally somewhat cumbersome as they lack a consistent format/structure.
Creators should also ideally always be on the latest SDK version, but I'd argue these annotations would perhaps even motivate, or at least remind them to do so. Since there is no solid channel for notifying existing creators of new SDK releases, _creators are often not even aware that an update is available;_ these annotations could potentially also serve as soft reminders as they browse the documentation.

Overall this is more of a QoL feature, it isn't some massive deal-breaker, but I think it would be a nice detail to have.

**Comment by renpytom** [comment]
I don't platy to do this, as I drop support for older SDKs when a new one comes out. Python has a much larger team working on it, which is why they're able to have LTS releases. Ren'Py really isn't at that point. I don't want to encourage people to use older, unsupported releases. 

So I'm closing this as not planned.

**Comment by shawna-p** [comment]
Knowing when a feature was added is a big help when debugging problems someone's having. Sometimes they just haven't updated for a while and it's unclear if a feature was recently added, so it takes much longer to figure out that the code is not wrong and they need to update. I don't think indicating when a feature was added has anything to do with supporting or not supporting older versions.

**Comment by renpytom** [comment]
> I don't think indicating when a feature was added has anything to do with supporting or not supporting older versions.

I do think this - since it's basically saying "you can make a decision which version to run" rather than "if you're not on a supported version, update." 

This is not the sort of thing I want to spend my limited time on, since it's tedious. If someone else wants to maintain a database of these annotations, they can.
