### ISSUE TITLE
Steam Achievements Not Unlocking in 8.3.2

### ISSUE THREAD

**Issue by HusbandoGoddess** [renpy/renpy#5820]
Hi! I wanted to make you aware that Ren'Py 8.3.2 has an issue with Steam where it cannot recognize achievements. While testing for my build for its upcoming release, I was running into issues getting the pop-up to appear through Steam. I had the Steam library installed, defined the Steam ID, defined the achievements, and added in the achievement.grant() and achievement.sync() wherever needed, but to no avail.

However, when downgrading the software to at least Ren'Py version 8.2.2 and uploading the new build with that, upon start up I was able to unlock 5 out of the 10 achievements I tested for!

P.S. This may be unrelated, but also on Ren'Py 8.3.2. I had a weird issue where on the Steam version for the game, the window_icon could not be found unless it was unarchived. Downgrading fixed this issue!

**Comment by danac78** [comment]
Have you tried the latest fix (nightly fix)?

**Comment by danac78** [comment]
I have done the following on 8.3.3.24092903+nightlyupdate (fix branch).

1. achievement.clear()
2. achievement.sync() to send a clear list to my Steam Achievement list.
3. I verified that my Steam Achievements for my game were blank on Steam.
4. Ran a special function I made to put them back in for testing purposes :)
5. All 86 went back in.

**Comment by HusbandoGoddess** [comment]
Oooo awesome! I wasn't able to test it yet, but I'm really glad the nightly build has the fixes. I was going insane early this morning looking at my code, haha! Thank you so much for your help and testing. :) <3

**Comment by danac78** [comment]
@HusbandoGoddess I am Not sure how your code is, but it sounds, based on your description, that you are writing achievement.grant and achievement.sync in multiple places within the code. One thing I did to avoid repeating that writing over and over was put it in a python function like this:

`
init python:
   def SteamAchieveCheck(achieve):
       if not achievement.has(achieve): #checks to see if the achievement has already been granted and run if it has not.
           achievement.grant(achieve)
           achievement.sync()
`
Then you can put $SteamAchieveCheck("APIofAchievement") (or whatever you want to name it) in a place where you need it to reduce hunting it down.:) Another reason to do this is that it simplifies it on screen as well because you can write action Function(SteamAchieveCheck,"APIofAchievement") :) Hoping to help the code drive you a little less insane in the morning.:)

**Comment by renpytom** [comment]
You should not be requiered to write achievement.sync, ever - it's there for some odd cases, like a non-steam game becoming a steam game. Even there, Ren'Py  should be doing this automatically. 

Is there an underlying issue here?

**Comment by HusbandoGoddess** [comment]
I only wrote achievement.sync() after every achievement.grant() after looking up some tutorials from other devs. But it's good to know that it's not needed every time! :)

**Comment by renpytom** [comment]
Okay, closing this.
