### ISSUE TITLE
Lint not seeing object as a transform

### ISSUE THREAD

**Issue by danac78** [renpy/renpy#5833]
Ok, I had a case where I did this:

```
$temppydict = {
        True:vpunch,
        False:shake555
    }
    $tempat = temppydict[c]

scene expression Composite((1920,1080),(0,0),ConditionSwitch("c","n2 emily pool 03 sexy base","not c","n2 emily pool 03 angry sfw"),(0,0),ConditionSwitch("c and not passNude","n2 emily pool 03 sexy nsfw","c and passNude","n2 emily pool 03 sexy sfw","not c","transblack")) at tempat
```

c is declared False or True above this. The purpose of tempat is to get the correct transform (vpunch or shake555, which is a predefined Shake() with a certain intensity and duration). 

It works, but Lint is reporting a problem "at tempat" not being evaluated. I was able to fix this by:

```
transform tempat:
     xpos 0
```
And the message is gone, but this seems like a useless piece of code because it would be replaced by objects shake555 or vpunch. Is this correct what Lint is doing?

**Comment by renpytom** [comment]
Yes. 

Lint isn't perfect, it's there to find errors, but it can't actually play through the game, and it doesn't run Python blocks at all. So what's happening there is that it sees a scene, sees that tempat hasn't been set, and errors. 

You can create a transform like that, but probably better would be something like: 

```renpy
default tempat = vpunch
```

At the  end of the day, lint is a compromise (which is why it doesn't stop the game from running, like true errors do). 

If you had written: 

```renpy
scene ... at tempart
```

Then without lint, that error would go unnoticed. 

(You should also strongly consider layered images rather than the Composite/ConditionSwitch mess.

**Comment by danac78** [comment]
@renpytom Ok, make sense. As far as Layered Image, it doesn't make sense in the context I was using the Composite Conditionswitch.in this case. :)
