### ISSUE TITLE
requests cannot use `socks` proxies

### ISSUE THREAD

**Issue by qTich** [renpy/renpy#5842]
```py
InvalidSchema('Missing dependencies for SOCKS support.')
```

**Comment by renpytom** [comment]
What's the use case for a SOCKS proxy over a HTTP proxy? SOCKS is pretty obsolete, isn't it? 

I ask because support for SOCKS isn't included in Python by defaulty - we'd have to take another dependency to add it.

**Comment by qTich** [comment]
I can't judge about obsolete, however, when using `socks` proxy in the system,
any request will be discarded inside `fetch_requests`.

**Comment by renpytom** [comment]
Sure, but I guess - were you using a socks proxy? Was someone with your game? It just feels weird to still be using a socks proxy, and I'm wondering how you found out that it was being used.

**Comment by Kassy2048** [comment]
For non-technical users, the most common use of SOCKS proxies is probably TOR, since the main network interface to the TOR client is SOCKS. Some Ren'Py stories contain topics that are considered illegal in some authoritarian countries, so it may make sense to use TOR in this context. Whether or not this is enough to add an extra dependency, I don't know.

**Comment by renpytom** [comment]
I added support, in both the fix and master branches. 

I haven't been able to test it as I don't have a socks proxy.
