### ISSUE TITLE
Live2D To IOS Shows An Error When Attempt To Open On Phone

### ISSUE THREAD

**Issue by AnonymousFoo1** [renpy/renpy#5857]
Hey Guys, so Ive tried multiple different renpy builds so far none of which are working for me atm. Found a page mentionibg adding in 2 lines in live2d.rpy didnt work for me either. Anyone have any ideas on how to get it fixed? Pics below. 
![image](https://github.com/user-attachments/assets/89fc31ef-ad50-4bb1-9996-4104acf27f44)
![image](https://github.com/user-attachments/assets/10499ba5-375d-4579-bb63-c462c991bfa9)

**Comment by qTich** [comment]
I think only someone who develops for `iOS` can help you,
because as far as I understand, linking `Live2D` library is different there.

**Comment by renpytom** [comment]
For it to have a chance of working, you need to drag the iOS Live2D libraries into the project. (I'm not great at Xcode, so I'm not 100% sure of how to do this.)

**Comment by AnonymousFoo1** [comment]
Appreciate the response guys. Would you happen to know which folder in the Renpy folder the Live2D libraries are in for me to drag them across into the project folder? Im not the most adept Xcode user myself either tbh so still figuring a lot of things out

**Comment by renpytom** [comment]
Ren'Py doesn't install them itself. 

The libraries are in the cubism sdk for native download, in Core/lib/ios .

**Comment by devmlew** [comment]
The cubism sdk only has x86 support for the simulator builds if I remember correctly. So you will only be able to test your game on a real device once you have linked the correct library. (Assuming you're on Apple Silicon)

You can link the library under "Build Settings", "Other Linker Flags" for the target. You'll see the Ren'Py libraries here as well. You will also need to verify that libLive2DCubismCore.a can be found in the Library Search Paths.

Based off of a project built from the Ren'Py SDK, you can copy Core/lib/iOS/Release-iphoneos/libLive2DCubismCore.a (from the native cubism sdk) into your project/prebuilt/release folder. Add -lLive2DCubismCore to the Other Linker Flags for Debug -> Any iOS SDK and Release.

Xcode might strip all of the symbols from the static library when you build so if you are still having issues then you can try to do a force_load of the library. You can do this by adding two entries into the Other Linker Flags like below.

-force_load
-$(PROJECT_DIR)/prebuilt/release/libLive2DCubismCore.a 

I personally use a framework. If you have the experience, you should build one and link that instead. That way you don't have to manage multiple debug/release libraries.

Since you're using an older version of Ren'Py, you will still need to make sure live2d.py is updated for this issue #5502 

I hope this helps!

**Comment by AnonymousFoo1** [comment]
Appreciate the responses guys. Still haven't been able to get it running properly on my iPhone though.

**Comment by AnonymousFoo1** [comment]
> The cubism sdk only has x86 support for the simulator builds if I remember correctly. So you will only be able to test your game on a real device once you have linked the correct library. (Assuming you're on Apple Silicon)
> 
> You can link the library under "Build Settings", "Other Linker Flags" for the target. You'll see the Ren'Py libraries here as well. You will also need to verify that libLive2DCubismCore.a can be found in the Library Search Paths.
> 
> Based off of a project built from the Ren'Py SDK, you can copy Core/lib/iOS/Release-iphoneos/libLive2DCubismCore.a (from the native cubism sdk) into your project/prebuilt/release folder. Add -lLive2DCubismCore to the Other Linker Flags for Debug -> Any iOS SDK and Release.
> 
> Xcode might strip all of the symbols from the static library when you build so if you are still having issues then you can try to do a force_load of the library. You can do this by adding two entries into the Other Linker Flags like below.
> 
> -force_load -$(PROJECT_DIR)/prebuilt/release/libLive2DCubismCore.a
> 
> I personally use a framework. If you have the experience, you should build one and link that instead. That way you don't have to manage multiple debug/release libraries.
> 
> Since you're using an older version of Ren'Py, you will still need to make sure live2d.py is updated for this issue #5502
> 
> I hope this helps!

Appreciate the detailed response :). added -|Live2DCubismCore to both the Debug and the Release option under "Other Linker Flags" but still got the same error message from the screenshot. So I then added -force_load
-$(PROJECT_DIR)/prebuilt/release/libLive2DCubismCore.a to both the Debug and Release options aswell (replaced release with debug for the debug option) I now get the error message       Build input file cannot be found: '/Users/MacbookM1/Documents/Renpy Collection/Xcode Project List/Survival The Night/-/Users/macbookM1/Documents/Renpy Collection/Xcode Project List/Survival The Night/prebuilt/debug/libLive2DCubismCore.a'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?             (P.S Ive added the static files to my projects prebuilt folder too the "Debug-iphoneos" libLive2DCubismCore.a into the debug folder and the "Release-Iphoneos" one into the release folder)                       Any Ideas on what went wrong?

**Comment by devmlew** [comment]
Remove the "-" before the $(PROJECT_DIR)/prebuilt/release/libLive2DCubismCore.a

I made a typo.

**Comment by AnonymousFoo1** [comment]
> Remove the "-" before the $(PROJECT_DIR)/prebuilt/release/libLive2DCubismCore.a
> 
> I made a typo.

Thank you very much that got it sorted. Thanks everyone who responded @qTich @renpytom @devmlew  grateful for the help I got guys :)
