### ISSUE TITLE
Revisit PyExpr and PyCode

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#5940]
At the moment, all PyCode and PyExpr instances in my project take up 40MB of memory, which is ~5% of the total memory used by the project. This is not a big deal, but since to store column offset for PEP 657 I most likely will need to add another slot, and because it is likely that I will intern NAME tokens in tokenizer, and PyExpr later creates new string, I was wondering if we can reimplement PyExpr and PyCode.

My idea for PyExpr is to do something like
```py
# Dict from interned string to list of tuples of PyExpr metadata.
# Potentially can be stored as part of .rpyb file and loaded lazily
# because after it is compiled it only needed if exec failed.
py_expr_locations = {}
class PyExpr:
    __slots__ = ["expr", "metadata_index"]

    expr: str  # interned string
    metadata_index: int  # index of instance metadata in a dict above

    __str__ -> self.expr

    # metadata are getters
```

And for PyCode, we don't need to store any additional data on the instance, so it can be a subclass of PyExpr, e.g.
```py
class PyCode(PyExpr):
    mode: ClassVar["eval" | "exec" | "hide"]

    # source, filename, lineno, etc. are getters

    bytecode -> renpy.python.py_compile_cache[... self.expr]

class PyEvalCode(PyCode):
    mode = "eval"
...
```
And for both classes its compiling, cache keys, etc are resposibility of `py_compile` and `Script.update_bytecode`.

**Comment by renpytom** [comment]
I've thought about it a bit, and I'm not really a fan of the change to PyExpr. I don't love that there doesn't seem to be a way to ensure that indexes into metadata_index are unique, given that py_expr_locations are shared between multiple files. 

Metadata_index can't be stored as part of the .rpyb file, because that file can be deleted without consequence - and if you don't have it, you then can't load the .rpyc file. This happens when upgrading Python versions, for example. 

We do have some low-hanging fruit that we can take advantage of without radically changing PyExpr. 

Probably the best thing to do would be to move it into Cython, so that linenumber and column could be stored as, say, a unsigned integer for line number and an unsigned short for column number. That would save over 28 bytes per PyExpr. More if we add the column field. 

We can also explore different ways to pickle new-PyExpr to reduce loading times. 

I need to look more at PyCode to see how much of it is still required. A lot of PyCode is to make hashing fast, but that may not be necessary anymore, or perhaps could be replaced by the identity of an interned string, something like that.

**Comment by Andykl** [comment]
So, I played around with this issue. I pushed two branches with different approaches. 
`PyCode` is really not needed anymore, it only had one meaningfull method to get its hash, and all this logic can be moved to `Script` where it was used.
But because it is pickled with `__getstate__` there is no easy way to convert it.

With `PyExpr` however, there is even better way to store stuff than your idea - we don't need to store it anywhere, because it is avaliable from the code itself. In both branches, I pass metadata to compiler, and retviete it from result code, which is one slot, instead of current 3.

1. https://github.com/renpy/renpy/blob/6b88086f0d970c58791d7608288076d5d0d84ae5/renpy/ast.py#L85-L123
In first branch `PyExpr` is a subclass of object, and source is interned string in slot. Because of that, several `PyExpr` can refer the same source, and that happens very often (e.g. 20% of all PyExpr in my project is a var-name of main character). But the main drawback is that even in Ren'Py code base a lot of code assume expr is a string (or at least has string methods), and changing that would be major incompatiable change in parser.
2. https://github.com/renpy/renpy/blob/8be361a33acbba3726fcea2b7b8e844ecd104101/renpy/ast.py#L85-L120
In second branch, it is still a string subclass, with one slot - compiled code object. I think this is a way to go, after some polishing, but we need to come up with a solution for `PyCode`.

**Comment by renpytom** [comment]
Looking at these two, I don't really like this. We're complicating the implementation to save relatively small amounts of memory, and that doesn't seem like it's a good trade.

Changes that only affect PyCode and PyExpr and that simplify script.py seem like a good idea, but changes that would make script.py more complex to save memory in PyCode and PyExpr don't seem worth it to me. (Especially when the savings is some fraction of 40 MB, in a game that's already very large.)

**Comment by Andykl** [comment]
Superseded by #5950
