### ISSUE TITLE
Allow menuset values to be overridden

### ISSUE THREAD

**Issue by mal** [renpy/renpy#6024]
Currently when using the `set` feature of the menu statement the literal text shown to the player is stored and used to avoid reshowing the same option when the menu is revisited. I would like to be able to override this behaviour and provide the identifying value myself.

There are several cases where this would be useful:
- The same identifier could be used for multiple options, such that choosing one disables not only itself, but any others sharing that identifier. i.e.
  Apple (key:fruit), Broccoli (key:vegetable), Carrot (key:vegetable), Orange (key:fruit)
- The same `set` could be used with multiple menus with overlapping keys allowing earlier choices to restrict later options. i.e.
  Smooth (key:edge), Orange (key:color), Triangle (key:shape)
  Sharp (key:edge), Pink (key:color), Hexagon (key:shape)
  Jagged (key:edge), Indigo (key:color), Square (key:shape)
- Changing the option string in episodic games would no longer re-enable the option (assuming the custom identifier was preserved).

I've already put together a quick version of this which leverages a `_key` argument on menu options which works, however it's not especially pretty, so I'm here to find out if there are better ideas about how it could be specified or in the extreme case whether we think it would be worth additional syntax.

Below is an example of how the current iteration looks in Ren'Py script:
```rpy
label start:
    scene black

    $ renpy.dynamic(foo=set())
    $ renpy.watch("foo")

    menu choose:
        set foo

        "Alpha" (_key="a"):
            jump choose

        "Bravo" (_key="b"):
            jump choose

        "Charlie" (_key="c"):
            jump choose

    "[''.join(sorted(foo))]" #=> abc
    return
```

**Comment by renpytom** [comment]
The ``set`` clause to ``menu`` is very old, existing from before when ``menu`` had support for ``if`` clauses. I'd suggest a way that does what you want, without adding new syntax or semantics, is: 

```renpy
label start:
    scene black

    $ renpy.dynamic(foo=set())
    $ renpy.watch("foo")

    menu choose:
        set foo

        "Alpha" if "a" not in foo:
            $ foo.add("a")
            jump choose

        "Bravo" if "b" not in foo:
            $ foo.add("b")
            jump choose

        "Charlie" if "c" not in foo:
            $ foo.add("c")
            jump choose

    "[''.join(sorted(foo))]" #=> abc
    return
```

And given how little set is used, this is probably better than adding functionality.

**Comment by mal** [comment]
Fair, though I will note this boilerplate does become rather unwieldy and prone to human error as the menu grows. Only needing to set/update a single value in menus of 20+ items, or when doing the inevitable copy-paste to add a new option is definitely a nice-to-have, especially when forgetting to update the second literal results in hard to spot (but easy to fix) bugs.

That said, I can understand not wanting to expand the codebase for what is quite a niche feature.

**Comment by shawna-p** [comment]
If I might suggest a syntax that I've actually made a custom menu for:

```renpy
menu:
  set fruits
  a "Apples":
    pass
  b "Bananas":
    pass
``` and the keys are "a" and "b". The keys are just an arbitrary string before the choice text which is used as an identifier.

Personally I would find this feature expansion *very* helpful for quickly identifying which choices were made, and potentially making some choices automatically exclude others with minimal overhead. I rarely use sets due to the limited way they store information + potential for problems if you try to expand on what's there by verbatim copying choice captions (which could have typos, or cause issues with translation).

A special key which is never added to the menu set would also be very helpful for something like a repeatable investigation dialogue where you can ask each question once and the option "That's all for now" is always available so the choice menu can be repeated and exited multiple times without removing the "That's all for now" option.
