### ISSUE TITLE
Some images wont load while no audio device is present.

### ISSUE THREAD

**Issue by AcidKitchen** [renpy/renpy#6030]
I've been playing some Ren'Py games over the past few days and noticed that some images weren't loading during gameplay. Curious about the issue, I decided to investigate today by checking the log file. The log indicated an error related to the audio endpoint.

I tried launching the game with my audio device activated, and it worked perfectly. However, this error only occurs if I start the game without the audio device being present. Interestingly, the game works fine if I disable the audio device after it has already started, but turning the audio device back on after the game has launched doesn't resolve the issue.

[log.txt](https://github.com/user-attachments/files/18233386/log.txt)

**Comment by renpytom** [comment]
Assuming the images not working are movies, that's normal - movies use the same media system as audio, so if the audio isn't working, movies won't either. 

Since every computer made in the last two decades comes with functional audio (even if it's not hooked up to anything), I'd say that if audio doesn't work, that's the problem.
