### ISSUE TITLE
Building documentation doesn't describe how to build full Ren'Py capable of making distributions

### ISSUE THREAD

**Issue by caryoscelus** [renpy/renpy#655]
Or, in other words, there's no instructions (or they are hidden too deep) for building contents of lib/ directory.

**Comment by renpytom** [comment]
Correct. Right now, the stuff to build lib/ is in the scripts at:

https://github.com/renpy/renpy-deps/tree/master/scripts

It's hard to document properly because it requires a windows, mac, and linux computer just to get started. The important parts are done the build_renpy_<platform>.sh scripts, followed by the the build_finish.sh script. (The build_<platform>.sh scripts take care of building renpy-deps from scratch on each platform.)

**Comment by caryoscelus** [comment]
Ah, it's in separate repo. I see, thanks! I'll try to figure out how it all works..

Anyway, i think it would make sense to mention renpy-deps in main README.

**Comment by renpytom** [comment]
This has been fixed by renpy/renpy-build, which fully automates the build process.
