### ISSUE TITLE
'area' property no longer works in 'screen' object since 6.17

### ISSUE THREAD

**Issue by nyfair** [renpy/renpy#659]
Consider the following example

```python
screen say:
    if p == 'l':
        $ xy = (0.1, 0.5)
    elif p == 'r':
        $ xy = (0.9, 0.5)
    elif p == 'c':
        $ xy = (0.5, 0.5)
    window:
        vbox:
            area (0, 0, 150, 100)
            align xy
            text who id 'who' ypos -0.5
            text what id 'what'

define el = Character('Eileen', show_p='l')
define er = Character('Eileen', show_p='r')
define ec = Character('Eileen', show_p='c')

label start:
    el "Left"
    er "Right"
    ec "Center"
```

All the 'say' dialogues will be in the top left corner

**Comment by renpytom** [comment]
So, there are a lot of problem with this code, to the point where I don't think it's showing a problem in Ren'Py.

The first is that you're placing the vbox within the window. That's probably not going to work - usually, you want to place the window itself, and not the thing it contains. (It's possible you meant to place the vbox inside the window, in which case, it's fine.)

The more important problem is that you're giving the vbox conflicting placement information. The area always places it at (0, 0) while the align places it at one of a number of other locations. Since these conflict, the behavior is undefined. I'd suggest using xysize instead of area to set the size of the vbox:

```
    window:
        vbox:
            xysize (150, 100)
            align xy
            text who id 'who' ypos -0.5
            text what id 'what'
```

That resolves the conflict, and should make Ren'Py do what you want.

**Comment by nyfair** [comment]
Yes, thanks for your help
