### ISSUE TITLE
It will be better if renpy supports customize plugins

### ISSUE THREAD

**Issue by bbs3223474** [renpy/renpy#686]
Compare with krkr2 and Ren'py engine, I noticed although krkr2 is a very simple engine that can only create some basic visual novel games, but it supports plugins. And we can use those plugins freely to make some advanced works. Like, I can use dynamic character images in the game, or multiple layers background, encrypt game scripts, even I can put a sub engine in it. These are not available in the original engine.
Look back to Ren'py, it contains complex source codes and some advanced functions, but I still feel not enough. Sometimes I want to create a Japanese-styled game, but Ren'py couldn't give me the things I want, or I have to look through a lot of instructions then understand how to use them. If we need to add some new things to engine, we still have to modify the source code rather than just realize them by put plugins inside my project.
I think Ren'py will be better if one day it can supports customize plugins. Engine just have to provide an interface and everyone can write their own plugins for it.

**Comment by weetabix-su** [comment]
Two things about this:
1. Though it lacks a simpler plugin system, Ren'Py supports the importation of Python code and modules from the game folder and files. From there you can add newer functions without fiddling with the engine's code.
2. Ren'Py operates within PyGame and is limited by it as well. Adding a bit here and there may drastically impede its capability.

**Comment by renpytom** [comment]
Ren'Py takes a different approach to customization than krkr2 does. Ren'Py allows "plugins" to be written in python as part of a Ren'Py script file, such as a creator-defined displayable:

http://www.renpy.org/doc/html/udd.html

CDDs can pull in C code using the standard Python import mechanism, if Python alone is not enough. 

This philosophy persists throughout the engine. For example, the say statement:

```
e "Hello, World."
```

is turned into the Python function call:

```
e("Hello, World.", interact=True)
```

where e can be replaced with any user-defined function. The result is that you can do customization at the game level, rather than having to depend on compiled plugins. (Which is good, since compiling for the 5 platforms Ren'Py supports is harder than for a single platform.)

I do hope to add ways of tapping into Ren'Py's OpenGL pipeline, which is the current limiting factor functionality-wise, but that's going to have to wait for me to get time to work on it.
