### ISSUE TITLE
Generator issues?

### ISSUE THREAD

**Issue by XelaPy** [renpy/renpy#732]
Since generators cannot be pickled, is there any good workaround for this? What is REALLY weird is even if the generator is deleted, there are still issues with saving/console :(

```python
init python:
    from itertools import count

# The game starts here.
label start:
    $ c = count()
    "Save or call Console"
    return
```

**Comment by renpytom** [comment]
What's happening is that to find out what objects it needs to save, Ren'Py has to walk through the tree of all objects. It does so by enumerating the fields of all reachable objects, iterating through all iterable objects, and getting all the values that are part of dict-like objects. Ren'Py does this to make sure it knows about all objects that could participate in rollback.

The problem is that count is its own iterator, and when you iterate over it, that iteration lasts forever. So that leads to problems. 

In general, iterators and generators can't be pickled. count is a weird case, since it can, but it has its own problems in terms of causing infinite iteration. Unfortunately, you can't save them to save files.
