### ISSUE TITLE
There is no "Call" action usable as a button action

### ISSUE THREAD

**Issue by Klaim** [renpy/renpy#784]
Hi, I started a thread in this forum and pointed a lack of "Call" action usable in button's action.
Here is a complete explanation of the problem: http://lemmasoft.renai.us/forums/viewtopic.php?p=393761#p393761

Basically:

    screen special_actions_screen():
        window id "special_actions_window":
            # place the window on the right of the screen
            vbox:
                # ...
                button:
                    text "Punch In The Face"
                    action Jump("on_punch_1") # OK, but never return!
                button:
                    text "Smile/Grin"
                    action Call("on_smile_1") # ERROR: Call is not defined

I need a Call action to be able to return from a label (see the thread for a full example of my use case) exactly like when you use the "call" statement.

My current "hack" (which seems to work is):

                    action Function(Renpy.call, "on_smile_1") # Equivalent to "call on_smile_1"

However I suspect that this is not the intended way to use button's action property. Jump action don't allow me to return from a label as it is equivalent to a "jump" statement.

Therefore I think that a Call action is missing (in the documentation too).

I could provide a patch but I see several ways of doing this and I'm not familiar with this codebase so I might need guidance if there are hidden difficulties with this.

Also, I don't understand why this is not already available. Is there some complexities with this feature that I am not perceiving? Or maybe it have just been forgotten? I suspect that a lot of people would have needed to do this so I'm a bit lost as to why it's not already available.

**Comment by renpytom** [comment]
The problem is that call is a little strange in Ren'Py. We can only transfer control to the start or end of statements, so the problem is that if we had call like you listed in the example above, it would end the screen statement. That might be acceptable for you, but it's a bit confusing. I don't want a Call action because it would increase my support burden.

**Comment by Klaim** [comment]
I might be misunderstanding you, what do you mean by "it would end the screen statement"? When I tried this it didn't seem to end any screen, not even the one with the buttons, but maybe you mean it was something not visible?

**Comment by renpytom** [comment]
Are you invoking your screen with "show screen" or "call screen"?

**Comment by Klaim** [comment]
In my test demo I used `show screen`.
Here is the full code:

    screen special_actions_screen():
        window id "special_actions_window":
            
            at topright        
            
            # place the window on the right of the screen
            vbox:
                at right
                # ...
                button:
                    text "Smile/Grin"
                    action Function(renpy.call, label="on_smile_1") # ugly but works as expected
                button:
                    text "Punch In The Face"
                    action Jump("on_punch_1")

    label start:

                    
        show screen special_actions_screen
        
        define A = Character(name="Anna")
        define B = Character(name="Barbara")
        
        jump scene_1


    label scene_1: 

        A "Hello!"
        B "Hello, how are you?"
        A "I'm fine, thank you! And you?"
        B "I'm fine too, let's have fun now!"
        A "Yes! Here are the sausages!"
        "Happy Ending."
        return
      
    label on_smile_1:
       "My grin shines a lot."
       "It makes everybody smile in the room too!"
       "I feel happy but a bit dumb too, but oh well..."
       return #Back to the previous dialog.

    label on_punch_1:
       "After this, everything went very fast."
       "I ended up in jail..."
       "...and stayed there until the end of my life."
       "BAD ENDING"
       return


Try to press the "smile" button while in the dialog to see the thing.

Maybe this code don't show the issue you were pointing? I don't see the menu of the screen disappear so I assumed that it was working as expected.

**Comment by renpytom** [comment]
Your code exhibits a variant of the problem I described (poorly). 

If you're on the first line of dialogue (by Anna), and you run a call, when you return you wind up on the second line of dialogue (by Barbara). This is probably not a problem in dialogue, since it's fairly transient in the first place, but was that first line to be something that shows a blocking screen, you'd have a problem.

I honestly think your code is probably the right level of convenience for such an iffy feature. What you have works, and will keep working - assuming that we consider these semantics working. But I think that if I make it more convenient, people will use the code without understanding the semantics.

**Comment by Klaim** [comment]
Ok so just so my understanding is clear:

 1. My solution works as long as I don't have another blocking screen, so basically I should hide the buttons in this case to avoid issues. For example I should hide the action buttons when I reach a menu/choice. Am I correct?
 2. No worries, I understand why it would not be very good for users to have easy access to this. I will just add my own Call action doing exactly that and it will be good for my specific case, assuming I understood you correctly. Is there other issues I should be aware of other than screen FUBAR potential?

**Comment by renpytom** [comment]
Correct, since doing a call during a choice will abort the menu, and go to the next statement. (I think. It might just crash in that case - I haven't thoroughly analyzed it.)

And 2 seems right. I don't think there are issues during normal dialogue, but there may be problems with arbitrary other statements. (For example, it would break renpy.input, since the python block would return without the variable being assigned.)

**Comment by Klaim** [comment]
Thanks for these details, I will experiment see how Renpy behaves in my cases. Hopefully I will be able to still do what I want, it seems totally doable.

**Comment by renpytom** [comment]
Call now exists as an action, for the record.

**Comment by Klaim** [comment]
Yes thanks, I remarked that recently :)

By the way, does it still have the same potential issue with blocking screens?
