### ISSUE TITLE
An Audio Issue

### ISSUE THREAD

**Issue by Renimator** [renpy/renpy#805]
The audio volume is irregular in the attached project, varies as it plays. 
[Test.zip](https://github.com/renpy/renpy/files/60657/Test.zip)

**Comment by XelaPy** [comment]
More specifically, volume on the newly created channel is not constant and changed sometimes even during the rollback.

**Comment by Renimator** [comment]
Thanks for a followup, Xela! This is very important for my game so I hope it can be fixed!

**Comment by XelaPy** [comment]
You don't really have to wait for it to get fixed if you're in a hurry, you can adjust the volume on a mixer once it is created, look for it in the docs. It should be constant then.

**Comment by Renimator** [comment]
I've been looking but I could not find how to force the volume on each mixer to be constant. Is it possible?

**Comment by renpytom** [comment]
I don't think there's a real problem here. When you play the same pure tone on two channels, the two tones will constructively or destructively interfere with each other. The result will sound like you're getting the same sound with different volume - which is what you're getting. But this shouldn't be a problem for dialogue, music, etc .

**Comment by Renimator** [comment]
I understand somewhat but then the interfering sound should always be the same, isn't it? Or this kind of irregularity is unavoidable?

**Comment by renpytom** [comment]
No, since the phase matters. Take a look at:

![Sine Wave Image]
(http://www.acs.psu.edu/drussell/Demos/superposition/interference.gif)

basically, when you click to start the second sound controls the phase (offset) of the second copy of the sound relative to the first. That phase can do anything from cancelling the sound entirely to doubling the volume. 

Try replacing the sample sound with a recording of voices and watch the problem go away.

**Comment by Renimator** [comment]
Wow, I've never thought about this. Very informative! Thank you!
I also would like to know how renpy handles mixes. In this case 50%+50% or 100%+100%?

**Comment by renpytom** [comment]
It's 100%+100%. It has to be, otherwise playing a second channel of silence would lower the sound on the first. (Half it physically, but not perceptually.)

I'm closing this as a bug, but posting it on twitter since it's probably one of the more interesting non-bugs I've seen.
