### ISSUE TITLE
Improve Progress Screen

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#933]
- [ ] Show total playtime.
- [ ] Show time + lines in current session.
- [ ] Document and make available via P?

This is the shift+alt+P screen.

**Comment by hsandt** [comment]
Hey, your last commit added new dialogue blocks count, but not the 3 others, so the issue's 3 tasks are not done yet. Should we reopen this issue?

Btw my new dialogue blocks count = seen count even after reloading or on new games, so I don't see the advantage of this (I thought it was to help players doing reruns to check if they discovered new story branches?)

Otherwise I came here looking for progress on total playtime. I come from https://lemmasoft.renai.us/forums/viewtopic.php?t=40407 which is about showing playtime on savegame info. I think it's a very useful feature to have, standardized in RPG, etc. and that should be standard, because most Renpy devs won't do the extra work to add it, but many players will benefit from it.

In the meantime, I'm still happy to have discovered Shift+Alt+P, it helps me see how far in the game I am without comparing playtime to average game playtime written on the game page description.
